-- @plm SRS-001  운동 카탈로그 시드 336종 — **생성물이다. 손으로 고치지 않는다.**
--
-- 원본: app/src/data/seed/exercises.seed.ts · app/src/data/seed/substitutes.seed.ts
-- 재생성: make gen-exercise-seed   (scripts/gen-exercise-seed.mjs)
--
-- 멱등하다: id가 같으면 갱신하되, **실제로 달라진 행만** 건드린다(updated_at이 매번 튀면
-- WatchCatalog 구독자가 바뀌지도 않은 카탈로그를 계속 다시 읽는다).
-- 커스텀 종목(is_custom)은 이 문장이 만들지도 덮지도 않는다.

INSERT INTO exercises (id, name_ko, name_en, primary_muscles, secondary_muscles, equipment, kind, load_mode, substitute_ids)
VALUES
  ('seed-barbell-bench-press', '바벨 벤치프레스', 'Barbell Bench Press', '{"chest"}', '{"triceps","shoulders"}', 'barbell', NULL, NULL, '{"seed-dumbbell-bench-press","seed-smith-machine-bench-press","seed-chest-press-machine","seed-push-up","seed-dips"}'),
  ('seed-incline-press', '인클라인 프레스 (바벨)', 'Incline Press', '{"chest"}', '{"shoulders","triceps"}', 'barbell', NULL, NULL, '{"seed-barbell-bench-press","seed-dumbbell-bench-press","seed-chest-press-machine","seed-push-up","seed-dips"}'),
  ('seed-incline-press-dumbbell', '인클라인 프레스 (덤벨)', 'Incline Press (Dumbbell)', '{"chest"}', '{"shoulders","triceps"}', 'dumbbell', NULL, NULL, '{}'),
  ('seed-incline-press-machine', '인클라인 프레스 (머신)', 'Incline Press (Machine)', '{"chest"}', '{"shoulders","triceps"}', 'machine', NULL, NULL, '{}'),
  ('seed-incline-press-smith', '인클라인 프레스 (스미스)', 'Incline Press (Smith)', '{"chest"}', '{"shoulders","triceps"}', 'smith', NULL, NULL, '{}'),
  ('seed-decline-barbell-press', '디클라인 프레스 (바벨)', 'Decline Barbell Press', '{"chest"}', '{"triceps"}', 'barbell', NULL, NULL, '{"seed-decline-dumbbell-press","seed-barbell-bench-press","seed-dumbbell-bench-press","seed-dips","seed-chest-press-machine"}'),
  ('seed-dumbbell-bench-press', '덤벨 벤치프레스', 'Dumbbell Bench Press', '{"chest"}', '{"triceps","shoulders"}', 'dumbbell', NULL, NULL, '{"seed-barbell-bench-press","seed-smith-machine-bench-press","seed-chest-press-machine","seed-push-up","seed-incline-press"}'),
  ('seed-decline-dumbbell-press', '디클라인 프레스 (덤벨)', 'Decline Dumbbell Press', '{"chest"}', '{"triceps"}', 'dumbbell', NULL, NULL, '{"seed-decline-barbell-press","seed-dumbbell-bench-press","seed-dips","seed-chest-press-machine","seed-barbell-bench-press"}'),
  ('seed-dumbbell-fly', '덤벨 플라이', 'Dumbbell Fly', '{"chest"}', '{}', 'dumbbell', NULL, NULL, '{"seed-cable-crossover","seed-pec-deck-fly","seed-low-cable-fly","seed-incline-dumbbell-fly","seed-chest-press-machine"}'),
  ('seed-incline-dumbbell-fly', '인클라인 덤벨 플라이', 'Incline Dumbbell Fly', '{"chest"}', '{}', 'dumbbell', NULL, NULL, '{"seed-low-cable-fly","seed-dumbbell-fly","seed-cable-crossover","seed-pec-deck-fly","seed-incline-press"}'),
  ('seed-cable-crossover', '케이블 크로스오버', 'Cable Crossover', '{"chest"}', '{}', 'cable', NULL, NULL, '{"seed-pec-deck-fly","seed-dumbbell-fly","seed-low-cable-fly","seed-incline-dumbbell-fly","seed-chest-press-machine"}'),
  ('seed-low-cable-fly', '로우 케이블 플라이', 'Low Cable Fly', '{"chest"}', '{}', 'cable', NULL, NULL, '{"seed-cable-crossover","seed-incline-dumbbell-fly","seed-pec-deck-fly","seed-dumbbell-fly","seed-incline-press"}'),
  ('seed-pec-deck-fly', '펙 덱 플라이', 'Pec Deck Fly', '{"chest"}', '{}', 'machine', NULL, NULL, '{"seed-cable-crossover","seed-dumbbell-fly","seed-low-cable-fly","seed-incline-dumbbell-fly","seed-chest-press-machine"}'),
  ('seed-chest-press-machine', '체스트 프레스 머신', 'Chest Press Machine', '{"chest"}', '{"triceps"}', 'machine', NULL, NULL, '{"seed-smith-machine-bench-press","seed-barbell-bench-press","seed-dumbbell-bench-press","seed-push-up","seed-incline-press"}'),
  ('seed-smith-machine-bench-press', '스미스 벤치프레스', 'Smith Machine Bench Press', '{"chest"}', '{"triceps"}', 'smith', NULL, NULL, '{"seed-barbell-bench-press","seed-dumbbell-bench-press","seed-chest-press-machine","seed-push-up","seed-dips"}'),
  ('seed-dips', '딥스', 'Dips', '{"chest"}', '{"triceps"}', 'bodyweight', NULL, NULL, '{"seed-push-up","seed-chest-press-machine","seed-decline-barbell-press","seed-bench-dip","seed-barbell-bench-press"}'),
  ('seed-push-up', '푸시업', 'Push Up', '{"chest"}', '{"triceps","shoulders"}', 'bodyweight', NULL, NULL, '{"seed-incline-push-up","seed-dips","seed-chest-press-machine","seed-dumbbell-bench-press","seed-barbell-bench-press"}'),
  ('seed-incline-push-up', '인클라인 푸시업', 'Incline Push Up', '{"chest"}', '{"triceps"}', 'bodyweight', NULL, NULL, '{"seed-push-up","seed-chest-press-machine","seed-incline-press","seed-dips","seed-dumbbell-bench-press"}'),
  ('seed-deadlift', '데드리프트', 'Deadlift', '{"back"}', '{"glutes","hamstrings"}', 'barbell', NULL, NULL, '{"seed-sumo-deadlift","seed-rack-pull","seed-romanian-deadlift","seed-barbell-row","seed-good-morning"}'),
  ('seed-sumo-deadlift', '스모 데드리프트', 'Sumo Deadlift', '{"back"}', '{"glutes","quads"}', 'barbell', NULL, NULL, '{"seed-deadlift","seed-rack-pull","seed-romanian-deadlift","seed-kettlebell-swing","seed-good-morning"}'),
  ('seed-rack-pull', '랙 풀', 'Rack Pull', '{"back"}', '{"traps"}', 'barbell', NULL, NULL, '{"seed-deadlift","seed-sumo-deadlift","seed-barbell-row","seed-romanian-deadlift","seed-good-morning"}'),
  ('seed-barbell-row', '바벨 로우', 'Barbell Row', '{"back"}', '{"biceps"}', 'barbell', NULL, NULL, '{"seed-pendlay-row","seed-dumbbell-row","seed-t-bar-row","seed-machine-row","seed-seated-cable-row"}'),
  ('seed-pendlay-row', '펜들레이 로우', 'Pendlay Row', '{"back"}', '{"biceps"}', 'barbell', NULL, NULL, '{"seed-barbell-row","seed-t-bar-row","seed-dumbbell-row","seed-machine-row","seed-seated-cable-row"}'),
  ('seed-t-bar-row', '티바 로우', 'T-Bar Row', '{"back"}', '{"biceps"}', 'barbell', NULL, NULL, '{"seed-barbell-row","seed-pendlay-row","seed-machine-row","seed-seated-cable-row","seed-dumbbell-row"}'),
  ('seed-dumbbell-row', '덤벨 로우', 'Dumbbell Row', '{"back"}', '{"biceps"}', 'dumbbell', NULL, NULL, '{"seed-seated-cable-row","seed-machine-row","seed-barbell-row","seed-t-bar-row","seed-pendlay-row"}'),
  ('seed-seated-cable-row', '시티드 케이블 로우', 'Seated Cable Row', '{"back"}', '{"biceps"}', 'cable', NULL, NULL, '{"seed-machine-row","seed-dumbbell-row","seed-barbell-row","seed-t-bar-row","seed-pendlay-row"}'),
  ('seed-lat-pulldown', '랫 풀다운', 'Lat Pulldown', '{"back"}', '{"biceps"}', 'cable', NULL, NULL, '{"seed-pull-up","seed-close-grip-pulldown","seed-chin-up","seed-machine-row","seed-seated-cable-row"}'),
  ('seed-close-grip-pulldown', '클로즈그립 풀다운', 'Close Grip Pulldown', '{"back"}', '{"biceps"}', 'cable', NULL, NULL, '{"seed-lat-pulldown","seed-chin-up","seed-pull-up","seed-seated-cable-row","seed-machine-row"}'),
  ('seed-straight-arm-pulldown', '스트레이트암 풀다운', 'Straight Arm Pulldown', '{"back"}', '{}', 'cable', NULL, NULL, '{"seed-lat-pulldown","seed-pull-up","seed-close-grip-pulldown","seed-seated-cable-row","seed-dumbbell-row"}'),
  ('seed-pull-up', '풀업', 'Pull Up', '{"back"}', '{"biceps"}', 'bodyweight', NULL, NULL, '{"seed-chin-up","seed-lat-pulldown","seed-close-grip-pulldown","seed-machine-row"}'),
  ('seed-chin-up', '친업', 'Chin Up', '{"back"}', '{"biceps"}', 'bodyweight', NULL, NULL, '{"seed-pull-up","seed-lat-pulldown","seed-close-grip-pulldown","seed-machine-row"}'),
  ('seed-machine-row', '머신 로우', 'Machine Row', '{"back"}', '{"biceps"}', 'machine', NULL, NULL, '{"seed-seated-cable-row","seed-dumbbell-row","seed-barbell-row","seed-t-bar-row","seed-pendlay-row"}'),
  ('seed-hyperextension', '하이퍼익스텐션', 'Hyperextension', '{"back"}', '{"glutes","hamstrings"}', 'bodyweight', NULL, NULL, '{"seed-good-morning","seed-romanian-deadlift","seed-stiff-leg-deadlift","seed-deadlift","seed-glute-bridge"}'),
  ('seed-good-morning', '굿모닝', 'Good Morning', '{"back"}', '{"hamstrings","glutes"}', 'barbell', NULL, NULL, '{"seed-romanian-deadlift","seed-stiff-leg-deadlift","seed-hyperextension","seed-deadlift","seed-rack-pull"}'),
  ('seed-overhead-press', '오버헤드 프레스', 'Overhead Press', '{"shoulders"}', '{"triceps"}', 'barbell', NULL, NULL, '{"seed-military-press","seed-dumbbell-shoulder-press","seed-shoulder-press-machine","seed-arnold-press"}'),
  ('seed-military-press', '밀리터리 프레스', 'Military Press', '{"shoulders"}', '{"triceps"}', 'barbell', NULL, NULL, '{"seed-overhead-press","seed-dumbbell-shoulder-press","seed-shoulder-press-machine","seed-arnold-press"}'),
  ('seed-dumbbell-shoulder-press', '덤벨 숄더 프레스', 'Dumbbell Shoulder Press', '{"shoulders"}', '{"triceps"}', 'dumbbell', NULL, NULL, '{"seed-arnold-press","seed-overhead-press","seed-shoulder-press-machine","seed-military-press"}'),
  ('seed-arnold-press', '아놀드 프레스', 'Arnold Press', '{"shoulders"}', '{"triceps"}', 'dumbbell', NULL, NULL, '{"seed-dumbbell-shoulder-press","seed-shoulder-press-machine","seed-overhead-press","seed-military-press"}'),
  ('seed-shoulder-press-machine', '숄더 프레스 머신', 'Shoulder Press Machine', '{"shoulders"}', '{"triceps"}', 'machine', NULL, NULL, '{"seed-dumbbell-shoulder-press","seed-overhead-press","seed-arnold-press","seed-military-press"}'),
  ('seed-side-lateral-raise', '덤벨 레터럴 레이즈', 'Side Lateral Raise', '{"shoulders"}', '{}', 'dumbbell', NULL, NULL, '{"seed-cable-lateral-raise","seed-machine-lateral-raise","seed-upright-row","seed-front-raise"}'),
  ('seed-cable-lateral-raise', '케이블 레터럴 레이즈', 'Cable Lateral Raise', '{"shoulders"}', '{}', 'cable', NULL, NULL, '{"seed-side-lateral-raise","seed-machine-lateral-raise","seed-upright-row","seed-front-raise"}'),
  ('seed-machine-lateral-raise', '머신 레터럴 레이즈', 'Machine Lateral Raise', '{"shoulders"}', '{}', 'machine', NULL, NULL, '{"seed-side-lateral-raise","seed-cable-lateral-raise","seed-upright-row","seed-front-raise"}'),
  ('seed-front-raise', '프론트 레이즈 (덤벨)', 'Front Raise', '{"shoulders"}', '{}', 'dumbbell', NULL, NULL, '{"seed-side-lateral-raise","seed-cable-lateral-raise","seed-overhead-press","seed-dumbbell-shoulder-press"}'),
  ('seed-rear-delt-fly', '덤벨 리어 델트 플라이', 'Rear Delt Fly', '{"shoulders"}', '{}', 'dumbbell', NULL, NULL, '{"seed-reverse-pec-deck","seed-face-pull","seed-barbell-row","seed-seated-cable-row"}'),
  ('seed-reverse-pec-deck', '리버스 펙 덱', 'Reverse Pec Deck', '{"shoulders"}', '{}', 'machine', NULL, NULL, '{"seed-rear-delt-fly","seed-face-pull","seed-barbell-row","seed-seated-cable-row"}'),
  ('seed-face-pull', '페이스 풀', 'Face Pull', '{"shoulders"}', '{"traps"}', 'cable', NULL, NULL, '{"seed-reverse-pec-deck","seed-rear-delt-fly","seed-barbell-row","seed-upright-row"}'),
  ('seed-upright-row', '업라이트 로우 (바벨)', 'Upright Row', '{"shoulders"}', '{"traps"}', 'barbell', NULL, NULL, '{"seed-side-lateral-raise","seed-cable-lateral-raise","seed-machine-lateral-raise","seed-face-pull"}'),
  ('seed-barbell-curl', '바벨 컬', 'Barbell Curl', '{"biceps"}', '{}', 'barbell', NULL, NULL, '{"seed-ez-bar-curl","seed-dumbbell-curl","seed-cable-curl","seed-machine-curl","seed-preacher-curl"}'),
  ('seed-ez-bar-curl', '이지바 컬', 'EZ-Bar Curl', '{"biceps"}', '{}', 'barbell', NULL, NULL, '{"seed-barbell-curl","seed-dumbbell-curl","seed-cable-curl","seed-preacher-curl","seed-machine-curl"}'),
  ('seed-dumbbell-curl', '덤벨 컬', 'Dumbbell Curl', '{"biceps"}', '{}', 'dumbbell', NULL, NULL, '{"seed-barbell-curl","seed-ez-bar-curl","seed-cable-curl","seed-incline-dumbbell-curl","seed-machine-curl"}'),
  ('seed-hammer-curl', '해머 컬 (덤벨)', 'Hammer Curl', '{"biceps"}', '{"forearms"}', 'dumbbell', NULL, NULL, '{"seed-dumbbell-curl","seed-reverse-barbell-curl","seed-cable-curl","seed-barbell-curl","seed-concentration-curl"}'),
  ('seed-incline-dumbbell-curl', '인클라인 덤벨 컬', 'Incline Dumbbell Curl', '{"biceps"}', '{}', 'dumbbell', NULL, NULL, '{"seed-dumbbell-curl","seed-spider-curl","seed-concentration-curl","seed-cable-curl","seed-preacher-curl"}'),
  ('seed-preacher-curl', '프리처 컬 (바벨)', 'Preacher Curl', '{"biceps"}', '{}', 'barbell', NULL, NULL, '{"seed-spider-curl","seed-machine-curl","seed-ez-bar-curl","seed-barbell-curl","seed-cable-curl"}'),
  ('seed-concentration-curl', '컨센트레이션 컬', 'Concentration Curl', '{"biceps"}', '{}', 'dumbbell', NULL, NULL, '{"seed-dumbbell-curl","seed-spider-curl","seed-preacher-curl","seed-incline-dumbbell-curl","seed-cable-curl"}'),
  ('seed-cable-curl', '케이블 컬', 'Cable Curl', '{"biceps"}', '{}', 'cable', NULL, NULL, '{"seed-dumbbell-curl","seed-barbell-curl","seed-ez-bar-curl","seed-machine-curl","seed-preacher-curl"}'),
  ('seed-spider-curl', '스파이더 컬', 'Spider Curl', '{"biceps"}', '{}', 'dumbbell', NULL, NULL, '{"seed-preacher-curl","seed-concentration-curl","seed-incline-dumbbell-curl","seed-dumbbell-curl","seed-cable-curl"}'),
  ('seed-machine-curl', '머신 컬', 'Machine Curl', '{"biceps"}', '{}', 'machine', NULL, NULL, '{"seed-cable-curl","seed-preacher-curl","seed-barbell-curl","seed-ez-bar-curl","seed-dumbbell-curl"}'),
  ('seed-close-grip-bench-press', '클로즈 그립 벤치프레스', 'Close Grip Bench Press', '{"triceps"}', '{"chest"}', 'barbell', NULL, NULL, '{"seed-skull-crusher","seed-diamond-push-up","seed-dips","seed-triceps-pushdown","seed-bench-dip"}'),
  ('seed-triceps-pushdown', '트라이셉스 푸시다운', 'Triceps Pushdown', '{"triceps"}', '{}', 'cable', NULL, NULL, '{"seed-rope-pushdown","seed-skull-crusher","seed-overhead-triceps-extension","seed-cable-overhead-extension","seed-bench-dip"}'),
  ('seed-rope-pushdown', '로프 푸시다운', 'Rope Pushdown', '{"triceps"}', '{}', 'cable', NULL, NULL, '{"seed-triceps-pushdown","seed-cable-overhead-extension","seed-skull-crusher","seed-overhead-triceps-extension","seed-bench-dip"}'),
  ('seed-overhead-triceps-extension', '오버헤드 트라이셉스 익스텐션', 'Overhead Triceps Extension', '{"triceps"}', '{}', 'dumbbell', NULL, NULL, '{"seed-cable-overhead-extension","seed-skull-crusher","seed-rope-pushdown","seed-triceps-pushdown","seed-triceps-kickback"}'),
  ('seed-cable-overhead-extension', '케이블 오버헤드 익스텐션', 'Cable Overhead Extension', '{"triceps"}', '{}', 'cable', NULL, NULL, '{"seed-overhead-triceps-extension","seed-rope-pushdown","seed-skull-crusher","seed-triceps-pushdown","seed-triceps-kickback"}'),
  ('seed-skull-crusher', '스컬 크러셔 (바벨)', 'Skull Crusher', '{"triceps"}', '{}', 'barbell', NULL, NULL, '{"seed-overhead-triceps-extension","seed-triceps-pushdown","seed-close-grip-bench-press","seed-cable-overhead-extension","seed-rope-pushdown"}'),
  ('seed-triceps-kickback', '트라이셉스 킥백 (덤벨)', 'Triceps Kickback', '{"triceps"}', '{}', 'dumbbell', NULL, NULL, '{"seed-rope-pushdown","seed-triceps-pushdown","seed-overhead-triceps-extension","seed-bench-dip","seed-skull-crusher"}'),
  ('seed-bench-dip', '벤치 딥스', 'Bench Dip', '{"triceps"}', '{}', 'bodyweight', NULL, NULL, '{"seed-dips","seed-diamond-push-up","seed-triceps-pushdown","seed-close-grip-bench-press","seed-rope-pushdown"}'),
  ('seed-diamond-push-up', '다이아몬드 푸시업', 'Diamond Push Up', '{"triceps"}', '{"chest"}', 'bodyweight', NULL, NULL, '{"seed-bench-dip","seed-dips","seed-close-grip-bench-press","seed-push-up","seed-triceps-pushdown"}'),
  ('seed-wrist-curl', '리스트 컬 (바벨)', 'Wrist Curl', '{"forearms"}', '{}', 'barbell', NULL, NULL, '{"seed-reverse-wrist-curl","seed-reverse-barbell-curl","seed-farmer-s-walk"}'),
  ('seed-reverse-wrist-curl', '리버스 리스트 컬', 'Reverse Wrist Curl', '{"forearms"}', '{}', 'barbell', NULL, NULL, '{"seed-wrist-curl","seed-reverse-barbell-curl","seed-hammer-curl","seed-farmer-s-walk"}'),
  ('seed-reverse-barbell-curl', '리버스 바벨 컬', 'Reverse Barbell Curl', '{"forearms"}', '{"biceps"}', 'barbell', NULL, NULL, '{"seed-hammer-curl","seed-reverse-wrist-curl","seed-barbell-curl","seed-wrist-curl","seed-ez-bar-curl"}'),
  ('seed-farmer-s-walk', '파머스 워크', 'Farmer''s Walk', '{"forearms"}', '{"traps"}', 'dumbbell', NULL, NULL, '{"seed-barbell-shrug","seed-dumbbell-shrug","seed-wrist-curl","seed-reverse-wrist-curl"}'),
  ('seed-barbell-squat', '바벨 스쿼트', 'Barbell Squat', '{"quads"}', '{"glutes","hamstrings"}', 'barbell', NULL, NULL, '{"seed-high-bar-squat","seed-front-squat","seed-smith-machine-squat","seed-hack-squat","seed-leg-press","seed-goblet-squat"}'),
  ('seed-front-squat', '프론트 스쿼트', 'Front Squat', '{"quads"}', '{"glutes"}', 'barbell', NULL, NULL, '{"seed-high-bar-squat","seed-barbell-squat","seed-goblet-squat","seed-hack-squat","seed-smith-machine-squat","seed-leg-press"}'),
  ('seed-high-bar-squat', '하이바 스쿼트', 'High Bar Squat', '{"quads"}', '{"glutes"}', 'barbell', NULL, NULL, '{"seed-barbell-squat","seed-front-squat","seed-smith-machine-squat","seed-hack-squat","seed-leg-press","seed-goblet-squat"}'),
  ('seed-hack-squat', '핵 스쿼트', 'Hack Squat', '{"quads"}', '{"glutes"}', 'machine', NULL, NULL, '{"seed-leg-press","seed-smith-machine-squat","seed-barbell-squat","seed-high-bar-squat","seed-front-squat","seed-leg-extension"}'),
  ('seed-leg-press', '레그 프레스', 'Leg Press', '{"quads"}', '{"glutes"}', 'machine', NULL, NULL, '{"seed-hack-squat","seed-smith-machine-squat","seed-barbell-squat","seed-goblet-squat","seed-leg-extension","seed-bulgarian-split-squat"}'),
  ('seed-leg-extension', '레그 익스텐션', 'Leg Extension', '{"quads"}', '{}', 'machine', NULL, NULL, '{"seed-hack-squat","seed-leg-press","seed-goblet-squat","seed-bulgarian-split-squat","seed-lunge"}'),
  ('seed-goblet-squat', '고블릿 스쿼트', 'Goblet Squat', '{"quads"}', '{"glutes"}', 'dumbbell', NULL, NULL, '{"seed-front-squat","seed-high-bar-squat","seed-barbell-squat","seed-leg-press","seed-bulgarian-split-squat","seed-lunge"}'),
  ('seed-lunge', '런지 (덤벨)', 'Lunge', '{"quads"}', '{"glutes"}', 'dumbbell', NULL, NULL, '{"seed-walking-lunge","seed-bulgarian-split-squat","seed-step-up","seed-goblet-squat","seed-leg-press"}'),
  ('seed-walking-lunge', '워킹 런지', 'Walking Lunge', '{"quads"}', '{"glutes"}', 'dumbbell', NULL, NULL, '{"seed-lunge","seed-bulgarian-split-squat","seed-step-up","seed-goblet-squat","seed-leg-press"}'),
  ('seed-bulgarian-split-squat', '불가리안 스플릿 스쿼트 (덤벨)', 'Bulgarian Split Squat', '{"quads"}', '{"glutes"}', 'dumbbell', NULL, NULL, '{"seed-lunge","seed-walking-lunge","seed-step-up","seed-goblet-squat","seed-leg-press"}'),
  ('seed-smith-machine-squat', '스미스 스쿼트', 'Smith Machine Squat', '{"quads"}', '{"glutes"}', 'smith', NULL, NULL, '{"seed-hack-squat","seed-barbell-squat","seed-high-bar-squat","seed-leg-press","seed-front-squat","seed-goblet-squat"}'),
  ('seed-step-up', '스텝업', 'Step Up', '{"quads"}', '{"glutes"}', 'dumbbell', NULL, NULL, '{"seed-lunge","seed-walking-lunge","seed-bulgarian-split-squat","seed-goblet-squat","seed-leg-press"}'),
  ('seed-romanian-deadlift', '루마니안 데드리프트 (바벨)', 'Romanian Deadlift', '{"hamstrings"}', '{"glutes","back"}', 'barbell', NULL, NULL, '{"seed-stiff-leg-deadlift","seed-good-morning","seed-deadlift","seed-kettlebell-swing","seed-lying-leg-curl","seed-seated-leg-curl"}'),
  ('seed-stiff-leg-deadlift', '스티프 레그 데드리프트', 'Stiff Leg Deadlift', '{"hamstrings"}', '{"glutes"}', 'barbell', NULL, NULL, '{"seed-romanian-deadlift","seed-good-morning","seed-deadlift","seed-nordic-curl","seed-lying-leg-curl","seed-kettlebell-swing"}'),
  ('seed-lying-leg-curl', '라잉 레그 컬', 'Lying Leg Curl', '{"hamstrings"}', '{}', 'machine', NULL, NULL, '{"seed-seated-leg-curl","seed-leg-curl","seed-nordic-curl","seed-romanian-deadlift","seed-stiff-leg-deadlift"}'),
  ('seed-seated-leg-curl', '시티드 레그 컬', 'Seated Leg Curl', '{"hamstrings"}', '{}', 'machine', NULL, NULL, '{"seed-lying-leg-curl","seed-leg-curl","seed-nordic-curl","seed-romanian-deadlift","seed-stiff-leg-deadlift"}'),
  ('seed-leg-curl', '레그 컬', 'Leg Curl', '{"hamstrings"}', '{}', 'machine', NULL, NULL, '{"seed-lying-leg-curl","seed-seated-leg-curl","seed-nordic-curl","seed-romanian-deadlift","seed-stiff-leg-deadlift"}'),
  ('seed-nordic-curl', '노르딕 컬', 'Nordic Curl', '{"hamstrings"}', '{}', 'bodyweight', NULL, NULL, '{"seed-lying-leg-curl","seed-seated-leg-curl","seed-leg-curl","seed-stiff-leg-deadlift","seed-romanian-deadlift"}'),
  ('seed-hip-thrust', '힙 쓰러스트 (바벨)', 'Hip Thrust', '{"glutes"}', '{"hamstrings"}', 'barbell', NULL, NULL, '{"seed-glute-bridge","seed-kettlebell-swing","seed-cable-kickback","seed-romanian-deadlift","seed-stiff-leg-deadlift"}'),
  ('seed-glute-bridge', '글루트 브릿지', 'Glute Bridge', '{"glutes"}', '{"hamstrings"}', 'barbell', NULL, NULL, '{"seed-hip-thrust","seed-kettlebell-swing","seed-cable-kickback","seed-romanian-deadlift","seed-hip-abduction-machine"}'),
  ('seed-cable-kickback', '케이블 킥백', 'Cable Kickback', '{"glutes"}', '{}', 'cable', NULL, NULL, '{"seed-hip-abduction-machine","seed-glute-bridge","seed-hip-thrust","seed-kettlebell-swing"}'),
  ('seed-hip-abduction-machine', '힙 어브덕션 머신', 'Hip Abduction Machine', '{"glutes"}', '{}', 'machine', NULL, NULL, '{"seed-cable-kickback","seed-glute-bridge","seed-hip-thrust","seed-kettlebell-swing"}'),
  ('seed-kettlebell-swing', '케틀벨 스윙', 'Kettlebell Swing', '{"glutes"}', '{"hamstrings","back"}', 'kettlebell', NULL, NULL, '{"seed-romanian-deadlift","seed-hip-thrust","seed-glute-bridge","seed-stiff-leg-deadlift","seed-deadlift"}'),
  ('seed-standing-calf-raise', '스탠딩 카프 레이즈', 'Standing Calf Raise', '{"calves"}', '{}', 'machine', NULL, NULL, '{"seed-leg-press-calf-raise","seed-seated-calf-raise","seed-dumbbell-calf-raise"}'),
  ('seed-seated-calf-raise', '시티드 카프 레이즈', 'Seated Calf Raise', '{"calves"}', '{}', 'machine', NULL, NULL, '{"seed-standing-calf-raise","seed-leg-press-calf-raise","seed-dumbbell-calf-raise"}'),
  ('seed-leg-press-calf-raise', '레그 프레스 카프 레이즈', 'Leg Press Calf Raise', '{"calves"}', '{}', 'machine', NULL, NULL, '{"seed-standing-calf-raise","seed-seated-calf-raise","seed-dumbbell-calf-raise"}'),
  ('seed-dumbbell-calf-raise', '덤벨 카프 레이즈', 'Dumbbell Calf Raise', '{"calves"}', '{}', 'dumbbell', NULL, NULL, '{"seed-standing-calf-raise","seed-leg-press-calf-raise","seed-seated-calf-raise"}'),
  ('seed-plank', '플랭크', 'Plank', '{"abs"}', '{}', 'bodyweight', NULL, NULL, '{"seed-side-plank","seed-ab-wheel-rollout","seed-mountain-climber"}'),
  ('seed-side-plank', '사이드 플랭크', 'Side Plank', '{"abs"}', '{}', 'bodyweight', NULL, NULL, '{"seed-plank","seed-russian-twist","seed-bicycle-crunch","seed-mountain-climber"}'),
  ('seed-crunch', '크런치', 'Crunch', '{"abs"}', '{}', 'bodyweight', NULL, NULL, '{"seed-cable-crunch","seed-decline-sit-up","seed-reverse-crunch","seed-bicycle-crunch","seed-hanging-leg-raise"}'),
  ('seed-bicycle-crunch', '바이시클 크런치', 'Bicycle Crunch', '{"abs"}', '{}', 'bodyweight', NULL, NULL, '{"seed-crunch","seed-russian-twist","seed-reverse-crunch","seed-mountain-climber","seed-hanging-leg-raise"}'),
  ('seed-hanging-leg-raise', '행잉 레그 레이즈', 'Hanging Leg Raise', '{"abs"}', '{}', 'bodyweight', NULL, NULL, '{"seed-reverse-crunch","seed-decline-sit-up","seed-crunch","seed-cable-crunch","seed-ab-wheel-rollout"}'),
  ('seed-reverse-crunch', '리버스 크런치', 'Reverse Crunch', '{"abs"}', '{}', 'bodyweight', NULL, NULL, '{"seed-hanging-leg-raise","seed-crunch","seed-decline-sit-up","seed-bicycle-crunch","seed-cable-crunch"}'),
  ('seed-cable-crunch', '케이블 크런치', 'Cable Crunch', '{"abs"}', '{}', 'cable', NULL, NULL, '{"seed-crunch","seed-decline-sit-up","seed-hanging-leg-raise","seed-reverse-crunch","seed-ab-wheel-rollout"}'),
  ('seed-russian-twist', '러시안 트위스트', 'Russian Twist', '{"abs"}', '{}', 'bodyweight', NULL, NULL, '{"seed-bicycle-crunch","seed-side-plank","seed-mountain-climber"}'),
  ('seed-ab-wheel-rollout', '앱 휠 롤아웃', 'Ab Wheel Rollout', '{"abs"}', '{}', 'other', NULL, NULL, '{"seed-plank","seed-hanging-leg-raise","seed-cable-crunch","seed-crunch","seed-reverse-crunch"}'),
  ('seed-decline-sit-up', '디클라인 싯업', 'Decline Sit Up', '{"abs"}', '{}', 'bodyweight', NULL, NULL, '{"seed-crunch","seed-cable-crunch","seed-hanging-leg-raise","seed-reverse-crunch","seed-bicycle-crunch"}'),
  ('seed-mountain-climber', '마운틴 클라이머', 'Mountain Climber', '{"abs"}', '{"fullBody"}', 'bodyweight', NULL, NULL, '{"seed-plank","seed-bicycle-crunch","seed-russian-twist","seed-hanging-leg-raise","seed-reverse-crunch"}'),
  ('seed-barbell-shrug', '바벨 슈러그', 'Barbell Shrug', '{"traps"}', '{}', 'barbell', NULL, NULL, '{"seed-dumbbell-shrug","seed-rack-pull","seed-farmer-s-walk","seed-upright-row"}'),
  ('seed-dumbbell-shrug', '덤벨 슈러그', 'Dumbbell Shrug', '{"traps"}', '{}', 'dumbbell', NULL, NULL, '{"seed-barbell-shrug","seed-farmer-s-walk","seed-upright-row","seed-rack-pull"}'),
  ('seed-power-clean', '바벨 클린', 'Power Clean', '{"fullBody"}', '{"back","quads"}', 'barbell', NULL, NULL, '{"seed-clean-and-jerk","seed-snatch","seed-deadlift","seed-thruster","seed-kettlebell-swing"}'),
  ('seed-clean-and-jerk', '클린 앤 저크', 'Clean and Jerk', '{"fullBody"}', '{"shoulders","quads"}', 'barbell', NULL, NULL, '{"seed-power-clean","seed-snatch","seed-thruster","seed-kettlebell-swing","seed-deadlift"}'),
  ('seed-snatch', '스내치', 'Snatch', '{"fullBody"}', '{"shoulders","back"}', 'barbell', NULL, NULL, '{"seed-power-clean","seed-clean-and-jerk","seed-thruster","seed-kettlebell-swing","seed-deadlift"}'),
  ('seed-thruster', '쓰러스터', 'Thruster', '{"fullBody"}', '{"quads","shoulders"}', 'barbell', NULL, NULL, '{"seed-power-clean","seed-clean-and-jerk","seed-overhead-press","seed-goblet-squat","seed-burpee"}'),
  ('seed-burpee', '버피', 'Burpee', '{"fullBody"}', '{}', 'bodyweight', NULL, NULL, '{"seed-mountain-climber","seed-thruster","seed-battle-rope","seed-kettlebell-swing","seed-rowing-machine"}'),
  ('seed-battle-rope', '배틀 로프', 'Battle Rope', '{"fullBody"}', '{"shoulders"}', 'other', NULL, NULL, '{"seed-kettlebell-swing","seed-rowing-machine","seed-burpee","seed-mountain-climber"}'),
  ('seed-rowing-machine', '로잉 머신', 'Rowing Machine', '{"fullBody"}', '{"back"}', 'machine', NULL, NULL, '{"seed-battle-rope","seed-burpee","seed-kettlebell-swing","seed-seated-cable-row","seed-mountain-climber"}'),
  ('seed-assisted-pull-up', '어시스트 풀업', 'Assisted Pull Up', '{"back"}', '{"biceps"}', 'machine', NULL, 'assisted', '{}'),
  ('seed-assisted-chin-up', '어시스트 친업', 'Assisted Chin Up', '{"biceps"}', '{"back"}', 'machine', NULL, 'assisted', '{}'),
  ('seed-assisted-dip', '어시스트 딥스', 'Assisted Dip', '{"triceps"}', '{"chest"}', 'machine', NULL, 'assisted', '{}'),
  ('seed-high-row', '하이 로우', 'High Row', '{"back"}', '{"biceps"}', 'machine', NULL, NULL, '{}'),
  ('seed-low-row', '로우 로우', 'Low Row', '{"back"}', '{"biceps"}', 'machine', NULL, NULL, '{}'),
  ('seed-chest-supported-row', '체스트 서포티드 로우', 'Chest Supported Row', '{"back"}', '{"biceps"}', 'machine', NULL, NULL, '{}'),
  ('seed-inverted-row', '인버티드 로우', 'Inverted Row', '{"back"}', '{"biceps"}', 'bodyweight', NULL, NULL, '{}'),
  ('seed-single-arm-lat-pulldown', '원암 랫풀다운', 'Single-arm Lat Pulldown', '{"back"}', '{"biceps"}', 'cable', NULL, NULL, '{}'),
  ('seed-dumbbell-pullover', '덤벨 풀오버', 'Dumbbell Pullover', '{"back"}', '{"chest"}', 'dumbbell', NULL, NULL, '{}'),
  ('seed-landmine-press', '랜드마인 프레스', 'Landmine Press', '{"shoulders"}', '{"chest","triceps"}', 'barbell', NULL, NULL, '{}'),
  ('seed-cable-rear-delt-fly', '케이블 리어 델트 플라이', 'Cable Rear Delt Fly', '{"shoulders"}', '{}', 'cable', NULL, NULL, '{}'),
  ('seed-sissy-squat', '시시 스쿼트', 'Sissy Squat', '{"quads"}', '{}', 'bodyweight', NULL, NULL, '{}'),
  ('seed-pendulum-squat', '펜듈럼 스쿼트', 'Pendulum Squat', '{"quads"}', '{"glutes"}', 'machine', NULL, NULL, '{}'),
  ('seed-belt-squat', '벨트 스쿼트', 'Belt Squat', '{"quads"}', '{"glutes"}', 'machine', NULL, NULL, '{}'),
  ('seed-hip-adduction-machine', '힙 어덕션 머신', 'Hip Adduction Machine', '{"glutes"}', '{}', 'machine', NULL, NULL, '{}'),
  ('seed-smith-hip-thrust', '스미스 힙 쓰러스트', 'Smith Hip Thrust', '{"glutes"}', '{"hamstrings"}', 'smith', NULL, NULL, '{}'),
  ('seed-jm-press', 'JM 프레스', 'JM Press', '{"triceps"}', '{}', 'barbell', NULL, NULL, '{}'),
  ('seed-dip-machine', '딥 머신', 'Dip Machine', '{"triceps"}', '{"chest"}', 'machine', NULL, NULL, '{}'),
  ('seed-cable-hammer-curl', '케이블 해머 컬', 'Cable Hammer Curl', '{"biceps"}', '{"forearms"}', 'cable', NULL, NULL, '{}'),
  ('seed-lying-leg-raise', '라잉 레그 레이즈', 'Lying Leg Raise', '{"abs"}', '{}', 'bodyweight', NULL, NULL, '{}'),
  ('seed-cable-woodchopper', '케이블 우드촙', 'Cable Woodchopper', '{"abs"}', '{}', 'cable', NULL, NULL, '{}'),
  ('seed-ab-crunch-machine', '앱 크런치 머신', 'Ab Crunch Machine', '{"abs"}', '{}', 'machine', NULL, NULL, '{}'),
  ('seed-cable-shrug', '케이블 슈러그', 'Cable Shrug', '{"traps"}', '{}', 'cable', NULL, NULL, '{}'),
  ('seed-treadmill-running', '러닝머신', 'Treadmill Running', '{"fullBody"}', '{"quads","calves"}', 'machine', 'cardio', NULL, '{}'),
  ('seed-running', '러닝', 'Running', '{"fullBody"}', '{"quads","calves"}', 'bodyweight', 'cardio', NULL, '{}'),
  ('seed-walking', '걷기', 'Walking', '{"fullBody"}', '{"calves"}', 'bodyweight', 'cardio', NULL, '{}'),
  ('seed-indoor-cycling', '실내 사이클', 'Indoor Cycling', '{"quads"}', '{"calves"}', 'machine', 'cardio', NULL, '{}'),
  ('seed-elliptical', '일립티컬', 'Elliptical', '{"fullBody"}', '{"quads"}', 'machine', 'cardio', NULL, '{}'),
  ('seed-stair-climber', '천국의 계단', 'Stair Climber', '{"quads"}', '{"glutes","calves"}', 'machine', 'cardio', NULL, '{}'),
  ('seed-jump-rope', '줄넘기', 'Jump Rope', '{"calves"}', '{"fullBody"}', 'other', 'cardio', NULL, '{}'),
  ('seed-assault-bike', '어썰트 바이크', 'Assault Bike', '{"fullBody"}', '{"quads"}', 'machine', 'cardio', NULL, '{}'),
  ('seed-stepper', '스텝퍼', 'Stepper', '{"quads"}', '{"glutes","calves"}', 'machine', 'cardio', NULL, '{}'),
  ('seed-skierg', '스키에르그', 'SkiErg', '{"back"}', '{"triceps","fullBody"}', 'machine', 'cardio', NULL, '{}'),
  ('seed-row-smith', '로우 (스미스)', 'Row (Smith)', '{"back"}', '{"biceps"}', 'smith', NULL, NULL, '{}'),
  ('seed-shoulder-press-smith', '숄더 프레스 (스미스)', 'Shoulder Press (Smith)', '{"shoulders"}', '{"triceps"}', 'smith', NULL, NULL, '{}'),
  ('seed-front-raise-cable', '프론트 레이즈 (케이블)', 'Front Raise (Cable)', '{"shoulders"}', '{}', 'cable', NULL, NULL, '{}'),
  ('seed-front-raise-barbell', '프론트 레이즈 (바벨)', 'Front Raise (Barbell)', '{"shoulders"}', '{}', 'barbell', NULL, NULL, '{}'),
  ('seed-upright-row-cable', '업라이트 로우 (케이블)', 'Upright Row (Cable)', '{"shoulders"}', '{"traps"}', 'cable', NULL, NULL, '{}'),
  ('seed-upright-row-dumbbell', '업라이트 로우 (덤벨)', 'Upright Row (Dumbbell)', '{"shoulders"}', '{"traps"}', 'dumbbell', NULL, NULL, '{}'),
  ('seed-preacher-curl-dumbbell', '프리처 컬 (덤벨)', 'Preacher Curl (Dumbbell)', '{"biceps"}', '{}', 'dumbbell', NULL, NULL, '{}'),
  ('seed-skull-crusher-dumbbell', '스컬 크러셔 (덤벨)', 'Skull Crusher (Dumbbell)', '{"triceps"}', '{}', 'dumbbell', NULL, NULL, '{}'),
  ('seed-triceps-kickback-cable', '트라이셉스 킥백 (케이블)', 'Triceps Kickback (Cable)', '{"triceps"}', '{}', 'cable', NULL, NULL, '{}'),
  ('seed-wrist-curl-dumbbell', '리스트 컬 (덤벨)', 'Wrist Curl (Dumbbell)', '{"forearms"}', '{}', 'dumbbell', NULL, NULL, '{}'),
  ('seed-lunge-barbell', '런지 (바벨)', 'Lunge (Barbell)', '{"quads"}', '{"glutes"}', 'barbell', NULL, NULL, '{}'),
  ('seed-lunge-smith', '런지 (스미스)', 'Lunge (Smith)', '{"quads"}', '{"glutes"}', 'smith', NULL, NULL, '{}'),
  ('seed-bulgarian-split-squat-barbell', '불가리안 스플릿 스쿼트 (바벨)', 'Bulgarian Split Squat (Barbell)', '{"quads"}', '{"glutes"}', 'barbell', NULL, NULL, '{}'),
  ('seed-bulgarian-split-squat-smith', '불가리안 스플릿 스쿼트 (스미스)', 'Bulgarian Split Squat (Smith)', '{"quads"}', '{"glutes"}', 'smith', NULL, NULL, '{}'),
  ('seed-romanian-deadlift-dumbbell', '루마니안 데드리프트 (덤벨)', 'Romanian Deadlift (Dumbbell)', '{"hamstrings"}', '{"glutes","back"}', 'dumbbell', NULL, NULL, '{}'),
  ('seed-hip-thrust-machine', '힙 쓰러스트 (머신)', 'Hip Thrust (Machine)', '{"glutes"}', '{"hamstrings"}', 'machine', NULL, NULL, '{}'),
  ('seed-shrug-smith', '슈러그 (스미스)', 'Shrug (Smith)', '{"traps"}', '{}', 'smith', NULL, NULL, '{}'),
  ('seed-hammer-strength-chest-press', '해머스트렝스 체스트 프레스', 'Hammer Strength Chest Press', '{"chest"}', '{"triceps"}', 'machine', NULL, NULL, '{}'),
  ('seed-decline-chest-press-machine', '디클라인 체스트 프레스 머신', 'Decline Chest Press Machine', '{"chest"}', '{"triceps"}', 'machine', NULL, NULL, '{}'),
  ('seed-lying-chest-press-machine', '라잉 체스트 프레스 머신', 'Lying Chest Press Machine', '{"chest"}', '{"triceps"}', 'machine', NULL, NULL, '{}'),
  ('seed-converging-chest-press-machine', '컨버징 체스트 프레스 머신', 'Converging Chest Press Machine', '{"chest"}', '{"triceps"}', 'machine', NULL, NULL, '{}'),
  ('seed-single-arm-chest-press-machine', '원암 체스트 프레스 머신', 'Single-arm Chest Press Machine', '{"chest"}', '{"triceps"}', 'machine', NULL, NULL, '{}'),
  ('seed-seated-cable-chest-press', '시티드 케이블 체스트 프레스', 'Seated Cable Chest Press', '{"chest"}', '{"triceps"}', 'cable', NULL, NULL, '{}'),
  ('seed-standing-cable-chest-press', '스탠딩 케이블 체스트 프레스', 'Standing Cable Chest Press', '{"chest"}', '{"triceps"}', 'cable', NULL, NULL, '{}'),
  ('seed-lying-cable-chest-press', '라잉 케이블 체스트 프레스', 'Lying Cable Chest Press', '{"chest"}', '{"triceps"}', 'cable', NULL, NULL, '{}'),
  ('seed-larsen-press', '라슨 프레스', 'Larsen Press', '{"chest"}', '{"triceps"}', 'barbell', NULL, NULL, '{}'),
  ('seed-feet-up-bench-press', '피트 업 벤치프레스', 'Feet-up Bench Press', '{"chest"}', '{"triceps"}', 'barbell', NULL, NULL, '{}'),
  ('seed-decline-press-smith', '디클라인 프레스 (스미스)', 'Decline Press (Smith)', '{"chest"}', '{"triceps"}', 'smith', NULL, NULL, '{}'),
  ('seed-wide-grip-push-up', '와이드 그립 푸시업', 'Wide Grip Push Up', '{"chest"}', '{"shoulders"}', 'bodyweight', NULL, NULL, '{}'),
  ('seed-deficit-push-up', '데피싯 푸시업', 'Deficit Push Up', '{"chest"}', '{"triceps"}', 'bodyweight', NULL, NULL, '{}'),
  ('seed-chest-supported-t-bar-row', '체스트 서포티드 티바 로우', 'Chest Supported T-Bar Row', '{"back"}', '{"biceps"}', 'barbell', NULL, NULL, '{}'),
  ('seed-chest-supported-row-dumbbell', '체스트 서포티드 로우 (덤벨)', 'Chest Supported Row (Dumbbell)', '{"back"}', '{"biceps"}', 'dumbbell', NULL, NULL, '{}'),
  ('seed-sit-up', '싯업', 'Sit Up', '{"abs"}', '{}', 'bodyweight', NULL, NULL, '{}'),
  ('seed-decline-push-up', '디클라인 푸시업', 'Decline Push Up', '{"chest"}', '{"shoulders","triceps"}', 'bodyweight', NULL, NULL, '{"seed-push-up","seed-pike-push-up","seed-deficit-push-up","seed-incline-press-dumbbell","seed-incline-press"}'),
  ('seed-clap-push-up', '클랩 푸시업', 'Clap Push Up', '{"chest"}', '{"triceps"}', 'bodyweight', NULL, NULL, '{"seed-push-up","seed-deficit-push-up","seed-wide-grip-push-up","seed-dumbbell-bench-press","seed-barbell-bench-press"}'),
  ('seed-kneeling-push-up', '닐링 푸시업', 'Kneeling Push Up', '{"chest"}', '{"triceps"}', 'bodyweight', NULL, NULL, '{"seed-incline-push-up","seed-push-up","seed-chest-press-machine","seed-dumbbell-bench-press"}'),
  ('seed-one-arm-push-up', '원암 푸시업', 'One Arm Push Up', '{"chest"}', '{"triceps","abs"}', 'bodyweight', NULL, NULL, '{"seed-deficit-push-up","seed-clap-push-up","seed-single-arm-chest-press-machine","seed-push-up","seed-dumbbell-bench-press"}'),
  ('seed-plank-push-up', '플랭크 푸시업', 'Plank Push Up', '{"chest"}', '{"abs"}', 'bodyweight', NULL, NULL, '{"seed-push-up","seed-plank","seed-shoulder-taps","seed-mountain-climber"}'),
  ('seed-ring-push-up', '링 푸시업', 'Ring Push Up', '{"chest"}', '{"triceps","abs"}', 'other', NULL, NULL, '{"seed-push-up","seed-deficit-push-up","seed-ring-dip","seed-dumbbell-bench-press"}'),
  ('seed-floor-press', '플로어 프레스', 'Floor Press', '{"chest"}', '{"triceps"}', 'barbell', NULL, NULL, '{"seed-barbell-bench-press","seed-dumbbell-bench-press","seed-close-grip-bench-press","seed-dumbbell-squeeze-press","seed-push-up"}'),
  ('seed-dumbbell-squeeze-press', '덤벨 스퀴즈 프레스', 'Dumbbell Squeeze Press', '{"chest"}', '{"triceps"}', 'dumbbell', NULL, NULL, '{"seed-svend-press","seed-dumbbell-bench-press","seed-close-grip-bench-press","seed-pec-deck-fly","seed-diamond-push-up"}'),
  ('seed-svend-press', '스벤드 프레스', 'Svend Press', '{"chest"}', '{}', 'other', NULL, NULL, '{"seed-dumbbell-squeeze-press","seed-pec-deck-fly","seed-cable-crossover","seed-diamond-push-up"}'),
  ('seed-decline-dumbbell-fly', '디클라인 덤벨 플라이', 'Decline Dumbbell Fly', '{"chest"}', '{}', 'dumbbell', NULL, NULL, '{"seed-cable-crossover","seed-dumbbell-fly","seed-pec-deck-fly","seed-decline-dumbbell-press","seed-dips"}'),
  ('seed-seated-cable-fly', '시티드 케이블 플라이', 'Seated Cable Fly', '{"chest"}', '{}', 'cable', NULL, NULL, '{"seed-pec-deck-fly","seed-cable-crossover","seed-dumbbell-fly","seed-low-cable-fly"}'),
  ('seed-dumbbell-around-the-world', '덤벨 어라운드 더 월드', 'Dumbbell Around the World', '{"chest"}', '{"shoulders"}', 'dumbbell', NULL, NULL, '{"seed-dumbbell-fly","seed-incline-dumbbell-fly","seed-cable-crossover","seed-pec-deck-fly"}'),
  ('seed-ring-dip', '링 딥스', 'Ring Dip', '{"chest"}', '{"triceps"}', 'other', NULL, NULL, '{"seed-dips","seed-assisted-dip","seed-dip-machine","seed-ring-push-up","seed-close-grip-bench-press"}'),
  ('seed-landmine-row', '랜드마인 로우', 'Landmine Row', '{"back"}', '{"biceps"}', 'barbell', NULL, NULL, '{"seed-t-bar-row","seed-barbell-row","seed-meadows-row","seed-dumbbell-row","seed-machine-row"}'),
  ('seed-meadows-row', '메도우스 로우', 'Meadows Row', '{"back"}', '{"biceps"}', 'barbell', NULL, NULL, '{"seed-dumbbell-row","seed-landmine-row","seed-t-bar-row","seed-barbell-row","seed-machine-row"}'),
  ('seed-seal-row', '씰 로우', 'Seal Row', '{"back"}', '{"biceps"}', 'barbell', NULL, NULL, '{"seed-chest-supported-row","seed-chest-supported-row-dumbbell","seed-chest-supported-t-bar-row","seed-machine-row","seed-barbell-row"}'),
  ('seed-gorilla-row', '고릴라 로우', 'Gorilla Row', '{"back"}', '{"biceps"}', 'kettlebell', NULL, NULL, '{"seed-dumbbell-row","seed-renegade-row","seed-barbell-row","seed-pendlay-row"}'),
  ('seed-renegade-row', '레니게이드 로우', 'Renegade Row', '{"back"}', '{"abs","biceps"}', 'dumbbell', NULL, NULL, '{"seed-dumbbell-row","seed-gorilla-row","seed-inverted-row","seed-shoulder-taps"}'),
  ('seed-machine-pullover', '풀오버 머신', 'Machine Pullover', '{"back"}', '{"chest"}', 'machine', NULL, NULL, '{"seed-dumbbell-pullover","seed-straight-arm-pulldown","seed-lat-pulldown","seed-close-grip-pulldown"}'),
  ('seed-negative-pull-up', '네거티브 풀업', 'Negative Pull Up', '{"back"}', '{"biceps"}', 'bodyweight', NULL, NULL, '{"seed-assisted-pull-up","seed-lat-pulldown","seed-inverted-row","seed-scapular-pull-up","seed-dead-hang"}'),
  ('seed-scapular-pull-up', '스캐퓰러 풀업', 'Scapular Pull Up', '{"back"}', '{"traps"}', 'bodyweight', NULL, NULL, '{"seed-dead-hang","seed-negative-pull-up","seed-straight-arm-pulldown","seed-assisted-pull-up"}'),
  ('seed-kipping-pull-up', '키핑 풀업', 'Kipping Pull Up', '{"back"}', '{"biceps","fullBody"}', 'bodyweight', NULL, NULL, '{"seed-pull-up","seed-assisted-pull-up","seed-negative-pull-up","seed-lat-pulldown"}'),
  ('seed-sternum-pull-up', '스터넘 풀업', 'Sternum Pull Up', '{"back"}', '{"biceps"}', 'bodyweight', NULL, NULL, '{"seed-pull-up","seed-chin-up","seed-inverted-row","seed-lat-pulldown"}'),
  ('seed-muscle-up', '머슬업', 'Muscle Up', '{"back"}', '{"fullBody"}', 'bodyweight', NULL, NULL, '{"seed-pull-up","seed-dips","seed-kipping-pull-up","seed-ring-pull-up","seed-negative-pull-up"}'),
  ('seed-ring-pull-up', '링 풀업', 'Ring Pull Up', '{"back"}', '{"biceps"}', 'other', NULL, NULL, '{"seed-pull-up","seed-chin-up","seed-assisted-pull-up","seed-lat-pulldown"}'),
  ('seed-dead-hang', '데드 행', 'Dead Hang', '{"back"}', '{"forearms"}', 'bodyweight', NULL, NULL, '{"seed-scapular-pull-up","seed-farmer-s-walk","seed-negative-pull-up","seed-wrist-roller"}'),
  ('seed-back-extension-machine', '백 익스텐션 머신', 'Back Extension Machine', '{"back"}', '{"glutes"}', 'machine', NULL, NULL, '{"seed-hyperextension","seed-good-morning","seed-romanian-deadlift","seed-superman","seed-reverse-hyperextension"}'),
  ('seed-superman', '슈퍼맨', 'Superman', '{"back"}', '{"glutes"}', 'bodyweight', NULL, NULL, '{"seed-hyperextension","seed-back-extension-machine","seed-bird-dog","seed-reverse-hyperextension","seed-good-morning"}'),
  ('seed-pike-push-up', '파이크 푸시업', 'Pike Push Up', '{"shoulders"}', '{"triceps"}', 'bodyweight', NULL, NULL, '{"seed-handstand-push-up","seed-dumbbell-shoulder-press","seed-overhead-press","seed-shoulder-press-machine","seed-arnold-press"}'),
  ('seed-handstand-push-up', '핸드스탠드 푸시업', 'Handstand Push Up', '{"shoulders"}', '{"triceps"}', 'bodyweight', NULL, NULL, '{"seed-pike-push-up","seed-overhead-press","seed-dumbbell-shoulder-press","seed-shoulder-press-machine","seed-push-press"}'),
  ('seed-handstand-hold', '핸드스탠드 홀드', 'Handstand Hold', '{"shoulders"}', '{"abs"}', 'bodyweight', NULL, NULL, '{"seed-pike-push-up","seed-handstand-push-up","seed-overhead-press","seed-dumbbell-shoulder-press","seed-shoulder-taps"}'),
  ('seed-push-press', '푸시 프레스', 'Push Press', '{"shoulders"}', '{"triceps","quads"}', 'barbell', NULL, NULL, '{"seed-overhead-press","seed-military-press","seed-dumbbell-shoulder-press","seed-thruster","seed-shoulder-press-machine"}'),
  ('seed-band-pull-apart', '밴드 풀 어파트', 'Band Pull Apart', '{"shoulders"}', '{"traps"}', 'band', NULL, NULL, '{"seed-face-pull","seed-reverse-pec-deck","seed-rear-delt-fly","seed-cable-rear-delt-fly"}'),
  ('seed-cable-y-raise', '케이블 Y 레이즈', 'Cable Y Raise', '{"shoulders"}', '{}', 'cable', NULL, NULL, '{"seed-chest-supported-y-raise","seed-cable-lateral-raise","seed-side-lateral-raise","seed-front-raise","seed-machine-lateral-raise"}'),
  ('seed-chest-supported-y-raise', '체스트 서포티드 Y 레이즈', 'Chest Supported Y Raise', '{"shoulders"}', '{}', 'dumbbell', NULL, NULL, '{"seed-cable-y-raise","seed-side-lateral-raise","seed-cable-lateral-raise","seed-rear-delt-fly","seed-machine-lateral-raise"}'),
  ('seed-plate-front-raise', '프론트 레이즈 (플레이트)', 'Plate Front Raise', '{"shoulders"}', '{}', 'other', NULL, NULL, '{"seed-front-raise","seed-front-raise-cable","seed-front-raise-barbell","seed-overhead-plate-raise","seed-dumbbell-shoulder-press"}'),
  ('seed-overhead-plate-raise', '오버헤드 플레이트 레이즈', 'Overhead Plate Raise', '{"shoulders"}', '{}', 'other', NULL, NULL, '{"seed-plate-front-raise","seed-front-raise","seed-front-raise-cable","seed-dumbbell-shoulder-press","seed-kettlebell-halo"}'),
  ('seed-shoulder-taps', '숄더 탭', 'Shoulder Taps', '{"abs"}', '{"shoulders"}', 'bodyweight', NULL, NULL, '{"seed-plank","seed-spiderman-plank","seed-mountain-climber","seed-dead-bug","seed-pallof-press"}'),
  ('seed-kettlebell-halo', '케틀벨 헤일로', 'Kettlebell Halo', '{"shoulders"}', '{"abs"}', 'kettlebell', NULL, NULL, '{"seed-kettlebell-around-the-world","seed-overhead-plate-raise","seed-arnold-press","seed-turkish-get-up"}'),
  ('seed-drag-curl', '드래그 컬', 'Drag Curl', '{"biceps"}', '{}', 'barbell', NULL, NULL, '{"seed-barbell-curl","seed-ez-bar-curl","seed-cable-curl","seed-spider-curl","seed-dumbbell-curl"}'),
  ('seed-zottman-curl', '조트맨 컬', 'Zottman Curl', '{"biceps"}', '{"forearms"}', 'dumbbell', NULL, NULL, '{"seed-hammer-curl","seed-reverse-curl-dumbbell","seed-dumbbell-curl","seed-cross-body-hammer-curl","seed-reverse-barbell-curl"}'),
  ('seed-cross-body-hammer-curl', '크로스 바디 해머 컬', 'Cross Body Hammer Curl', '{"biceps"}', '{"forearms"}', 'dumbbell', NULL, NULL, '{"seed-hammer-curl","seed-cable-hammer-curl","seed-zottman-curl","seed-dumbbell-curl","seed-reverse-curl-dumbbell"}'),
  ('seed-waiter-curl', '웨이터 컬', 'Waiter Curl', '{"biceps"}', '{}', 'dumbbell', NULL, NULL, '{"seed-dumbbell-curl","seed-ez-bar-curl","seed-barbell-curl","seed-cable-curl","seed-plate-curl"}'),
  ('seed-bicep-curl-21s', '21 컬', 'Bicep Curl 21s', '{"biceps"}', '{}', 'barbell', NULL, NULL, '{"seed-barbell-curl","seed-ez-bar-curl","seed-dumbbell-curl","seed-cable-curl","seed-machine-curl"}'),
  ('seed-overhead-cable-curl', '오버헤드 케이블 컬', 'Overhead Cable Curl', '{"biceps"}', '{}', 'cable', NULL, NULL, '{"seed-cable-curl","seed-spider-curl","seed-preacher-curl","seed-concentration-curl","seed-incline-dumbbell-curl"}'),
  ('seed-behind-the-back-cable-curl', '비하인드 백 케이블 컬', 'Behind the Back Cable Curl', '{"biceps"}', '{}', 'cable', NULL, NULL, '{"seed-cable-curl","seed-incline-dumbbell-curl","seed-drag-curl","seed-dumbbell-curl","seed-barbell-curl"}'),
  ('seed-plate-curl', '플레이트 컬', 'Plate Curl', '{"biceps"}', '{"forearms"}', 'other', NULL, NULL, '{"seed-dumbbell-curl","seed-hammer-curl","seed-waiter-curl","seed-barbell-curl"}'),
  ('seed-reverse-grip-pushdown', '리버스 그립 푸시다운', 'Reverse Grip Pushdown', '{"triceps"}', '{}', 'cable', NULL, NULL, '{"seed-triceps-pushdown","seed-rope-pushdown","seed-triceps-kickback-cable","seed-triceps-extension-machine","seed-bench-dip"}'),
  ('seed-triceps-extension-machine', '트라이셉스 익스텐션 머신', 'Triceps Extension Machine', '{"triceps"}', '{}', 'machine', NULL, NULL, '{"seed-triceps-pushdown","seed-skull-crusher","seed-overhead-triceps-extension","seed-rope-pushdown","seed-dip-machine"}'),
  ('seed-wide-elbow-triceps-press', '와이드 엘보 트라이셉스 프레스', 'Wide-Elbow Triceps Press', '{"triceps"}', '{}', 'dumbbell', NULL, NULL, '{"seed-skull-crusher-dumbbell","seed-overhead-triceps-extension","seed-jm-press","seed-close-grip-bench-press","seed-triceps-pushdown"}'),
  ('seed-wrist-roller', '리스트 롤러', 'Wrist Roller', '{"forearms"}', '{}', 'other', NULL, NULL, '{"seed-wrist-curl","seed-reverse-wrist-curl","seed-farmer-s-walk","seed-behind-the-back-wrist-curl","seed-dead-hang"}'),
  ('seed-behind-the-back-wrist-curl', '비하인드 백 리스트 컬', 'Behind the Back Wrist Curl', '{"forearms"}', '{}', 'barbell', NULL, NULL, '{"seed-wrist-curl","seed-wrist-curl-dumbbell","seed-reverse-wrist-curl","seed-wrist-roller","seed-farmer-s-walk"}'),
  ('seed-reverse-curl-dumbbell', '리버스 컬 (덤벨)', 'Reverse Curl (Dumbbell)', '{"forearms"}', '{"biceps"}', 'dumbbell', NULL, NULL, '{"seed-reverse-barbell-curl","seed-reverse-curl-cable","seed-hammer-curl","seed-zottman-curl","seed-reverse-wrist-curl"}'),
  ('seed-reverse-curl-cable', '리버스 컬 (케이블)', 'Reverse Curl (Cable)', '{"forearms"}', '{"biceps"}', 'cable', NULL, NULL, '{"seed-reverse-barbell-curl","seed-reverse-curl-dumbbell","seed-cable-hammer-curl","seed-hammer-curl","seed-reverse-wrist-curl"}'),
  ('seed-shrug-machine', '슈러그 (머신)', 'Shrug (Machine)', '{"traps"}', '{}', 'machine', NULL, NULL, '{"seed-barbell-shrug","seed-dumbbell-shrug","seed-cable-shrug","seed-shrug-smith","seed-farmer-s-walk"}'),
  ('seed-jump-shrug', '점프 슈러그', 'Jump Shrug', '{"traps"}', '{"fullBody"}', 'barbell', NULL, NULL, '{"seed-barbell-shrug","seed-deadlift-high-pull","seed-hang-clean","seed-kettlebell-high-pull","seed-dumbbell-shrug"}'),
  ('seed-lying-neck-curl', '라잉 넥 컬', 'Lying Neck Curl', '{"other"}', '{}', 'bodyweight', NULL, NULL, '{"seed-face-pull","seed-barbell-shrug","seed-dumbbell-shrug"}'),
  ('seed-lying-neck-extension', '라잉 넥 익스텐션', 'Lying Neck Extension', '{"other"}', '{}', 'bodyweight', NULL, NULL, '{"seed-face-pull","seed-dumbbell-shrug","seed-barbell-shrug"}'),
  ('seed-box-squat', '박스 스쿼트', 'Box Squat', '{"quads"}', '{"glutes"}', 'barbell', NULL, NULL, '{"seed-barbell-squat","seed-pause-squat","seed-smith-machine-squat","seed-hack-squat","seed-leg-press"}'),
  ('seed-pause-squat', '포즈 스쿼트', 'Pause Squat', '{"quads"}', '{"glutes"}', 'barbell', NULL, NULL, '{"seed-barbell-squat","seed-box-squat","seed-high-bar-squat","seed-front-squat","seed-smith-machine-squat"}'),
  ('seed-overhead-squat', '오버헤드 스쿼트', 'Overhead Squat', '{"quads"}', '{"fullBody"}', 'barbell', NULL, NULL, '{"seed-front-squat","seed-high-bar-squat","seed-goblet-squat","seed-overhead-lunge"}'),
  ('seed-zercher-squat', '저처 스쿼트', 'Zercher Squat', '{"quads"}', '{"glutes","abs"}', 'barbell', NULL, NULL, '{"seed-front-squat","seed-goblet-squat","seed-barbell-squat","seed-hack-squat"}'),
  ('seed-sumo-squat', '스모 스쿼트', 'Sumo Squat', '{"quads"}', '{"glutes"}', 'dumbbell', NULL, NULL, '{"seed-goblet-squat","seed-sumo-deadlift","seed-barbell-squat","seed-leg-press","seed-hip-adduction-machine"}'),
  ('seed-pistol-squat', '피스톨 스쿼트', 'Pistol Squat', '{"quads"}', '{"glutes"}', 'bodyweight', NULL, NULL, '{"seed-bulgarian-split-squat","seed-split-squat","seed-step-up","seed-leg-press","seed-goblet-squat"}'),
  ('seed-wall-sit', '월 싯', 'Wall Sit', '{"quads"}', '{}', 'bodyweight', NULL, NULL, '{"seed-leg-extension","seed-sissy-squat","seed-goblet-squat","seed-leg-press"}'),
  ('seed-jump-squat', '점프 스쿼트', 'Jump Squat', '{"quads"}', '{"glutes"}', 'bodyweight', NULL, NULL, '{"seed-box-jump","seed-jump-lunge","seed-frog-jump","seed-barbell-squat"}'),
  ('seed-box-jump', '박스 점프', 'Box Jump', '{"quads"}', '{"glutes"}', 'bodyweight', NULL, NULL, '{"seed-jump-squat","seed-lateral-box-jump","seed-frog-jump","seed-step-up"}'),
  ('seed-lateral-box-jump', '레터럴 박스 점프', 'Lateral Box Jump', '{"quads"}', '{"glutes"}', 'bodyweight', NULL, NULL, '{"seed-box-jump","seed-jump-squat","seed-lateral-lunge","seed-lateral-squat","seed-frog-jump"}'),
  ('seed-frog-jump', '프로그 점프', 'Frog Jump', '{"quads"}', '{"glutes"}', 'bodyweight', NULL, NULL, '{"seed-jump-squat","seed-box-jump","seed-jump-lunge","seed-burpee"}'),
  ('seed-lateral-squat', '레터럴 스쿼트', 'Lateral Squat', '{"quads"}', '{"glutes"}', 'bodyweight', NULL, NULL, '{"seed-lateral-lunge","seed-curtsy-lunge","seed-sumo-squat","seed-goblet-squat"}'),
  ('seed-reverse-lunge', '리버스 런지', 'Reverse Lunge', '{"quads"}', '{"glutes"}', 'bodyweight', NULL, NULL, '{"seed-lunge","seed-walking-lunge","seed-split-squat","seed-bulgarian-split-squat","seed-step-up"}'),
  ('seed-lateral-lunge', '레터럴 런지', 'Lateral Lunge', '{"quads"}', '{"glutes"}', 'bodyweight', NULL, NULL, '{"seed-lateral-squat","seed-curtsy-lunge","seed-lunge","seed-hip-abduction-machine"}'),
  ('seed-curtsy-lunge', '커시 런지', 'Curtsy Lunge', '{"quads"}', '{"glutes"}', 'bodyweight', NULL, NULL, '{"seed-reverse-lunge","seed-lateral-lunge","seed-bulgarian-split-squat","seed-step-up"}'),
  ('seed-jump-lunge', '점프 런지', 'Jump Lunge', '{"quads"}', '{"glutes"}', 'bodyweight', NULL, NULL, '{"seed-jump-squat","seed-box-jump","seed-walking-lunge","seed-reverse-lunge"}'),
  ('seed-overhead-lunge', '오버헤드 런지', 'Overhead Lunge', '{"quads"}', '{"glutes","shoulders"}', 'dumbbell', NULL, NULL, '{"seed-lunge","seed-walking-lunge","seed-overhead-squat","seed-split-squat","seed-reverse-lunge"}'),
  ('seed-split-squat', '스플릿 스쿼트', 'Split Squat', '{"quads"}', '{"glutes"}', 'dumbbell', NULL, NULL, '{"seed-bulgarian-split-squat","seed-lunge","seed-reverse-lunge","seed-walking-lunge","seed-step-up"}'),
  ('seed-glute-ham-raise', '글루트 햄 레이즈', 'Glute Ham Raise', '{"hamstrings"}', '{"glutes"}', 'machine', NULL, NULL, '{"seed-nordic-curl","seed-lying-leg-curl","seed-romanian-deadlift","seed-stiff-leg-deadlift","seed-hyperextension"}'),
  ('seed-standing-leg-curl', '스탠딩 레그 컬', 'Standing Leg Curl', '{"hamstrings"}', '{}', 'machine', NULL, NULL, '{"seed-lying-leg-curl","seed-seated-leg-curl","seed-leg-curl","seed-nordic-curl","seed-romanian-deadlift"}'),
  ('seed-cable-pull-through', '케이블 풀 스루', 'Cable Pull Through', '{"glutes"}', '{"hamstrings"}', 'cable', NULL, NULL, '{"seed-romanian-deadlift","seed-kettlebell-swing","seed-hip-thrust","seed-good-morning","seed-glute-bridge"}'),
  ('seed-reverse-hyperextension', '리버스 하이퍼익스텐션', 'Reverse Hyperextension', '{"glutes"}', '{"hamstrings","back"}', 'machine', NULL, NULL, '{"seed-hyperextension","seed-back-extension-machine","seed-glute-bridge","seed-hip-thrust","seed-cable-pull-through"}'),
  ('seed-deadlift-high-pull', '데드리프트 하이 풀', 'Deadlift High Pull', '{"fullBody"}', '{"back","traps"}', 'barbell', NULL, NULL, '{"seed-kettlebell-high-pull","seed-clean-pull","seed-kettlebell-swing","seed-upright-row","seed-jump-shrug"}'),
  ('seed-hip-thrust-dumbbell', '힙 쓰러스트 (덤벨)', 'Hip Thrust (Dumbbell)', '{"glutes"}', '{"hamstrings"}', 'dumbbell', NULL, NULL, '{"seed-hip-thrust","seed-hip-thrust-machine","seed-smith-hip-thrust","seed-glute-bridge","seed-cable-pull-through"}'),
  ('seed-fire-hydrant', '파이어 하이드런트', 'Fire Hydrant', '{"glutes"}', '{}', 'bodyweight', NULL, NULL, '{"seed-clamshell","seed-cable-hip-abduction","seed-hip-abduction-machine","seed-lateral-band-walk","seed-lateral-leg-raise"}'),
  ('seed-clamshell', '클램셸', 'Clamshell', '{"glutes"}', '{}', 'bodyweight', NULL, NULL, '{"seed-fire-hydrant","seed-hip-abduction-machine","seed-cable-hip-abduction","seed-lateral-band-walk","seed-lateral-leg-raise"}'),
  ('seed-frog-pump', '프로그 펌프', 'Frog Pump', '{"glutes"}', '{"hamstrings"}', 'dumbbell', NULL, NULL, '{"seed-glute-bridge","seed-hip-thrust-dumbbell","seed-hip-thrust","seed-cable-pull-through"}'),
  ('seed-bird-dog', '버드 독', 'Bird Dog', '{"glutes"}', '{"abs","back"}', 'bodyweight', NULL, NULL, '{"seed-superman","seed-dead-bug","seed-glute-kickback","seed-plank"}'),
  ('seed-glute-kickback-machine', '글루트 킥백 머신', 'Glute Kickback Machine', '{"glutes"}', '{}', 'machine', NULL, NULL, '{"seed-cable-kickback","seed-glute-kickback","seed-hip-thrust","seed-glute-bridge","seed-cable-pull-through"}'),
  ('seed-glute-kickback', '글루트 킥백', 'Glute Kickback', '{"glutes"}', '{}', 'bodyweight', NULL, NULL, '{"seed-cable-kickback","seed-glute-kickback-machine","seed-fire-hydrant","seed-glute-bridge","seed-hip-thrust-dumbbell"}'),
  ('seed-cable-hip-abduction', '케이블 힙 어브덕션', 'Cable Hip Abduction', '{"glutes"}', '{}', 'cable', NULL, NULL, '{"seed-hip-abduction-machine","seed-lateral-band-walk","seed-clamshell","seed-lateral-leg-raise","seed-fire-hydrant"}'),
  ('seed-cable-hip-adduction', '케이블 힙 어덕션', 'Cable Hip Adduction', '{"glutes"}', '{}', 'cable', NULL, NULL, '{"seed-hip-adduction-machine","seed-sumo-squat","seed-sumo-deadlift","seed-lateral-lunge"}'),
  ('seed-lateral-leg-raise', '레터럴 레그 레이즈', 'Lateral Leg Raise', '{"glutes"}', '{}', 'bodyweight', NULL, NULL, '{"seed-clamshell","seed-fire-hydrant","seed-cable-hip-abduction","seed-hip-abduction-machine","seed-lateral-band-walk"}'),
  ('seed-lateral-band-walk', '레터럴 밴드 워크', 'Lateral Band Walk', '{"glutes"}', '{}', 'band', NULL, NULL, '{"seed-cable-hip-abduction","seed-hip-abduction-machine","seed-clamshell","seed-lateral-leg-raise","seed-fire-hydrant"}'),
  ('seed-dead-bug', '데드 버그', 'Dead Bug', '{"abs"}', '{}', 'bodyweight', NULL, NULL, '{"seed-bird-dog","seed-plank","seed-hollow-rock","seed-lying-knee-raise","seed-ab-wheel-rollout"}'),
  ('seed-v-sit-up', 'V 싯업', 'V Sit Up', '{"abs"}', '{}', 'bodyweight', NULL, NULL, '{"seed-sit-up","seed-toe-touch","seed-hanging-leg-raise","seed-decline-sit-up","seed-hollow-rock"}'),
  ('seed-hollow-rock', '할로우 락', 'Hollow Rock', '{"abs"}', '{}', 'bodyweight', NULL, NULL, '{"seed-dead-bug","seed-v-sit-up","seed-flutter-kick","seed-l-sit-hold","seed-ab-wheel-rollout"}'),
  ('seed-flutter-kick', '플러터 킥', 'Flutter Kick', '{"abs"}', '{}', 'bodyweight', NULL, NULL, '{"seed-scissor-kick","seed-lying-leg-raise","seed-lying-knee-raise","seed-hollow-rock","seed-reverse-crunch"}'),
  ('seed-scissor-kick', '시저 킥', 'Scissor Kick', '{"abs"}', '{}', 'bodyweight', NULL, NULL, '{"seed-flutter-kick","seed-lying-leg-raise","seed-reverse-crunch","seed-hollow-rock","seed-lying-knee-raise"}'),
  ('seed-toe-touch', '토 터치', 'Toe Touch', '{"abs"}', '{}', 'bodyweight', NULL, NULL, '{"seed-crunch","seed-v-sit-up","seed-sit-up","seed-cable-crunch","seed-reverse-crunch"}'),
  ('seed-heel-tap', '힐 터치', 'Heel Tap', '{"abs"}', '{}', 'bodyweight', NULL, NULL, '{"seed-side-crunch","seed-russian-twist","seed-bicycle-crunch","seed-side-bend","seed-side-plank"}'),
  ('seed-side-crunch', '사이드 크런치', 'Side Crunch', '{"abs"}', '{}', 'bodyweight', NULL, NULL, '{"seed-heel-tap","seed-bicycle-crunch","seed-russian-twist","seed-side-bend","seed-side-plank"}'),
  ('seed-side-bend', '사이드 벤드', 'Side Bend', '{"abs"}', '{}', 'dumbbell', NULL, NULL, '{"seed-side-crunch","seed-side-plank","seed-russian-twist","seed-cable-woodchopper","seed-heel-tap"}'),
  ('seed-decline-crunch', '디클라인 크런치', 'Decline Crunch', '{"abs"}', '{}', 'bodyweight', NULL, NULL, '{"seed-decline-sit-up","seed-crunch","seed-cable-crunch","seed-ab-crunch-machine","seed-reverse-crunch"}'),
  ('seed-lying-knee-raise', '라잉 니 레이즈', 'Lying Knee Raise', '{"abs"}', '{}', 'bodyweight', NULL, NULL, '{"seed-lying-leg-raise","seed-reverse-crunch","seed-hanging-knee-raise","seed-flutter-kick","seed-dead-bug"}'),
  ('seed-hanging-knee-raise', '행잉 니 레이즈', 'Hanging Knee Raise', '{"abs"}', '{}', 'bodyweight', NULL, NULL, '{"seed-hanging-leg-raise","seed-parallel-bar-knee-raise","seed-lying-knee-raise","seed-toes-to-bar","seed-reverse-crunch"}'),
  ('seed-parallel-bar-knee-raise', '패러럴 바 니 레이즈', 'Parallel Bar Knee Raise', '{"abs"}', '{}', 'other', NULL, NULL, '{"seed-hanging-knee-raise","seed-parallel-bar-leg-raise","seed-hanging-leg-raise","seed-lying-knee-raise","seed-reverse-crunch"}'),
  ('seed-parallel-bar-leg-raise', '패러럴 바 레그 레이즈', 'Parallel Bar Leg Raise', '{"abs"}', '{}', 'other', NULL, NULL, '{"seed-hanging-leg-raise","seed-parallel-bar-knee-raise","seed-lying-leg-raise","seed-toes-to-bar","seed-reverse-crunch"}'),
  ('seed-dragon-flag', '드래곤 플래그', 'Dragon Flag', '{"abs"}', '{"fullBody"}', 'bodyweight', NULL, NULL, '{"seed-hanging-leg-raise","seed-toes-to-bar","seed-ab-wheel-rollout","seed-hollow-rock","seed-lying-leg-raise"}'),
  ('seed-reverse-plank', '리버스 플랭크', 'Reverse Plank', '{"abs"}', '{"glutes","back"}', 'bodyweight', NULL, NULL, '{"seed-plank","seed-glute-bridge","seed-side-plank","seed-superman","seed-bird-dog"}'),
  ('seed-elbow-to-knee', '엘보 투 니', 'Elbow to Knee', '{"abs"}', '{}', 'bodyweight', NULL, NULL, '{"seed-bicycle-crunch","seed-side-crunch","seed-russian-twist","seed-mountain-climber","seed-crunch"}'),
  ('seed-spiderman-plank', '스파이더맨 플랭크', 'Spiderman Plank', '{"abs"}', '{}', 'bodyweight', NULL, NULL, '{"seed-plank","seed-mountain-climber","seed-shoulder-taps","seed-side-plank","seed-elbow-to-knee"}'),
  ('seed-pallof-press', '팔로프 프레스', 'Pallof Press', '{"abs"}', '{}', 'cable', NULL, NULL, '{"seed-cable-woodchopper","seed-russian-twist","seed-landmine-180","seed-torso-rotation-machine","seed-side-plank"}'),
  ('seed-landmine-180', '랜드마인 180', 'Landmine 180', '{"abs"}', '{"shoulders"}', 'barbell', NULL, NULL, '{"seed-cable-woodchopper","seed-pallof-press","seed-russian-twist","seed-torso-rotation-machine","seed-medicine-ball-slam"}'),
  ('seed-toes-to-bar', '토즈 투 바', 'Toes to Bar', '{"abs"}', '{"forearms"}', 'bodyweight', NULL, NULL, '{"seed-hanging-leg-raise","seed-hanging-knee-raise","seed-parallel-bar-leg-raise","seed-lying-leg-raise","seed-dragon-flag"}'),
  ('seed-l-sit-hold', 'L-싯 홀드', 'L-Sit Hold', '{"abs"}', '{"triceps"}', 'bodyweight', NULL, NULL, '{"seed-hollow-rock","seed-parallel-bar-leg-raise","seed-hanging-leg-raise","seed-v-sit-up","seed-plank"}'),
  ('seed-torso-rotation-machine', '토르소 로테이션 머신', 'Torso Rotation Machine', '{"abs"}', '{}', 'machine', NULL, NULL, '{"seed-cable-woodchopper","seed-russian-twist","seed-pallof-press","seed-landmine-180","seed-bicycle-crunch"}'),
  ('seed-hang-clean', '행 클린', 'Hang Clean', '{"fullBody"}', '{"back","quads"}', 'barbell', NULL, NULL, '{"seed-power-clean","seed-clean-pull","seed-clean-and-jerk","seed-kettlebell-swing","seed-jump-shrug"}'),
  ('seed-clean-and-press', '클린 앤 프레스', 'Clean and Press', '{"fullBody"}', '{"shoulders","quads"}', 'barbell', NULL, NULL, '{"seed-clean-and-jerk","seed-thruster","seed-push-press","seed-power-clean","seed-landmine-squat-to-press"}'),
  ('seed-clean-pull', '클린 풀', 'Clean Pull', '{"fullBody"}', '{"back","traps"}', 'barbell', NULL, NULL, '{"seed-deadlift-high-pull","seed-power-clean","seed-jump-shrug","seed-deadlift","seed-kettlebell-swing"}'),
  ('seed-power-snatch', '파워 스내치', 'Power Snatch', '{"fullBody"}', '{"shoulders","back"}', 'barbell', NULL, NULL, '{"seed-snatch","seed-hang-snatch","seed-power-clean","seed-kettlebell-swing","seed-deadlift-high-pull"}'),
  ('seed-hang-snatch', '행 스내치', 'Hang Snatch', '{"fullBody"}', '{"shoulders","back"}', 'barbell', NULL, NULL, '{"seed-power-snatch","seed-snatch","seed-hang-clean","seed-kettlebell-swing","seed-deadlift-high-pull"}'),
  ('seed-split-jerk', '스플릿 저크', 'Split Jerk', '{"fullBody"}', '{"shoulders","quads"}', 'barbell', NULL, NULL, '{"seed-push-press","seed-clean-and-jerk","seed-press-under","seed-thruster","seed-overhead-press"}'),
  ('seed-press-under', '프레스 언더', 'Press Under', '{"fullBody"}', '{"shoulders"}', 'barbell', NULL, NULL, '{"seed-split-jerk","seed-push-press","seed-overhead-squat","seed-overhead-press"}'),
  ('seed-landmine-squat-to-press', '랜드마인 스쿼트 앤 프레스', 'Landmine Squat to Press', '{"fullBody"}', '{"quads","shoulders"}', 'barbell', NULL, NULL, '{"seed-thruster","seed-landmine-press","seed-clean-and-press","seed-goblet-squat","seed-push-press"}'),
  ('seed-kettlebell-high-pull', '케틀벨 하이 풀', 'Kettlebell High Pull', '{"fullBody"}', '{"traps","shoulders"}', 'kettlebell', NULL, NULL, '{"seed-deadlift-high-pull","seed-kettlebell-swing","seed-upright-row-dumbbell","seed-clean-pull","seed-jump-shrug"}'),
  ('seed-turkish-get-up', '터키시 겟업', 'Turkish Get Up', '{"fullBody"}', '{"abs","shoulders"}', 'kettlebell', NULL, NULL, '{"seed-overhead-lunge","seed-kettlebell-halo","seed-overhead-squat","seed-suitcase-carry"}'),
  ('seed-kettlebell-around-the-world', '케틀벨 어라운드 더 월드', 'Kettlebell Around the World', '{"fullBody"}', '{"abs"}', 'kettlebell', NULL, NULL, '{"seed-kettlebell-halo","seed-dumbbell-around-the-world","seed-russian-twist","seed-pallof-press"}'),
  ('seed-sled-push', '슬레드 푸시', 'Sled Push', '{"fullBody"}', '{"quads"}', 'other', NULL, NULL, '{"seed-walking-lunge","seed-leg-press","seed-bear-crawl","seed-farmer-s-walk","seed-step-up"}'),
  ('seed-sled-pull', '슬레드 풀', 'Sled Pull', '{"fullBody"}', '{"back"}', 'other', NULL, NULL, '{"seed-farmer-s-walk","seed-seated-cable-row","seed-inverted-row","seed-kettlebell-swing"}'),
  ('seed-suitcase-carry', '수트케이스 캐리', 'Suitcase Carry', '{"fullBody"}', '{"forearms","abs"}', 'dumbbell', NULL, NULL, '{"seed-farmer-s-walk","seed-side-bend","seed-side-plank","seed-pallof-press"}'),
  ('seed-wall-ball', '월 볼', 'Wall Ball', '{"fullBody"}', '{"quads","shoulders"}', 'other', NULL, NULL, '{"seed-thruster","seed-medicine-ball-slam","seed-jump-squat","seed-goblet-squat","seed-push-press"}'),
  ('seed-medicine-ball-slam', '메디신 볼 슬램', 'Medicine Ball Slam', '{"fullBody"}', '{"abs"}', 'other', NULL, NULL, '{"seed-wall-ball","seed-kettlebell-swing","seed-battle-rope","seed-burpee","seed-cable-woodchopper"}'),
  ('seed-bear-crawl', '베어 크롤', 'Bear Crawl', '{"fullBody"}', '{"abs","shoulders"}', 'bodyweight', NULL, NULL, '{"seed-mountain-climber","seed-spiderman-plank","seed-plank","seed-sled-push","seed-burpee"}'),
  ('seed-front-lever-hold', '프론트 레버 홀드', 'Front Lever Hold', '{"back"}', '{"abs"}', 'bodyweight', NULL, NULL, '{"seed-front-lever-raise","seed-dragon-flag","seed-straight-arm-pulldown","seed-toes-to-bar","seed-hanging-leg-raise"}'),
  ('seed-burpee-broad-jump', '버피 브로드 점프', 'Burpee Broad Jump', '{"fullBody"}', '{}', 'bodyweight', NULL, NULL, '{"seed-burpee","seed-burpee-over-the-bar","seed-frog-jump","seed-box-jump","seed-jump-squat"}'),
  ('seed-burpee-over-the-bar', '버피 오버 더 바', 'Burpee Over the Bar', '{"fullBody"}', '{}', 'bodyweight', NULL, NULL, '{"seed-burpee","seed-burpee-broad-jump","seed-lateral-box-jump","seed-box-jump","seed-jump-squat"}'),
  ('seed-jumping-jack', '점핑 잭', 'Jumping Jack', '{"fullBody"}', '{"calves"}', 'bodyweight', NULL, NULL, '{"seed-high-knees","seed-mountain-climber","seed-jump-squat","seed-burpee","seed-battle-rope"}'),
  ('seed-high-knees', '하이 니', 'High Knees', '{"fullBody"}', '{"quads","calves"}', 'bodyweight', NULL, NULL, '{"seed-jumping-jack","seed-mountain-climber","seed-burpee","seed-jump-squat","seed-battle-rope"}'),
  ('seed-front-lever-raise', '프론트 레버 레이즈', 'Front Lever Raise', '{"back"}', '{"abs"}', 'bodyweight', NULL, NULL, '{"seed-front-lever-hold","seed-straight-arm-pulldown","seed-dragon-flag","seed-toes-to-bar","seed-hanging-leg-raise"}'),
  ('seed-swimming', '수영', 'Swimming', '{"fullBody"}', '{"back","shoulders"}', 'bodyweight', 'cardio', NULL, '{}'),
  ('seed-boxing', '복싱', 'Boxing', '{"fullBody"}', '{"shoulders","abs"}', 'bodyweight', 'cardio', NULL, '{}'),
  ('seed-climbing', '클라이밍', 'Climbing', '{"fullBody"}', '{"back","forearms"}', 'bodyweight', 'cardio', NULL, '{}'),
  ('seed-hiking', '하이킹', 'Hiking', '{"fullBody"}', '{"quads","calves"}', 'bodyweight', 'cardio', NULL, '{}'),
  ('seed-sprint', '스프린트', 'Sprint', '{"fullBody"}', '{"quads","hamstrings"}', 'bodyweight', 'cardio', NULL, '{}'),
  ('seed-outdoor-cycling', '야외 사이클', 'Outdoor Cycling', '{"quads"}', '{"calves"}', 'other', 'cardio', NULL, '{}'),
  ('seed-recumbent-bike', '리컴번트 바이크', 'Recumbent Bike', '{"quads"}', '{"calves"}', 'machine', 'cardio', NULL, '{}'),
  ('seed-hiit', '히트 (HIIT)', 'HIIT', '{"fullBody"}', '{}', 'bodyweight', 'cardio', NULL, '{}'),
  ('seed-aerobics', '에어로빅', 'Aerobics', '{"fullBody"}', '{}', 'bodyweight', 'cardio', NULL, '{}'),
  ('seed-yoga', '요가', 'Yoga', '{"fullBody"}', '{}', 'bodyweight', 'cardio', NULL, '{}'),
  ('seed-pilates', '필라테스', 'Pilates', '{"fullBody"}', '{"abs"}', 'bodyweight', 'cardio', NULL, '{}'),
  ('seed-skating', '스케이팅', 'Skating', '{"quads"}', '{"glutes"}', 'other', 'cardio', NULL, '{}'),
  ('seed-skiing', '스키', 'Skiing', '{"quads"}', '{"glutes"}', 'other', 'cardio', NULL, '{}'),
  ('seed-snowboarding', '스노우보드', 'Snowboarding', '{"quads"}', '{"glutes","abs"}', 'other', 'cardio', NULL, '{}'),
  ('seed-stretching', '스트레칭', 'Stretching', '{"fullBody"}', '{}', 'bodyweight', 'cardio', NULL, '{}')
ON CONFLICT (id) DO UPDATE SET
  name_ko = EXCLUDED.name_ko,
  name_en = EXCLUDED.name_en,
  primary_muscles = EXCLUDED.primary_muscles,
  secondary_muscles = EXCLUDED.secondary_muscles,
  equipment = EXCLUDED.equipment,
  kind = EXCLUDED.kind,
  load_mode = EXCLUDED.load_mode,
  substitute_ids = EXCLUDED.substitute_ids,
  updated_at = now()
WHERE (
  exercises.name_ko, exercises.name_en, exercises.primary_muscles, exercises.secondary_muscles,
  exercises.equipment, exercises.kind, exercises.load_mode, exercises.substitute_ids
) IS DISTINCT FROM (
  EXCLUDED.name_ko, EXCLUDED.name_en, EXCLUDED.primary_muscles, EXCLUDED.secondary_muscles,
  EXCLUDED.equipment, EXCLUDED.kind, EXCLUDED.load_mode, EXCLUDED.substitute_ids
);
