// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO refresh_tokens (token_hash, user_id, expires_at)
VALUES ($1, $2, $3)
`

type CreateRefreshTokenParams struct {
	TokenHash string
	UserID    string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, createRefreshToken, arg.TokenHash, arg.UserID, arg.ExpiresAt)
	return err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (id, email, display_name, password_hash, auth_provider, role)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, email, display_name, avatar_url, password_hash, auth_provider, role, experience_level, trainer_intent, created_at, updated_at
`

type CreateUserParams struct {
	ID           string
	Email        *string
	DisplayName  *string
	PasswordHash *string
	AuthProvider string
	Role         string
}

// @plm SRS-006  계정·인증 쿼리 — 여기 있는 것은 SQL뿐이다
//
// 규칙(비밀번호를 어떻게 검사하는가·토큰을 언제 폐기하는가)은 internal/auth/service.go가 안다.
// 이 파일은 "무엇을 읽고 쓰는가"만 적는다.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.DisplayName,
		arg.PasswordHash,
		arg.AuthProvider,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.PasswordHash,
		&i.AuthProvider,
		&i.Role,
		&i.ExperienceLevel,
		&i.TrainerIntent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpiredRefreshTokens = `-- name: DeleteExpiredRefreshTokens :exec
DELETE FROM refresh_tokens WHERE expires_at < now()
`

// 만료된 토큰 청소 — 쌓아 둘 이유가 없다.
func (q *Queries) DeleteExpiredRefreshTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredRefreshTokens)
	return err
}

const getLiveRefreshToken = `-- name: GetLiveRefreshToken :one
SELECT token_hash, user_id, expires_at, revoked_at, created_at FROM refresh_tokens
WHERE token_hash = $1 AND revoked_at IS NULL AND expires_at > now()
`

// 갱신이 쓴다. **살아 있는 것만** 돌려준다 — 폐기·만료 판단을 Go로 미루지 않는다.
func (q *Queries) GetLiveRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getLiveRefreshToken, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.TokenHash,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, display_name, avatar_url, password_hash, auth_provider, role, experience_level, trainer_intent, created_at, updated_at FROM users WHERE lower(email) = lower($1)
`

// 로그인이 쓴다. 이메일은 대소문자를 가리지 않는다 —
// 'A@b.com'으로 가입하고 'a@b.com'으로 로그인하는 것은 같은 사람이다.
func (q *Queries) GetUserByEmail(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.PasswordHash,
		&i.AuthProvider,
		&i.Role,
		&i.ExperienceLevel,
		&i.TrainerIntent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, display_name, avatar_url, password_hash, auth_provider, role, experience_level, trainer_intent, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.PasswordHash,
		&i.AuthProvider,
		&i.Role,
		&i.ExperienceLevel,
		&i.TrainerIntent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeAllRefreshTokensForUser = `-- name: RevokeAllRefreshTokensForUser :exec
UPDATE refresh_tokens SET revoked_at = now()
WHERE user_id = $1 AND revoked_at IS NULL
`

// 이 사용자의 모든 세션을 끊는다. 토큰 도난이 드러났을 때 쓸 자리다.
func (q *Queries) RevokeAllRefreshTokensForUser(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, revokeAllRefreshTokensForUser, userID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens SET revoked_at = now()
WHERE token_hash = $1 AND revoked_at IS NULL
`

// 회전·로그아웃. 이미 폐기된 것을 다시 폐기해도 문제 없다(멱등).
func (q *Queries) RevokeRefreshToken(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, tokenHash)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users SET
  display_name     = CASE WHEN $1::boolean     THEN $2::text     ELSE display_name END,
  avatar_url       = CASE WHEN $3::boolean       THEN $4::text       ELSE avatar_url END,
  experience_level = CASE WHEN $5::boolean THEN $6::text ELSE experience_level END,
  trainer_intent   = CASE WHEN $7::boolean   THEN $8::boolean ELSE trainer_intent END,
  updated_at       = now()
WHERE id = $9::text
RETURNING id, email, display_name, avatar_url, password_hash, auth_provider, role, experience_level, trainer_intent, created_at, updated_at
`

type UpdateUserProfileParams struct {
	SetDisplayName     bool
	DisplayName        string
	SetAvatarUrl       bool
	AvatarUrl          string
	SetExperienceLevel bool
	ExperienceLevel    string
	SetTrainerIntent   bool
	TrainerIntent      bool
	ID                 string
}

// 프로필 수정 — 보낸 것만 바꾼다.
// `set_*` 플래그가 false면 기존 값을 그대로 둔다(빈 문자열로 지우는 것과 구분하기 위해서다).
func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.SetDisplayName,
		arg.DisplayName,
		arg.SetAvatarUrl,
		arg.AvatarUrl,
		arg.SetExperienceLevel,
		arg.ExperienceLevel,
		arg.SetTrainerIntent,
		arg.TrainerIntent,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.PasswordHash,
		&i.AuthProvider,
		&i.Role,
		&i.ExperienceLevel,
		&i.TrainerIntent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
