// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: coaching.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptGrant = `-- name: AcceptGrant :one
UPDATE coaching_grants
SET status = 'active', consent_at = now(), updated_at = now()
WHERE id = $1
RETURNING id, trainer_id, member_id, status, scope, requested_by, consent_at, revoked_at, created_at, updated_at
`

func (q *Queries) AcceptGrant(ctx context.Context, id string) (CoachingGrant, error) {
	row := q.db.QueryRow(ctx, acceptGrant, id)
	var i CoachingGrant
	err := row.Scan(
		&i.ID,
		&i.TrainerID,
		&i.MemberID,
		&i.Status,
		&i.Scope,
		&i.RequestedBy,
		&i.ConsentAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAudit = `-- name: CreateAudit :exec
INSERT INTO coaching_audits (id, grant_id, actor_id, action, detail)
VALUES ($1, $2, $3, $4, $5)
`

type CreateAuditParams struct {
	ID      string
	GrantID string
	ActorID string
	Action  string
	Detail  []byte
}

func (q *Queries) CreateAudit(ctx context.Context, arg CreateAuditParams) error {
	_, err := q.db.Exec(ctx, createAudit,
		arg.ID,
		arg.GrantID,
		arg.ActorID,
		arg.Action,
		arg.Detail,
	)
	return err
}

const createGrant = `-- name: CreateGrant :one
INSERT INTO coaching_grants (id, trainer_id, member_id, status, requested_by)
VALUES ($1, $2, $3, 'pending', $4)
RETURNING id, trainer_id, member_id, status, scope, requested_by, consent_at, revoked_at, created_at, updated_at
`

type CreateGrantParams struct {
	ID          string
	TrainerID   string
	MemberID    string
	RequestedBy string
}

func (q *Queries) CreateGrant(ctx context.Context, arg CreateGrantParams) (CoachingGrant, error) {
	row := q.db.QueryRow(ctx, createGrant,
		arg.ID,
		arg.TrainerID,
		arg.MemberID,
		arg.RequestedBy,
	)
	var i CoachingGrant
	err := row.Scan(
		&i.ID,
		&i.TrainerID,
		&i.MemberID,
		&i.Status,
		&i.Scope,
		&i.RequestedBy,
		&i.ConsentAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGrantByID = `-- name: GetGrantByID :one
SELECT id, trainer_id, member_id, status, scope, requested_by, consent_at, revoked_at, created_at, updated_at FROM coaching_grants WHERE id = $1
`

func (q *Queries) GetGrantByID(ctx context.Context, id string) (CoachingGrant, error) {
	row := q.db.QueryRow(ctx, getGrantByID, id)
	var i CoachingGrant
	err := row.Scan(
		&i.ID,
		&i.TrainerID,
		&i.MemberID,
		&i.Status,
		&i.Scope,
		&i.RequestedBy,
		&i.ConsentAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGrantByPair = `-- name: GetGrantByPair :one
SELECT id, trainer_id, member_id, status, scope, requested_by, consent_at, revoked_at, created_at, updated_at FROM coaching_grants WHERE trainer_id = $1 AND member_id = $2
`

type GetGrantByPairParams struct {
	TrainerID string
	MemberID  string
}

func (q *Queries) GetGrantByPair(ctx context.Context, arg GetGrantByPairParams) (CoachingGrant, error) {
	row := q.db.QueryRow(ctx, getGrantByPair, arg.TrainerID, arg.MemberID)
	var i CoachingGrant
	err := row.Scan(
		&i.ID,
		&i.TrainerID,
		&i.MemberID,
		&i.Status,
		&i.Scope,
		&i.RequestedBy,
		&i.ConsentAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMemberRecord = `-- name: GetMemberRecord :one
SELECT id, payload FROM sync_records
WHERE user_id = $1 AND collection = $2 AND record_id = $3 AND deleted = false
`

type GetMemberRecordParams struct {
	UserID     string
	Collection string
	RecordID   string
}

type GetMemberRecordRow struct {
	ID      string
	Payload []byte
}

func (q *Queries) GetMemberRecord(ctx context.Context, arg GetMemberRecordParams) (GetMemberRecordRow, error) {
	row := q.db.QueryRow(ctx, getMemberRecord, arg.UserID, arg.Collection, arg.RecordID)
	var i GetMemberRecordRow
	err := row.Scan(&i.ID, &i.Payload)
	return i, err
}

const listAudit = `-- name: ListAudit :many
SELECT id, actor_id, action, created_at
FROM coaching_audits
WHERE grant_id = $1
ORDER BY created_at DESC
LIMIT 100
`

type ListAuditRow struct {
	ID        string
	ActorID   string
	Action    string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) ListAudit(ctx context.Context, grantID string) ([]ListAuditRow, error) {
	rows, err := q.db.Query(ctx, listAudit, grantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuditRow
	for rows.Next() {
		var i ListAuditRow
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.Action,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGrantsForUser = `-- name: ListGrantsForUser :many
SELECT
  g.id, g.trainer_id, g.member_id, g.status, g.scope, g.requested_by, g.consent_at, g.revoked_at, g.created_at, g.updated_at,
  t.display_name     AS trainer_name,
  t.avatar_url       AS trainer_avatar,
  t.experience_level AS trainer_level,
  t.trainer_intent   AS trainer_intent_flag,
  m.display_name     AS member_name,
  m.avatar_url       AS member_avatar,
  m.experience_level AS member_level,
  m.trainer_intent   AS member_intent_flag
FROM coaching_grants g
JOIN users t ON t.id = g.trainer_id
JOIN users m ON m.id = g.member_id
WHERE g.trainer_id = $1::text OR g.member_id = $1::text
ORDER BY g.updated_at DESC
`

type ListGrantsForUserRow struct {
	ID                string
	TrainerID         string
	MemberID          string
	Status            string
	Scope             []byte
	RequestedBy       string
	ConsentAt         pgtype.Timestamptz
	RevokedAt         pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	TrainerName       *string
	TrainerAvatar     *string
	TrainerLevel      *string
	TrainerIntentFlag bool
	MemberName        *string
	MemberAvatar      *string
	MemberLevel       *string
	MemberIntentFlag  bool
}

// 내가 낀 모든 관계. 최근 것부터 — 방금 요청한 것이 위에 있어야 한다.
func (q *Queries) ListGrantsForUser(ctx context.Context, viewerID string) ([]ListGrantsForUserRow, error) {
	rows, err := q.db.Query(ctx, listGrantsForUser, viewerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGrantsForUserRow
	for rows.Next() {
		var i ListGrantsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.TrainerID,
			&i.MemberID,
			&i.Status,
			&i.Scope,
			&i.RequestedBy,
			&i.ConsentAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TrainerName,
			&i.TrainerAvatar,
			&i.TrainerLevel,
			&i.TrainerIntentFlag,
			&i.MemberName,
			&i.MemberAvatar,
			&i.MemberLevel,
			&i.MemberIntentFlag,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemberRecords = `-- name: ListMemberRecords :many
SELECT collection, record_id, payload
FROM sync_records
WHERE user_id = $1::text
  AND deleted = false
  AND collection = ANY ($2::text[])
`

type ListMemberRecordsParams struct {
	MemberID    string
	Collections []string
}

type ListMemberRecordsRow struct {
	Collection string
	RecordID   string
	Payload    []byte
}

// 회원이 동기해 둔 레코드를 컬렉션별로 읽는다 — 리포트·루틴 열람이 여기서 나온다.
// **지워진 것은 빼고**(회원이 지운 기록을 트레이너가 계속 보면 안 된다).
func (q *Queries) ListMemberRecords(ctx context.Context, arg ListMemberRecordsParams) ([]ListMemberRecordsRow, error) {
	rows, err := q.db.Query(ctx, listMemberRecords, arg.MemberID, arg.Collections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMemberRecordsRow
	for rows.Next() {
		var i ListMemberRecordsRow
		if err := rows.Scan(&i.Collection, &i.RecordID, &i.Payload); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reopenGrant = `-- name: ReopenGrant :one
UPDATE coaching_grants
SET status = 'pending', requested_by = $2, consent_at = NULL, revoked_at = NULL, updated_at = now()
WHERE id = $1
RETURNING id, trainer_id, member_id, status, scope, requested_by, consent_at, revoked_at, created_at, updated_at
`

type ReopenGrantParams struct {
	ID          string
	RequestedBy string
}

// 해지된 관계에 다시 요청 — 새 행을 만들지 않고 **같은 행을** 되살린다(감사 기록이 이력을 보존한다).
func (q *Queries) ReopenGrant(ctx context.Context, arg ReopenGrantParams) (CoachingGrant, error) {
	row := q.db.QueryRow(ctx, reopenGrant, arg.ID, arg.RequestedBy)
	var i CoachingGrant
	err := row.Scan(
		&i.ID,
		&i.TrainerID,
		&i.MemberID,
		&i.Status,
		&i.Scope,
		&i.RequestedBy,
		&i.ConsentAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeGrant = `-- name: RevokeGrant :one
UPDATE coaching_grants
SET status = 'revoked', revoked_at = now(), updated_at = now()
WHERE id = $1
RETURNING id, trainer_id, member_id, status, scope, requested_by, consent_at, revoked_at, created_at, updated_at
`

func (q *Queries) RevokeGrant(ctx context.Context, id string) (CoachingGrant, error) {
	row := q.db.QueryRow(ctx, revokeGrant, id)
	var i CoachingGrant
	err := row.Scan(
		&i.ID,
		&i.TrainerID,
		&i.MemberID,
		&i.Status,
		&i.Scope,
		&i.RequestedBy,
		&i.ConsentAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const searchTrainers = `-- name: SearchTrainers :many

SELECT id, display_name, avatar_url, experience_level, trainer_intent
FROM users u
WHERE u.trainer_intent = true
  AND u.id <> $1::text
  AND NOT EXISTS (
    SELECT 1 FROM blocks b
    WHERE (b.blocker_id = $1::text AND b.blocked_id = u.id)
       OR (b.blocker_id = u.id AND b.blocked_id = $1::text)
  )
  AND ($2::text = '' OR u.display_name ILIKE '%' || $2::text || '%')
ORDER BY u.created_at
LIMIT 30
`

type SearchTrainersParams struct {
	ViewerID string
	Query    string
}

type SearchTrainersRow struct {
	ID              string
	DisplayName     *string
	AvatarUrl       *string
	ExperienceLevel *string
	TrainerIntent   bool
}

// @plm SRS-048  코칭
// 코칭 의향을 밝힌 사람 찾기. **차단한/차단당한 사람과 나 자신은 빼고**.
func (q *Queries) SearchTrainers(ctx context.Context, arg SearchTrainersParams) ([]SearchTrainersRow, error) {
	rows, err := q.db.Query(ctx, searchTrainers, arg.ViewerID, arg.Query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchTrainersRow
	for rows.Next() {
		var i SearchTrainersRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.ExperienceLevel,
			&i.TrainerIntent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMemberRecord = `-- name: UpdateMemberRecord :exec
UPDATE sync_records
SET payload = $2, updated_at = now()
WHERE id = $1
`

type UpdateMemberRecordParams struct {
	ID      string
	Payload []byte
}

// 처방을 회원의 레코드에 써 넣는다. `updated_at`이 움직여야 회원 기기가 다음 pull에서 받는다.
func (q *Queries) UpdateMemberRecord(ctx context.Context, arg UpdateMemberRecordParams) error {
	_, err := q.db.Exec(ctx, updateMemberRecord, arg.ID, arg.Payload)
	return err
}
