// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dm.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addParticipant = `-- name: AddParticipant :exec
INSERT INTO conversation_participants (conversation_id, user_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddParticipantParams struct {
	ConversationID string
	UserID         string
}

func (q *Queries) AddParticipant(ctx context.Context, arg AddParticipantParams) error {
	_, err := q.db.Exec(ctx, addParticipant, arg.ConversationID, arg.UserID)
	return err
}

const countFollowedAmong = `-- name: CountFollowedAmong :one
SELECT count(*)::int FROM follows
WHERE follower_id = $1::text AND followee_id = ANY ($2::text[])
`

type CountFollowedAmongParams struct {
	FollowerID string
	UserIds    []string
}

// 그룹에 넣을 수 있는지 — 내가 팔로우하는 사람만.
func (q *Queries) CountFollowedAmong(ctx context.Context, arg CountFollowedAmongParams) (int32, error) {
	row := q.db.QueryRow(ctx, countFollowedAmong, arg.FollowerID, arg.UserIds)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countParticipants = `-- name: CountParticipants :one
SELECT count(*)::int FROM conversation_participants WHERE conversation_id = $1
`

func (q *Queries) CountParticipants(ctx context.Context, conversationID string) (int32, error) {
	row := q.db.QueryRow(ctx, countParticipants, conversationID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countUnread = `-- name: CountUnread :one
SELECT count(*)::int
FROM messages m
JOIN conversation_participants p
  ON p.conversation_id = m.conversation_id AND p.user_id = $1::text
WHERE m.conversation_id = $2::text
  AND m.sender_id <> $1::text
  AND (p.last_read_at IS NULL OR m.created_at > p.last_read_at)
`

type CountUnreadParams struct {
	ViewerID       string
	ConversationID string
}

// 안 읽은 수 — 저장하지 않고 셀 때 센다(내 last_read_at 이후의 **남의** 메시지).
func (q *Queries) CountUnread(ctx context.Context, arg CountUnreadParams) (int32, error) {
	row := q.db.QueryRow(ctx, countUnread, arg.ViewerID, arg.ConversationID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countUsersAmong = `-- name: CountUsersAmong :one
SELECT count(*)::int FROM users WHERE id = ANY ($1::text[])
`

func (q *Queries) CountUsersAmong(ctx context.Context, userIds []string) (int32, error) {
	row := q.db.QueryRow(ctx, countUsersAmong, userIds)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (id, is_group, direct_key, title)
VALUES ($1, $2, $3, $4)
RETURNING id, is_group, direct_key, title, created_at, updated_at
`

type CreateConversationParams struct {
	ID        string
	IsGroup   bool
	DirectKey *string
	Title     *string
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, createConversation,
		arg.ID,
		arg.IsGroup,
		arg.DirectKey,
		arg.Title,
	)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.IsGroup,
		&i.DirectKey,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (id, conversation_id, sender_id, kind, body, media_url)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, conversation_id, sender_id, kind, body, media_url, created_at
`

type CreateMessageParams struct {
	ID             string
	ConversationID string
	SenderID       string
	Kind           string
	Body           *string
	MediaUrl       *string
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.ID,
		arg.ConversationID,
		arg.SenderID,
		arg.Kind,
		arg.Body,
		arg.MediaUrl,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderID,
		&i.Kind,
		&i.Body,
		&i.MediaUrl,
		&i.CreatedAt,
	)
	return i, err
}

const deleteConversation = `-- name: DeleteConversation :exec
DELETE FROM conversations WHERE id = $1
`

func (q *Queries) DeleteConversation(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteConversation, id)
	return err
}

const findDirectConversation = `-- name: FindDirectConversation :one

SELECT id, is_group, direct_key, title, created_at, updated_at FROM conversations WHERE direct_key = $1
`

// @plm SRS-017  DM 쿼리
//
// 참여자 확인은 **모든 접근의 첫 관문**이다(대화 열기·메시지 읽기·보내기·읽음 처리).
// 그래서 참여자 표의 기본 키가 (대화, 사람)이다 — 확인이 인덱스 한 번이면 끝난다.
// 1:1 대화는 정규화 키로 찾는다. 동시에 만들어도 유일 제약이 하나만 남긴다.
func (q *Queries) FindDirectConversation(ctx context.Context, directKey *string) (Conversation, error) {
	row := q.db.QueryRow(ctx, findDirectConversation, directKey)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.IsGroup,
		&i.DirectKey,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConversation = `-- name: GetConversation :one
SELECT id, is_group, direct_key, title, created_at, updated_at FROM conversations WHERE id = $1
`

func (q *Queries) GetConversation(ctx context.Context, id string) (Conversation, error) {
	row := q.db.QueryRow(ctx, getConversation, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.IsGroup,
		&i.DirectKey,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLastMessage = `-- name: GetLastMessage :one
SELECT m.id, m.conversation_id, m.sender_id, m.kind, m.body, m.media_url, m.created_at, u.display_name AS sender_name, u.avatar_url AS sender_avatar
FROM messages m
JOIN users u ON u.id = m.sender_id
WHERE m.conversation_id = $1
ORDER BY m.created_at DESC, m.id DESC
LIMIT 1
`

type GetLastMessageRow struct {
	ID             string
	ConversationID string
	SenderID       string
	Kind           string
	Body           *string
	MediaUrl       *string
	CreatedAt      pgtype.Timestamptz
	SenderName     *string
	SenderAvatar   *string
}

// 목록에 붙는 마지막 메시지.
func (q *Queries) GetLastMessage(ctx context.Context, conversationID string) (GetLastMessageRow, error) {
	row := q.db.QueryRow(ctx, getLastMessage, conversationID)
	var i GetLastMessageRow
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderID,
		&i.Kind,
		&i.Body,
		&i.MediaUrl,
		&i.CreatedAt,
		&i.SenderName,
		&i.SenderAvatar,
	)
	return i, err
}

const isParticipant = `-- name: IsParticipant :one
SELECT EXISTS (
  SELECT 1 FROM conversation_participants WHERE conversation_id = $1 AND user_id = $2
)::boolean
`

type IsParticipantParams struct {
	ConversationID string
	UserID         string
}

func (q *Queries) IsParticipant(ctx context.Context, arg IsParticipantParams) (bool, error) {
	row := q.db.QueryRow(ctx, isParticipant, arg.ConversationID, arg.UserID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const listMessages = `-- name: ListMessages :many
SELECT m.id, m.conversation_id, m.sender_id, m.kind, m.body, m.media_url, m.created_at, u.display_name AS sender_name, u.avatar_url AS sender_avatar
FROM messages m
JOIN users u ON u.id = m.sender_id
WHERE m.conversation_id = $1::text
  AND NOT EXISTS (
    SELECT 1 FROM blocks b
    WHERE (b.blocker_id = $2::text AND b.blocked_id = m.sender_id)
       OR (b.blocker_id = m.sender_id AND b.blocked_id = $2::text)
  )
  AND ($3::boolean = false OR m.created_at < $4::timestamptz)
ORDER BY m.created_at DESC, m.id DESC
LIMIT $5
`

type ListMessagesParams struct {
	ConversationID string
	ViewerID       string
	HasBefore      bool
	Before         pgtype.Timestamptz
	Lim            int32
}

type ListMessagesRow struct {
	ID             string
	ConversationID string
	SenderID       string
	Kind           string
	Body           *string
	MediaUrl       *string
	CreatedAt      pgtype.Timestamptz
	SenderName     *string
	SenderAvatar   *string
}

// 대화 내용. 차단 관계인 사람의 메시지는 빼고 본다(1:1이면 상대, 그룹이면 그 멤버).
func (q *Queries) ListMessages(ctx context.Context, arg ListMessagesParams) ([]ListMessagesRow, error) {
	rows, err := q.db.Query(ctx, listMessages,
		arg.ConversationID,
		arg.ViewerID,
		arg.HasBefore,
		arg.Before,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessagesRow
	for rows.Next() {
		var i ListMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SenderID,
			&i.Kind,
			&i.Body,
			&i.MediaUrl,
			&i.CreatedAt,
			&i.SenderName,
			&i.SenderAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesAfter = `-- name: ListMessagesAfter :many
SELECT m.id, m.conversation_id, m.sender_id, m.kind, m.body, m.media_url, m.created_at, u.display_name AS sender_name, u.avatar_url AS sender_avatar
FROM messages m
JOIN users u ON u.id = m.sender_id
WHERE m.conversation_id = $1::text
  AND NOT EXISTS (
    SELECT 1 FROM blocks b
    WHERE (b.blocker_id = $2::text AND b.blocked_id = m.sender_id)
       OR (b.blocker_id = m.sender_id AND b.blocked_id = $2::text)
  )
  AND m.created_at > $3::timestamptz
ORDER BY m.created_at ASC, m.id ASC
LIMIT $4
`

type ListMessagesAfterParams struct {
	ConversationID string
	ViewerID       string
	After          pgtype.Timestamptz
	Lim            int32
}

type ListMessagesAfterRow struct {
	ID             string
	ConversationID string
	SenderID       string
	Kind           string
	Body           *string
	MediaUrl       *string
	CreatedAt      pgtype.Timestamptz
	SenderName     *string
	SenderAvatar   *string
}

// 스트림이 쓰는 방향: 이 시각 **이후**의 새 메시지(오래된 것부터).
func (q *Queries) ListMessagesAfter(ctx context.Context, arg ListMessagesAfterParams) ([]ListMessagesAfterRow, error) {
	rows, err := q.db.Query(ctx, listMessagesAfter,
		arg.ConversationID,
		arg.ViewerID,
		arg.After,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessagesAfterRow
	for rows.Next() {
		var i ListMessagesAfterRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SenderID,
			&i.Kind,
			&i.Body,
			&i.MediaUrl,
			&i.CreatedAt,
			&i.SenderName,
			&i.SenderAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyConversations = `-- name: ListMyConversations :many
SELECT c.id, c.is_group, c.direct_key, c.title, c.created_at, c.updated_at
FROM conversations c
JOIN conversation_participants p ON p.conversation_id = c.id AND p.user_id = $1::text
ORDER BY c.updated_at DESC
LIMIT $2
`

type ListMyConversationsParams struct {
	ViewerID string
	Lim      int32
}

// 내가 낀 대화들. 최근 것이 앞.
func (q *Queries) ListMyConversations(ctx context.Context, arg ListMyConversationsParams) ([]Conversation, error) {
	rows, err := q.db.Query(ctx, listMyConversations, arg.ViewerID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Conversation
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.IsGroup,
			&i.DirectKey,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParticipants = `-- name: ListParticipants :many
SELECT p.conversation_id, u.id, u.display_name, u.avatar_url
FROM conversation_participants p
JOIN users u ON u.id = p.user_id
WHERE p.conversation_id = ANY ($1::text[])
`

type ListParticipantsRow struct {
	ConversationID string
	ID             string
	DisplayName    *string
	AvatarUrl      *string
}

// 한 대화의 참여자들(이름까지).
func (q *Queries) ListParticipants(ctx context.Context, conversationIds []string) ([]ListParticipantsRow, error) {
	rows, err := q.db.Query(ctx, listParticipants, conversationIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListParticipantsRow
	for rows.Next() {
		var i ListParticipantsRow
		if err := rows.Scan(
			&i.ConversationID,
			&i.ID,
			&i.DisplayName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRead = `-- name: MarkRead :exec
UPDATE conversation_participants SET last_read_at = now()
WHERE conversation_id = $1 AND user_id = $2
`

type MarkReadParams struct {
	ConversationID string
	UserID         string
}

func (q *Queries) MarkRead(ctx context.Context, arg MarkReadParams) error {
	_, err := q.db.Exec(ctx, markRead, arg.ConversationID, arg.UserID)
	return err
}

const removeParticipant = `-- name: RemoveParticipant :exec
DELETE FROM conversation_participants WHERE conversation_id = $1 AND user_id = $2
`

type RemoveParticipantParams struct {
	ConversationID string
	UserID         string
}

func (q *Queries) RemoveParticipant(ctx context.Context, arg RemoveParticipantParams) error {
	_, err := q.db.Exec(ctx, removeParticipant, arg.ConversationID, arg.UserID)
	return err
}

const touchConversation = `-- name: TouchConversation :exec
UPDATE conversations SET updated_at = now() WHERE id = $1
`

// 목록 정렬이 최신 대화 순이므로, 메시지를 넣으면 대화도 함께 올린다(같은 트랜잭션).
func (q *Queries) TouchConversation(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, touchConversation, id)
	return err
}
