// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feed.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addHashtag = `-- name: AddHashtag :exec
INSERT INTO post_hashtags (post_id, tag) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddHashtagParams struct {
	PostID string
	Tag    string
}

// ── 해시태그 ────────────────────────────────────────────────────────────────
func (q *Queries) AddHashtag(ctx context.Context, arg AddHashtagParams) error {
	_, err := q.db.Exec(ctx, addHashtag, arg.PostID, arg.Tag)
	return err
}

const blockUser = `-- name: BlockUser :exec
INSERT INTO blocks (blocker_id, blocked_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type BlockUserParams struct {
	BlockerID string
	BlockedID string
}

// ── 차단 ────────────────────────────────────────────────────────────────────
// 차단하면 팔로우 관계도 **양쪽 다** 끊는다 — 남겨 두면 차단이 풀리는 순간 다시 이어진다.
func (q *Queries) BlockUser(ctx context.Context, arg BlockUserParams) error {
	_, err := q.db.Exec(ctx, blockUser, arg.BlockerID, arg.BlockedID)
	return err
}

const bookmarkPost = `-- name: BookmarkPost :execrows
INSERT INTO post_bookmarks (post_id, user_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type BookmarkPostParams struct {
	PostID string
	UserID string
}

// ── 저장(북마크) ────────────────────────────────────────────────────────────
func (q *Queries) BookmarkPost(ctx context.Context, arg BookmarkPostParams) (int64, error) {
	result, err := q.db.Exec(ctx, bookmarkPost, arg.PostID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const bumpCommentCount = `-- name: BumpCommentCount :exec
UPDATE posts SET comment_count = GREATEST(0, comment_count + $1::int) WHERE id = $2::text
`

type BumpCommentCountParams struct {
	Delta  int32
	PostID string
}

func (q *Queries) BumpCommentCount(ctx context.Context, arg BumpCommentCountParams) error {
	_, err := q.db.Exec(ctx, bumpCommentCount, arg.Delta, arg.PostID)
	return err
}

const bumpCommentLikeCount = `-- name: BumpCommentLikeCount :one
UPDATE comments SET like_count = GREATEST(0, like_count + $1::int) WHERE id = $2::text
RETURNING like_count
`

type BumpCommentLikeCountParams struct {
	Delta     int32
	CommentID string
}

func (q *Queries) BumpCommentLikeCount(ctx context.Context, arg BumpCommentLikeCountParams) (int32, error) {
	row := q.db.QueryRow(ctx, bumpCommentLikeCount, arg.Delta, arg.CommentID)
	var like_count int32
	err := row.Scan(&like_count)
	return like_count, err
}

const bumpLikeCount = `-- name: BumpLikeCount :one
UPDATE posts SET like_count = GREATEST(0, like_count + $1::int) WHERE id = $2::text
RETURNING like_count
`

type BumpLikeCountParams struct {
	Delta  int32
	PostID string
}

// 실제로 넣거나 뺐을 때만 부른다(멱등 호출은 카운트를 건드리지 않는다).
func (q *Queries) BumpLikeCount(ctx context.Context, arg BumpLikeCountParams) (int32, error) {
	row := q.db.QueryRow(ctx, bumpLikeCount, arg.Delta, arg.PostID)
	var like_count int32
	err := row.Scan(&like_count)
	return like_count, err
}

const bumpReplyCount = `-- name: BumpReplyCount :exec
UPDATE comments SET reply_count = GREATEST(0, reply_count + $1::int) WHERE id = $2::text
`

type BumpReplyCountParams struct {
	Delta     int32
	CommentID string
}

// 답글 수는 루트 댓글이 들고 있다.
func (q *Queries) BumpReplyCount(ctx context.Context, arg BumpReplyCountParams) error {
	_, err := q.db.Exec(ctx, bumpReplyCount, arg.Delta, arg.CommentID)
	return err
}

const clearHashtags = `-- name: ClearHashtags :exec
DELETE FROM post_hashtags WHERE post_id = $1
`

// 캡션을 고치면 태그를 다시 뽑는다 — 지우고 새로 넣는 편이 차이를 계산하는 것보다 안전하다.
func (q *Queries) ClearHashtags(ctx context.Context, postID string) error {
	_, err := q.db.Exec(ctx, clearHashtags, postID)
	return err
}

const createComment = `-- name: CreateComment :one
INSERT INTO comments (id, post_id, author_id, body, parent_id) VALUES ($1, $2, $3, $4, $5)
RETURNING id, post_id, author_id, body, moderation_status, created_at, parent_id, like_count, reply_count, removed_at
`

type CreateCommentParams struct {
	ID       string
	PostID   string
	AuthorID string
	Body     string
	ParentID *string
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, createComment,
		arg.ID,
		arg.PostID,
		arg.AuthorID,
		arg.Body,
		arg.ParentID,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.AuthorID,
		&i.Body,
		&i.ModerationStatus,
		&i.CreatedAt,
		&i.ParentID,
		&i.LikeCount,
		&i.ReplyCount,
		&i.RemovedAt,
	)
	return i, err
}

const createPost = `-- name: CreatePost :one
INSERT INTO posts (
  id, author_id, kind, caption, visibility,
  workout_id, workout_name, total_volume_kg, working_sets, duration_seconds, pr_count,
  streak_days, weekly_reached, exercises, gear,
  media_urls, idempotency_key
) VALUES (
  $1, $2, $3, $4, $5,
  $6, $7, $8, $9, $10, $11,
  $12, $13, $14, $15,
  $16, $17
)
RETURNING id, author_id, kind, caption, visibility, moderation_status, workout_id, workout_name, total_volume_kg, working_sets, duration_seconds, pr_count, media_urls, idempotency_key, like_count, comment_count, created_at, updated_at, streak_days, weekly_reached, exercises, removed_at, removed_reason, gear
`

type CreatePostParams struct {
	ID              string
	AuthorID        string
	Kind            string
	Caption         *string
	Visibility      string
	WorkoutID       *string
	WorkoutName     *string
	TotalVolumeKg   *float64
	WorkingSets     *int32
	DurationSeconds *int32
	PrCount         *int32
	StreakDays      *int32
	WeeklyReached   *bool
	Exercises       []byte
	Gear            []byte
	MediaUrls       []string
	IdempotencyKey  *string
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, createPost,
		arg.ID,
		arg.AuthorID,
		arg.Kind,
		arg.Caption,
		arg.Visibility,
		arg.WorkoutID,
		arg.WorkoutName,
		arg.TotalVolumeKg,
		arg.WorkingSets,
		arg.DurationSeconds,
		arg.PrCount,
		arg.StreakDays,
		arg.WeeklyReached,
		arg.Exercises,
		arg.Gear,
		arg.MediaUrls,
		arg.IdempotencyKey,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Kind,
		&i.Caption,
		&i.Visibility,
		&i.ModerationStatus,
		&i.WorkoutID,
		&i.WorkoutName,
		&i.TotalVolumeKg,
		&i.WorkingSets,
		&i.DurationSeconds,
		&i.PrCount,
		&i.MediaUrls,
		&i.IdempotencyKey,
		&i.LikeCount,
		&i.CommentCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StreakDays,
		&i.WeeklyReached,
		&i.Exercises,
		&i.RemovedAt,
		&i.RemovedReason,
		&i.Gear,
	)
	return i, err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM comments WHERE id = $1
`

func (q *Queries) DeleteComment(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteComment, id)
	return err
}

const deletePost = `-- name: DeletePost :exec
DELETE FROM posts WHERE id = $1 AND author_id = $2
`

type DeletePostParams struct {
	ID       string
	AuthorID string
}

func (q *Queries) DeletePost(ctx context.Context, arg DeletePostParams) error {
	_, err := q.db.Exec(ctx, deletePost, arg.ID, arg.AuthorID)
	return err
}

const dropFollowBothWays = `-- name: DropFollowBothWays :exec
DELETE FROM follows
WHERE (follower_id = $1::text AND followee_id = $2::text)
   OR (follower_id = $2::text AND followee_id = $1::text)
`

type DropFollowBothWaysParams struct {
	A string
	B string
}

func (q *Queries) DropFollowBothWays(ctx context.Context, arg DropFollowBothWaysParams) error {
	_, err := q.db.Exec(ctx, dropFollowBothWays, arg.A, arg.B)
	return err
}

const follow = `-- name: Follow :execrows
INSERT INTO follows (follower_id, followee_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type FollowParams struct {
	FollowerID string
	FolloweeID string
}

func (q *Queries) Follow(ctx context.Context, arg FollowParams) (int64, error) {
	result, err := q.db.Exec(ctx, follow, arg.FollowerID, arg.FolloweeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getComment = `-- name: GetComment :one
SELECT id, post_id, author_id, body, moderation_status, created_at, parent_id, like_count, reply_count, removed_at FROM comments WHERE id = $1
`

func (q *Queries) GetComment(ctx context.Context, id string) (Comment, error) {
	row := q.db.QueryRow(ctx, getComment, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.AuthorID,
		&i.Body,
		&i.ModerationStatus,
		&i.CreatedAt,
		&i.ParentID,
		&i.LikeCount,
		&i.ReplyCount,
		&i.RemovedAt,
	)
	return i, err
}

const getPost = `-- name: GetPost :one
SELECT p.id, p.author_id, p.kind, p.caption, p.visibility, p.moderation_status, p.workout_id, p.workout_name, p.total_volume_kg, p.working_sets, p.duration_seconds, p.pr_count, p.media_urls, p.idempotency_key, p.like_count, p.comment_count, p.created_at, p.updated_at, p.streak_days, p.weekly_reached, p.exercises, p.removed_at, p.removed_reason, p.gear, u.display_name AS author_name, u.avatar_url AS author_avatar,
       (l.user_id IS NOT NULL)::boolean AS liked_by_me,
       (bm.user_id IS NOT NULL)::boolean AS bookmarked_by_me
FROM posts p
JOIN users u ON u.id = p.author_id
LEFT JOIN post_likes l ON l.post_id = p.id AND l.user_id = $1::text
LEFT JOIN post_bookmarks bm ON bm.post_id = p.id AND bm.user_id = $1::text
WHERE p.id = $2::text
`

type GetPostParams struct {
	ViewerID string
	PostID   string
}

type GetPostRow struct {
	ID               string
	AuthorID         string
	Kind             string
	Caption          *string
	Visibility       string
	ModerationStatus string
	WorkoutID        *string
	WorkoutName      *string
	TotalVolumeKg    *float64
	WorkingSets      *int32
	DurationSeconds  *int32
	PrCount          *int32
	MediaUrls        []string
	IdempotencyKey   *string
	LikeCount        int32
	CommentCount     int32
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	StreakDays       *int32
	WeeklyReached    *bool
	Exercises        []byte
	RemovedAt        pgtype.Timestamptz
	RemovedReason    *string
	Gear             []byte
	AuthorName       *string
	AuthorAvatar     *string
	LikedByMe        bool
	BookmarkedByMe   bool
}

func (q *Queries) GetPost(ctx context.Context, arg GetPostParams) (GetPostRow, error) {
	row := q.db.QueryRow(ctx, getPost, arg.ViewerID, arg.PostID)
	var i GetPostRow
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Kind,
		&i.Caption,
		&i.Visibility,
		&i.ModerationStatus,
		&i.WorkoutID,
		&i.WorkoutName,
		&i.TotalVolumeKg,
		&i.WorkingSets,
		&i.DurationSeconds,
		&i.PrCount,
		&i.MediaUrls,
		&i.IdempotencyKey,
		&i.LikeCount,
		&i.CommentCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StreakDays,
		&i.WeeklyReached,
		&i.Exercises,
		&i.RemovedAt,
		&i.RemovedReason,
		&i.Gear,
		&i.AuthorName,
		&i.AuthorAvatar,
		&i.LikedByMe,
		&i.BookmarkedByMe,
	)
	return i, err
}

const getPostAuthor = `-- name: GetPostAuthor :one
SELECT author_id FROM posts WHERE id = $1
`

// 댓글 삭제 권한 판정이 쓴다(글 주인도 지울 수 있다).
func (q *Queries) GetPostAuthor(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getPostAuthor, id)
	var author_id string
	err := row.Scan(&author_id)
	return author_id, err
}

const getPostByIdempotencyKey = `-- name: GetPostByIdempotencyKey :one
SELECT p.id, p.author_id, p.kind, p.caption, p.visibility, p.moderation_status, p.workout_id, p.workout_name, p.total_volume_kg, p.working_sets, p.duration_seconds, p.pr_count, p.media_urls, p.idempotency_key, p.like_count, p.comment_count, p.created_at, p.updated_at, p.streak_days, p.weekly_reached, p.exercises, p.removed_at, p.removed_reason, p.gear, u.display_name AS author_name, u.avatar_url AS author_avatar,
       false::boolean AS liked_by_me,
       false::boolean AS bookmarked_by_me
FROM posts p
JOIN users u ON u.id = p.author_id
WHERE p.author_id = $1 AND p.idempotency_key = $2
`

type GetPostByIdempotencyKeyParams struct {
	AuthorID       string
	IdempotencyKey *string
}

type GetPostByIdempotencyKeyRow struct {
	ID               string
	AuthorID         string
	Kind             string
	Caption          *string
	Visibility       string
	ModerationStatus string
	WorkoutID        *string
	WorkoutName      *string
	TotalVolumeKg    *float64
	WorkingSets      *int32
	DurationSeconds  *int32
	PrCount          *int32
	MediaUrls        []string
	IdempotencyKey   *string
	LikeCount        int32
	CommentCount     int32
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	StreakDays       *int32
	WeeklyReached    *bool
	Exercises        []byte
	RemovedAt        pgtype.Timestamptz
	RemovedReason    *string
	Gear             []byte
	AuthorName       *string
	AuthorAvatar     *string
	LikedByMe        bool
	BookmarkedByMe   bool
}

// 같은 멱등 키로 이미 올린 글 — 재시도가 두 번째 글을 만들지 않게.
func (q *Queries) GetPostByIdempotencyKey(ctx context.Context, arg GetPostByIdempotencyKeyParams) (GetPostByIdempotencyKeyRow, error) {
	row := q.db.QueryRow(ctx, getPostByIdempotencyKey, arg.AuthorID, arg.IdempotencyKey)
	var i GetPostByIdempotencyKeyRow
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Kind,
		&i.Caption,
		&i.Visibility,
		&i.ModerationStatus,
		&i.WorkoutID,
		&i.WorkoutName,
		&i.TotalVolumeKg,
		&i.WorkingSets,
		&i.DurationSeconds,
		&i.PrCount,
		&i.MediaUrls,
		&i.IdempotencyKey,
		&i.LikeCount,
		&i.CommentCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StreakDays,
		&i.WeeklyReached,
		&i.Exercises,
		&i.RemovedAt,
		&i.RemovedReason,
		&i.Gear,
		&i.AuthorName,
		&i.AuthorAvatar,
		&i.LikedByMe,
		&i.BookmarkedByMe,
	)
	return i, err
}

const getProfileCounts = `-- name: GetProfileCounts :one
SELECT
  (SELECT count(*) FROM posts   WHERE author_id = $1::text AND moderation_status = 'approved')::int AS post_count,
  (SELECT count(*) FROM follows WHERE followee_id = $1::text)::int AS follower_count,
  (SELECT count(*) FROM follows WHERE follower_id = $1::text)::int AS following_count
`

type GetProfileCountsRow struct {
	PostCount      int32
	FollowerCount  int32
	FollowingCount int32
}

// ── 프로필 ──────────────────────────────────────────────────────────────────
// 카운트는 저장하지 않고 셀 때 센다 — 프로필은 피드만큼 자주 열리지 않는다.
func (q *Queries) GetProfileCounts(ctx context.Context, userID string) (GetProfileCountsRow, error) {
	row := q.db.QueryRow(ctx, getProfileCounts, userID)
	var i GetProfileCountsRow
	err := row.Scan(&i.PostCount, &i.FollowerCount, &i.FollowingCount)
	return i, err
}

const isBlockedByMe = `-- name: IsBlockedByMe :one
SELECT EXISTS (
  SELECT 1 FROM blocks WHERE blocker_id = $1 AND blocked_id = $2
)::boolean
`

type IsBlockedByMeParams struct {
	BlockerID string
	BlockedID string
}

func (q *Queries) IsBlockedByMe(ctx context.Context, arg IsBlockedByMeParams) (bool, error) {
	row := q.db.QueryRow(ctx, isBlockedByMe, arg.BlockerID, arg.BlockedID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const isBlockedEitherWay = `-- name: IsBlockedEitherWay :one
SELECT EXISTS (
  SELECT 1 FROM blocks
  WHERE (blocker_id = $1::text AND blocked_id = $2::text)
     OR (blocker_id = $2::text AND blocked_id = $1::text)
)::boolean
`

type IsBlockedEitherWayParams struct {
	A string
	B string
}

// 단건 조회의 접근 판정이 쓴다. 차단은 **양방향**으로 가린다.
func (q *Queries) IsBlockedEitherWay(ctx context.Context, arg IsBlockedEitherWayParams) (bool, error) {
	row := q.db.QueryRow(ctx, isBlockedEitherWay, arg.A, arg.B)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const isFollowing = `-- name: IsFollowing :one
SELECT EXISTS (SELECT 1 FROM follows WHERE follower_id = $1 AND followee_id = $2)
`

type IsFollowingParams struct {
	FollowerID string
	FolloweeID string
}

func (q *Queries) IsFollowing(ctx context.Context, arg IsFollowingParams) (bool, error) {
	row := q.db.QueryRow(ctx, isFollowing, arg.FollowerID, arg.FolloweeID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const likeComment = `-- name: LikeComment :execrows
INSERT INTO comment_likes (comment_id, user_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type LikeCommentParams struct {
	CommentID string
	UserID    string
}

func (q *Queries) LikeComment(ctx context.Context, arg LikeCommentParams) (int64, error) {
	result, err := q.db.Exec(ctx, likeComment, arg.CommentID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const likePost = `-- name: LikePost :execrows
INSERT INTO post_likes (post_id, user_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type LikePostParams struct {
	PostID string
	UserID string
}

// 좋아요는 멱등이다 — 두 번 눌러도 하나.
func (q *Queries) LikePost(ctx context.Context, arg LikePostParams) (int64, error) {
	result, err := q.db.Exec(ctx, likePost, arg.PostID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listBlockedUsers = `-- name: ListBlockedUsers :many
SELECT u.id, u.display_name, u.avatar_url
FROM blocks b
JOIN users u ON u.id = b.blocked_id
WHERE b.blocker_id = $1::text
ORDER BY b.created_at DESC
`

type ListBlockedUsersRow struct {
	ID          string
	DisplayName *string
	AvatarUrl   *string
}

// 내가 차단한 사람들 — 풀려면 여기서 찾아야 한다.
func (q *Queries) ListBlockedUsers(ctx context.Context, viewerID string) ([]ListBlockedUsersRow, error) {
	rows, err := q.db.Query(ctx, listBlockedUsers, viewerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBlockedUsersRow
	for rows.Next() {
		var i ListBlockedUsersRow
		if err := rows.Scan(&i.ID, &i.DisplayName, &i.AvatarUrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookmarks = `-- name: ListBookmarks :many
SELECT p.id, p.author_id, p.kind, p.caption, p.visibility, p.moderation_status, p.workout_id, p.workout_name, p.total_volume_kg, p.working_sets, p.duration_seconds, p.pr_count, p.media_urls, p.idempotency_key, p.like_count, p.comment_count, p.created_at, p.updated_at, p.streak_days, p.weekly_reached, p.exercises, p.removed_at, p.removed_reason, p.gear, u.display_name AS author_name, u.avatar_url AS author_avatar,
       (l.user_id IS NOT NULL)::boolean AS liked_by_me,
       true::boolean AS bookmarked_by_me
FROM post_bookmarks bm
JOIN posts p ON p.id = bm.post_id
JOIN users u ON u.id = p.author_id
LEFT JOIN post_likes l ON l.post_id = p.id AND l.user_id = $1::text
WHERE bm.user_id = $1::text
  AND p.moderation_status = 'approved'
  AND (
    p.author_id = $1::text
    OR p.visibility = 'public'
    OR (
      p.visibility = 'followers'
      AND EXISTS (
        SELECT 1 FROM follows f
        WHERE f.follower_id = $1::text AND f.followee_id = p.author_id
      )
    )
  )
  AND NOT EXISTS (
    SELECT 1 FROM blocks b
    WHERE (b.blocker_id = $1::text AND b.blocked_id = p.author_id)
       OR (b.blocker_id = p.author_id AND b.blocked_id = $1::text)
  )
  AND (
    $2::boolean = false
    OR (p.created_at, p.id) < ($3::timestamptz, $4::text)
  )
ORDER BY p.created_at DESC, p.id DESC
LIMIT $5
`

type ListBookmarksParams struct {
	ViewerID  string
	HasCursor bool
	CursorAt  pgtype.Timestamptz
	CursorID  string
	Lim       int32
}

type ListBookmarksRow struct {
	ID               string
	AuthorID         string
	Kind             string
	Caption          *string
	Visibility       string
	ModerationStatus string
	WorkoutID        *string
	WorkoutName      *string
	TotalVolumeKg    *float64
	WorkingSets      *int32
	DurationSeconds  *int32
	PrCount          *int32
	MediaUrls        []string
	IdempotencyKey   *string
	LikeCount        int32
	CommentCount     int32
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	StreakDays       *int32
	WeeklyReached    *bool
	Exercises        []byte
	RemovedAt        pgtype.Timestamptz
	RemovedReason    *string
	Gear             []byte
	AuthorName       *string
	AuthorAvatar     *string
	LikedByMe        bool
	BookmarkedByMe   bool
}

// 내가 저장한 글. 그새 못 보게 된 글(비공개 전환·차단)은 빠진다 — 저장은 열람권이 아니다.
func (q *Queries) ListBookmarks(ctx context.Context, arg ListBookmarksParams) ([]ListBookmarksRow, error) {
	rows, err := q.db.Query(ctx, listBookmarks,
		arg.ViewerID,
		arg.HasCursor,
		arg.CursorAt,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBookmarksRow
	for rows.Next() {
		var i ListBookmarksRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Kind,
			&i.Caption,
			&i.Visibility,
			&i.ModerationStatus,
			&i.WorkoutID,
			&i.WorkoutName,
			&i.TotalVolumeKg,
			&i.WorkingSets,
			&i.DurationSeconds,
			&i.PrCount,
			&i.MediaUrls,
			&i.IdempotencyKey,
			&i.LikeCount,
			&i.CommentCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StreakDays,
			&i.WeeklyReached,
			&i.Exercises,
			&i.RemovedAt,
			&i.RemovedReason,
			&i.Gear,
			&i.AuthorName,
			&i.AuthorAvatar,
			&i.LikedByMe,
			&i.BookmarkedByMe,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComments = `-- name: ListComments :many
SELECT c.id, c.post_id, c.author_id, c.body, c.moderation_status, c.created_at, c.parent_id, c.like_count, c.reply_count, c.removed_at, u.display_name AS author_name, u.avatar_url AS author_avatar,
       (cl.user_id IS NOT NULL)::boolean AS liked_by_me
FROM comments c
JOIN users u ON u.id = c.author_id
LEFT JOIN comment_likes cl ON cl.comment_id = c.id AND cl.user_id = $1::text
WHERE c.post_id = $2::text
  AND c.parent_id IS NULL
  AND c.moderation_status = 'approved'
  AND (
    $3::boolean = false
    OR (c.created_at, c.id) > ($4::timestamptz, $5::text)
  )
ORDER BY c.created_at ASC, c.id ASC
LIMIT $6
`

type ListCommentsParams struct {
	ViewerID  string
	PostID    string
	HasCursor bool
	CursorAt  pgtype.Timestamptz
	CursorID  string
	Lim       int32
}

type ListCommentsRow struct {
	ID               string
	PostID           string
	AuthorID         string
	Body             string
	ModerationStatus string
	CreatedAt        pgtype.Timestamptz
	ParentID         *string
	LikeCount        int32
	ReplyCount       int32
	RemovedAt        pgtype.Timestamptz
	AuthorName       *string
	AuthorAvatar     *string
	LikedByMe        bool
}

func (q *Queries) ListComments(ctx context.Context, arg ListCommentsParams) ([]ListCommentsRow, error) {
	rows, err := q.db.Query(ctx, listComments,
		arg.ViewerID,
		arg.PostID,
		arg.HasCursor,
		arg.CursorAt,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommentsRow
	for rows.Next() {
		var i ListCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.AuthorID,
			&i.Body,
			&i.ModerationStatus,
			&i.CreatedAt,
			&i.ParentID,
			&i.LikeCount,
			&i.ReplyCount,
			&i.RemovedAt,
			&i.AuthorName,
			&i.AuthorAvatar,
			&i.LikedByMe,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExplore = `-- name: ListExplore :many
SELECT p.id, p.author_id, p.kind, p.caption, p.visibility, p.moderation_status, p.workout_id, p.workout_name, p.total_volume_kg, p.working_sets, p.duration_seconds, p.pr_count, p.media_urls, p.idempotency_key, p.like_count, p.comment_count, p.created_at, p.updated_at, p.streak_days, p.weekly_reached, p.exercises, p.removed_at, p.removed_reason, p.gear, u.display_name AS author_name, u.avatar_url AS author_avatar,
       (l.user_id IS NOT NULL)::boolean AS liked_by_me,
       (bm.user_id IS NOT NULL)::boolean AS bookmarked_by_me
FROM posts p
JOIN users u ON u.id = p.author_id
LEFT JOIN post_likes l ON l.post_id = p.id AND l.user_id = $1::text
LEFT JOIN post_bookmarks bm ON bm.post_id = p.id AND bm.user_id = $1::text
WHERE p.visibility = 'public'
  AND p.moderation_status = 'approved'
  AND NOT EXISTS (
    SELECT 1 FROM blocks b
    WHERE (b.blocker_id = $1::text AND b.blocked_id = p.author_id)
       OR (b.blocker_id = p.author_id AND b.blocked_id = $1::text)
  )
ORDER BY p.like_count DESC, p.created_at DESC, p.id DESC
LIMIT $2
`

type ListExploreParams struct {
	ViewerID string
	Lim      int32
}

type ListExploreRow struct {
	ID               string
	AuthorID         string
	Kind             string
	Caption          *string
	Visibility       string
	ModerationStatus string
	WorkoutID        *string
	WorkoutName      *string
	TotalVolumeKg    *float64
	WorkingSets      *int32
	DurationSeconds  *int32
	PrCount          *int32
	MediaUrls        []string
	IdempotencyKey   *string
	LikeCount        int32
	CommentCount     int32
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	StreakDays       *int32
	WeeklyReached    *bool
	Exercises        []byte
	RemovedAt        pgtype.Timestamptz
	RemovedReason    *string
	Gear             []byte
	AuthorName       *string
	AuthorAvatar     *string
	LikedByMe        bool
	BookmarkedByMe   bool
}

// ── 발견(Explore) ───────────────────────────────────────────────────────────
// 인기 글 — **공개·승인**만. 좋아요가 많은 순, 같으면 최신 순.
// 댓글 수로 정렬하지 않는 이유: 내려간 댓글까지 세어 순위가 오염된다(옛 서버의 판단 그대로).
func (q *Queries) ListExplore(ctx context.Context, arg ListExploreParams) ([]ListExploreRow, error) {
	rows, err := q.db.Query(ctx, listExplore, arg.ViewerID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExploreRow
	for rows.Next() {
		var i ListExploreRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Kind,
			&i.Caption,
			&i.Visibility,
			&i.ModerationStatus,
			&i.WorkoutID,
			&i.WorkoutName,
			&i.TotalVolumeKg,
			&i.WorkingSets,
			&i.DurationSeconds,
			&i.PrCount,
			&i.MediaUrls,
			&i.IdempotencyKey,
			&i.LikeCount,
			&i.CommentCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StreakDays,
			&i.WeeklyReached,
			&i.Exercises,
			&i.RemovedAt,
			&i.RemovedReason,
			&i.Gear,
			&i.AuthorName,
			&i.AuthorAvatar,
			&i.LikedByMe,
			&i.BookmarkedByMe,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeed = `-- name: ListFeed :many

SELECT p.id, p.author_id, p.kind, p.caption, p.visibility, p.moderation_status, p.workout_id, p.workout_name, p.total_volume_kg, p.working_sets, p.duration_seconds, p.pr_count, p.media_urls, p.idempotency_key, p.like_count, p.comment_count, p.created_at, p.updated_at, p.streak_days, p.weekly_reached, p.exercises, p.removed_at, p.removed_reason, p.gear, u.display_name AS author_name, u.avatar_url AS author_avatar,
       (l.user_id IS NOT NULL)::boolean AS liked_by_me,
       (bm.user_id IS NOT NULL)::boolean AS bookmarked_by_me
FROM posts p
JOIN users u ON u.id = p.author_id
LEFT JOIN post_likes l ON l.post_id = p.id AND l.user_id = $1::text
LEFT JOIN post_bookmarks bm ON bm.post_id = p.id AND bm.user_id = $1::text
WHERE p.moderation_status = 'approved'
  AND (
    p.author_id = $1::text
    OR (
      p.visibility IN ('public', 'followers')
      AND EXISTS (
        SELECT 1 FROM follows f
        WHERE f.follower_id = $1::text AND f.followee_id = p.author_id
      )
    )
  )
  AND NOT EXISTS (
    SELECT 1 FROM blocks b
    WHERE (b.blocker_id = $1::text AND b.blocked_id = p.author_id)
       OR (b.blocker_id = p.author_id AND b.blocked_id = $1::text)
  )
  AND (
    $2::boolean = false
    OR (p.created_at, p.id) < ($3::timestamptz, $4::text)
  )
ORDER BY p.created_at DESC, p.id DESC
LIMIT $5
`

type ListFeedParams struct {
	ViewerID  string
	HasCursor bool
	CursorAt  pgtype.Timestamptz
	CursorID  string
	Lim       int32
}

type ListFeedRow struct {
	ID               string
	AuthorID         string
	Kind             string
	Caption          *string
	Visibility       string
	ModerationStatus string
	WorkoutID        *string
	WorkoutName      *string
	TotalVolumeKg    *float64
	WorkingSets      *int32
	DurationSeconds  *int32
	PrCount          *int32
	MediaUrls        []string
	IdempotencyKey   *string
	LikeCount        int32
	CommentCount     int32
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	StreakDays       *int32
	WeeklyReached    *bool
	Exercises        []byte
	RemovedAt        pgtype.Timestamptz
	RemovedReason    *string
	Gear             []byte
	AuthorName       *string
	AuthorAvatar     *string
	LikedByMe        bool
	BookmarkedByMe   bool
}

// @plm SRS-007  피드 쿼리 — 여기 있는 것은 SQL뿐이다
//
// 규칙(누가 무엇을 볼 수 있는가·누가 지울 수 있는가)은 internal/feed/service.go가 안다.
// 다만 **누구의 글을 고를 것인가**는 SQL이 한다 — 팔로우·차단 목록을 Go로 가져와 거르면
// 사람이 늘수록 느려지고, 페이지 크기도 못 맞춘다.
// 피드 한 페이지.
//
// 보이는 것: 내 글 전부 + 팔로우하는 사람의 public|followers 글.
// 가리는 것: 내려간 글 · 내가 차단한 사람 · 나를 차단한 사람(양방향).
// 커서: (created_at, id)를 함께 비교한다 — 같은 시각의 글이 새거나 겹치지 않게.
func (q *Queries) ListFeed(ctx context.Context, arg ListFeedParams) ([]ListFeedRow, error) {
	rows, err := q.db.Query(ctx, listFeed,
		arg.ViewerID,
		arg.HasCursor,
		arg.CursorAt,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFeedRow
	for rows.Next() {
		var i ListFeedRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Kind,
			&i.Caption,
			&i.Visibility,
			&i.ModerationStatus,
			&i.WorkoutID,
			&i.WorkoutName,
			&i.TotalVolumeKg,
			&i.WorkingSets,
			&i.DurationSeconds,
			&i.PrCount,
			&i.MediaUrls,
			&i.IdempotencyKey,
			&i.LikeCount,
			&i.CommentCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StreakDays,
			&i.WeeklyReached,
			&i.Exercises,
			&i.RemovedAt,
			&i.RemovedReason,
			&i.Gear,
			&i.AuthorName,
			&i.AuthorAvatar,
			&i.LikedByMe,
			&i.BookmarkedByMe,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFollowers = `-- name: ListFollowers :many
SELECT u.id, u.display_name, u.avatar_url,
       EXISTS (SELECT 1 FROM follows f2 WHERE f2.follower_id = $1::text AND f2.followee_id = u.id)::boolean AS following
FROM follows f
JOIN users u ON u.id = f.follower_id
WHERE f.followee_id = $2::text
  AND NOT EXISTS (
    SELECT 1 FROM blocks b
    WHERE (b.blocker_id = $1::text AND b.blocked_id = u.id)
       OR (b.blocker_id = u.id AND b.blocked_id = $1::text)
  )
ORDER BY f.created_at DESC
LIMIT $3
`

type ListFollowersParams struct {
	ViewerID string
	UserID   string
	Lim      int32
}

type ListFollowersRow struct {
	ID          string
	DisplayName *string
	AvatarUrl   *string
	Following   bool
}

func (q *Queries) ListFollowers(ctx context.Context, arg ListFollowersParams) ([]ListFollowersRow, error) {
	rows, err := q.db.Query(ctx, listFollowers, arg.ViewerID, arg.UserID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFollowersRow
	for rows.Next() {
		var i ListFollowersRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Following,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFollowing = `-- name: ListFollowing :many
SELECT u.id, u.display_name, u.avatar_url,
       EXISTS (SELECT 1 FROM follows f2 WHERE f2.follower_id = $1::text AND f2.followee_id = u.id)::boolean AS following
FROM follows f
JOIN users u ON u.id = f.followee_id
WHERE f.follower_id = $2::text
  AND NOT EXISTS (
    SELECT 1 FROM blocks b
    WHERE (b.blocker_id = $1::text AND b.blocked_id = u.id)
       OR (b.blocker_id = u.id AND b.blocked_id = $1::text)
  )
ORDER BY f.created_at DESC
LIMIT $3
`

type ListFollowingParams struct {
	ViewerID string
	UserID   string
	Lim      int32
}

type ListFollowingRow struct {
	ID          string
	DisplayName *string
	AvatarUrl   *string
	Following   bool
}

func (q *Queries) ListFollowing(ctx context.Context, arg ListFollowingParams) ([]ListFollowingRow, error) {
	rows, err := q.db.Query(ctx, listFollowing, arg.ViewerID, arg.UserID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFollowingRow
	for rows.Next() {
		var i ListFollowingRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Following,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHashtagPosts = `-- name: ListHashtagPosts :many
SELECT p.id, p.author_id, p.kind, p.caption, p.visibility, p.moderation_status, p.workout_id, p.workout_name, p.total_volume_kg, p.working_sets, p.duration_seconds, p.pr_count, p.media_urls, p.idempotency_key, p.like_count, p.comment_count, p.created_at, p.updated_at, p.streak_days, p.weekly_reached, p.exercises, p.removed_at, p.removed_reason, p.gear, u.display_name AS author_name, u.avatar_url AS author_avatar,
       (l.user_id IS NOT NULL)::boolean AS liked_by_me,
       (bm.user_id IS NOT NULL)::boolean AS bookmarked_by_me
FROM post_hashtags h
JOIN posts p ON p.id = h.post_id
JOIN users u ON u.id = p.author_id
LEFT JOIN post_likes l ON l.post_id = p.id AND l.user_id = $1::text
LEFT JOIN post_bookmarks bm ON bm.post_id = p.id AND bm.user_id = $1::text
WHERE h.tag = $2::text
  AND p.moderation_status = 'approved'
  AND (p.visibility = 'public' OR p.author_id = $1::text)
  AND NOT EXISTS (
    SELECT 1 FROM blocks b
    WHERE (b.blocker_id = $1::text AND b.blocked_id = p.author_id)
       OR (b.blocker_id = p.author_id AND b.blocked_id = $1::text)
  )
  AND (
    $3::boolean = false
    OR (p.created_at, p.id) < ($4::timestamptz, $5::text)
  )
ORDER BY p.created_at DESC, p.id DESC
LIMIT $6
`

type ListHashtagPostsParams struct {
	ViewerID  string
	Tag       string
	HasCursor bool
	CursorAt  pgtype.Timestamptz
	CursorID  string
	Lim       int32
}

type ListHashtagPostsRow struct {
	ID               string
	AuthorID         string
	Kind             string
	Caption          *string
	Visibility       string
	ModerationStatus string
	WorkoutID        *string
	WorkoutName      *string
	TotalVolumeKg    *float64
	WorkingSets      *int32
	DurationSeconds  *int32
	PrCount          *int32
	MediaUrls        []string
	IdempotencyKey   *string
	LikeCount        int32
	CommentCount     int32
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	StreakDays       *int32
	WeeklyReached    *bool
	Exercises        []byte
	RemovedAt        pgtype.Timestamptz
	RemovedReason    *string
	Gear             []byte
	AuthorName       *string
	AuthorAvatar     *string
	LikedByMe        bool
	BookmarkedByMe   bool
}

// 태그로 모아 보기. 공개 글만(팔로워 전용·비공개는 태그로 새 나가면 안 된다).
func (q *Queries) ListHashtagPosts(ctx context.Context, arg ListHashtagPostsParams) ([]ListHashtagPostsRow, error) {
	rows, err := q.db.Query(ctx, listHashtagPosts,
		arg.ViewerID,
		arg.Tag,
		arg.HasCursor,
		arg.CursorAt,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHashtagPostsRow
	for rows.Next() {
		var i ListHashtagPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Kind,
			&i.Caption,
			&i.Visibility,
			&i.ModerationStatus,
			&i.WorkoutID,
			&i.WorkoutName,
			&i.TotalVolumeKg,
			&i.WorkingSets,
			&i.DurationSeconds,
			&i.PrCount,
			&i.MediaUrls,
			&i.IdempotencyKey,
			&i.LikeCount,
			&i.CommentCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StreakDays,
			&i.WeeklyReached,
			&i.Exercises,
			&i.RemovedAt,
			&i.RemovedReason,
			&i.Gear,
			&i.AuthorName,
			&i.AuthorAvatar,
			&i.LikedByMe,
			&i.BookmarkedByMe,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReplies = `-- name: ListReplies :many
SELECT c.id, c.post_id, c.author_id, c.body, c.moderation_status, c.created_at, c.parent_id, c.like_count, c.reply_count, c.removed_at, u.display_name AS author_name, u.avatar_url AS author_avatar,
       (cl.user_id IS NOT NULL)::boolean AS liked_by_me
FROM comments c
JOIN users u ON u.id = c.author_id
LEFT JOIN comment_likes cl ON cl.comment_id = c.id AND cl.user_id = $1::text
WHERE c.parent_id = $2::text
  AND c.moderation_status = 'approved'
ORDER BY c.created_at ASC, c.id ASC
LIMIT $3
`

type ListRepliesParams struct {
	ViewerID string
	ParentID string
	Lim      int32
}

type ListRepliesRow struct {
	ID               string
	PostID           string
	AuthorID         string
	Body             string
	ModerationStatus string
	CreatedAt        pgtype.Timestamptz
	ParentID         *string
	LikeCount        int32
	ReplyCount       int32
	RemovedAt        pgtype.Timestamptz
	AuthorName       *string
	AuthorAvatar     *string
	LikedByMe        bool
}

// ── 댓글: 답글과 좋아요 ─────────────────────────────────────────────────────
func (q *Queries) ListReplies(ctx context.Context, arg ListRepliesParams) ([]ListRepliesRow, error) {
	rows, err := q.db.Query(ctx, listReplies, arg.ViewerID, arg.ParentID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRepliesRow
	for rows.Next() {
		var i ListRepliesRow
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.AuthorID,
			&i.Body,
			&i.ModerationStatus,
			&i.CreatedAt,
			&i.ParentID,
			&i.LikeCount,
			&i.ReplyCount,
			&i.RemovedAt,
			&i.AuthorName,
			&i.AuthorAvatar,
			&i.LikedByMe,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserPosts = `-- name: ListUserPosts :many
SELECT p.id, p.author_id, p.kind, p.caption, p.visibility, p.moderation_status, p.workout_id, p.workout_name, p.total_volume_kg, p.working_sets, p.duration_seconds, p.pr_count, p.media_urls, p.idempotency_key, p.like_count, p.comment_count, p.created_at, p.updated_at, p.streak_days, p.weekly_reached, p.exercises, p.removed_at, p.removed_reason, p.gear, u.display_name AS author_name, u.avatar_url AS author_avatar,
       (l.user_id IS NOT NULL)::boolean AS liked_by_me,
       (bm.user_id IS NOT NULL)::boolean AS bookmarked_by_me
FROM posts p
JOIN users u ON u.id = p.author_id
LEFT JOIN post_likes l ON l.post_id = p.id AND l.user_id = $1::text
LEFT JOIN post_bookmarks bm ON bm.post_id = p.id AND bm.user_id = $1::text
WHERE p.author_id = $2::text
  AND p.moderation_status = 'approved'
  AND p.visibility = ANY ($3::text[])
  AND NOT EXISTS (
    SELECT 1 FROM blocks b
    WHERE (b.blocker_id = $1::text AND b.blocked_id = p.author_id)
       OR (b.blocker_id = p.author_id AND b.blocked_id = $1::text)
  )
  AND (
    $4::boolean = false
    OR (p.created_at, p.id) < ($5::timestamptz, $6::text)
  )
ORDER BY p.created_at DESC, p.id DESC
LIMIT $7
`

type ListUserPostsParams struct {
	ViewerID          string
	AuthorID          string
	AllowedVisibility []string
	HasCursor         bool
	CursorAt          pgtype.Timestamptz
	CursorID          string
	Lim               int32
}

type ListUserPostsRow struct {
	ID               string
	AuthorID         string
	Kind             string
	Caption          *string
	Visibility       string
	ModerationStatus string
	WorkoutID        *string
	WorkoutName      *string
	TotalVolumeKg    *float64
	WorkingSets      *int32
	DurationSeconds  *int32
	PrCount          *int32
	MediaUrls        []string
	IdempotencyKey   *string
	LikeCount        int32
	CommentCount     int32
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	StreakDays       *int32
	WeeklyReached    *bool
	Exercises        []byte
	RemovedAt        pgtype.Timestamptz
	RemovedReason    *string
	Gear             []byte
	AuthorName       *string
	AuthorAvatar     *string
	LikedByMe        bool
	BookmarkedByMe   bool
}

// 한 사람의 글. 보는 사람과의 관계가 공개범위를 정한다:
//
//	본인      public + followers + private
//	팔로워    public + followers
//	그 외     public
func (q *Queries) ListUserPosts(ctx context.Context, arg ListUserPostsParams) ([]ListUserPostsRow, error) {
	rows, err := q.db.Query(ctx, listUserPosts,
		arg.ViewerID,
		arg.AuthorID,
		arg.AllowedVisibility,
		arg.HasCursor,
		arg.CursorAt,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserPostsRow
	for rows.Next() {
		var i ListUserPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Kind,
			&i.Caption,
			&i.Visibility,
			&i.ModerationStatus,
			&i.WorkoutID,
			&i.WorkoutName,
			&i.TotalVolumeKg,
			&i.WorkingSets,
			&i.DurationSeconds,
			&i.PrCount,
			&i.MediaUrls,
			&i.IdempotencyKey,
			&i.LikeCount,
			&i.CommentCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StreakDays,
			&i.WeeklyReached,
			&i.Exercises,
			&i.RemovedAt,
			&i.RemovedReason,
			&i.Gear,
			&i.AuthorName,
			&i.AuthorAvatar,
			&i.LikedByMe,
			&i.BookmarkedByMe,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchHashtags = `-- name: SearchHashtags :many
SELECT h.tag, count(*)::int AS uses
FROM post_hashtags h
JOIN posts p ON p.id = h.post_id
WHERE p.visibility = 'public'
  AND p.moderation_status = 'approved'
  AND position(lower($1::text) in h.tag) > 0
  AND NOT EXISTS (
    SELECT 1 FROM blocks b
    WHERE (b.blocker_id = $2::text AND b.blocked_id = p.author_id)
       OR (b.blocker_id = p.author_id AND b.blocked_id = $2::text)
  )
GROUP BY h.tag
ORDER BY count(*) DESC, h.tag
LIMIT $3
`

type SearchHashtagsParams struct {
	Q        string
	ViewerID string
	Lim      int32
}

type SearchHashtagsRow struct {
	Tag  string
	Uses int32
}

// 태그 검색 — 이름에 포함되는 태그를 많이 쓰인 순으로.
func (q *Queries) SearchHashtags(ctx context.Context, arg SearchHashtagsParams) ([]SearchHashtagsRow, error) {
	rows, err := q.db.Query(ctx, searchHashtags, arg.Q, arg.ViewerID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchHashtagsRow
	for rows.Next() {
		var i SearchHashtagsRow
		if err := rows.Scan(&i.Tag, &i.Uses); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPosts = `-- name: SearchPosts :many
SELECT p.id, p.author_id, p.kind, p.caption, p.visibility, p.moderation_status, p.workout_id, p.workout_name, p.total_volume_kg, p.working_sets, p.duration_seconds, p.pr_count, p.media_urls, p.idempotency_key, p.like_count, p.comment_count, p.created_at, p.updated_at, p.streak_days, p.weekly_reached, p.exercises, p.removed_at, p.removed_reason, p.gear, u.display_name AS author_name, u.avatar_url AS author_avatar,
       (l.user_id IS NOT NULL)::boolean AS liked_by_me,
       (bm.user_id IS NOT NULL)::boolean AS bookmarked_by_me
FROM posts p
JOIN users u ON u.id = p.author_id
LEFT JOIN post_likes l ON l.post_id = p.id AND l.user_id = $1::text
LEFT JOIN post_bookmarks bm ON bm.post_id = p.id AND bm.user_id = $1::text
WHERE p.visibility = 'public'
  AND p.moderation_status = 'approved'
  AND position(lower($2::text) in lower(coalesce(p.caption, ''))) > 0
  AND NOT EXISTS (
    SELECT 1 FROM blocks b
    WHERE (b.blocker_id = $1::text AND b.blocked_id = p.author_id)
       OR (b.blocker_id = p.author_id AND b.blocked_id = $1::text)
  )
ORDER BY p.created_at DESC, p.id DESC
LIMIT $3
`

type SearchPostsParams struct {
	ViewerID string
	Q        string
	Lim      int32
}

type SearchPostsRow struct {
	ID               string
	AuthorID         string
	Kind             string
	Caption          *string
	Visibility       string
	ModerationStatus string
	WorkoutID        *string
	WorkoutName      *string
	TotalVolumeKg    *float64
	WorkingSets      *int32
	DurationSeconds  *int32
	PrCount          *int32
	MediaUrls        []string
	IdempotencyKey   *string
	LikeCount        int32
	CommentCount     int32
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	StreakDays       *int32
	WeeklyReached    *bool
	Exercises        []byte
	RemovedAt        pgtype.Timestamptz
	RemovedReason    *string
	Gear             []byte
	AuthorName       *string
	AuthorAvatar     *string
	LikedByMe        bool
	BookmarkedByMe   bool
}

// 캡션으로 글 찾기 — 공개·승인만. 사용자가 친 '%'가 와일드카드가 되지 않게 position()을 쓴다.
func (q *Queries) SearchPosts(ctx context.Context, arg SearchPostsParams) ([]SearchPostsRow, error) {
	rows, err := q.db.Query(ctx, searchPosts, arg.ViewerID, arg.Q, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchPostsRow
	for rows.Next() {
		var i SearchPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Kind,
			&i.Caption,
			&i.Visibility,
			&i.ModerationStatus,
			&i.WorkoutID,
			&i.WorkoutName,
			&i.TotalVolumeKg,
			&i.WorkingSets,
			&i.DurationSeconds,
			&i.PrCount,
			&i.MediaUrls,
			&i.IdempotencyKey,
			&i.LikeCount,
			&i.CommentCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StreakDays,
			&i.WeeklyReached,
			&i.Exercises,
			&i.RemovedAt,
			&i.RemovedReason,
			&i.Gear,
			&i.AuthorName,
			&i.AuthorAvatar,
			&i.LikedByMe,
			&i.BookmarkedByMe,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsers = `-- name: SearchUsers :many
SELECT u.id, u.display_name, u.avatar_url,
       EXISTS (SELECT 1 FROM follows f WHERE f.follower_id = $1::text AND f.followee_id = u.id) ::boolean AS following
FROM users u
WHERE u.id <> $1::text
  AND (
    position(lower($2::text) in lower(coalesce(u.display_name, ''))) > 0
    OR position(lower($2::text) in lower(coalesce(u.email, ''))) > 0
  )
  AND NOT EXISTS (
    SELECT 1 FROM blocks b
    WHERE (b.blocker_id = $1::text AND b.blocked_id = u.id)
       OR (b.blocker_id = u.id AND b.blocked_id = $1::text)
  )
ORDER BY u.display_name NULLS LAST, u.id
LIMIT $3
`

type SearchUsersParams struct {
	ViewerID string
	Q        string
	Lim      int32
}

type SearchUsersRow struct {
	ID          string
	DisplayName *string
	AvatarUrl   *string
	Following   bool
}

// 사람 찾기 — 표시 이름·이메일 부분일치. 자기 자신과 차단 관계는 뺀다.
// LIKE 대신 position()을 쓴다: 사용자가 친 '%'가 와일드카드로 해석되면 전부 일치가 된다.
func (q *Queries) SearchUsers(ctx context.Context, arg SearchUsersParams) ([]SearchUsersRow, error) {
	rows, err := q.db.Query(ctx, searchUsers, arg.ViewerID, arg.Q, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchUsersRow
	for rows.Next() {
		var i SearchUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Following,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const suggestFriendsOfFriends = `-- name: SuggestFriendsOfFriends :many
SELECT u.id, u.display_name, u.avatar_url, count(*)::int AS mutuals
FROM follows f
JOIN follows ff ON ff.follower_id = f.followee_id
JOIN users u ON u.id = ff.followee_id
WHERE f.follower_id = $1::text
  AND ff.followee_id <> $1::text
  -- 이미 팔로우하는 사람은 뺀다.
  AND NOT EXISTS (
    SELECT 1 FROM follows mine
    WHERE mine.follower_id = $1::text AND mine.followee_id = ff.followee_id
  )
  AND NOT EXISTS (
    SELECT 1 FROM blocks b
    WHERE (b.blocker_id = $1::text AND b.blocked_id = ff.followee_id)
       OR (b.blocker_id = ff.followee_id AND b.blocked_id = $1::text)
  )
GROUP BY u.id, u.display_name, u.avatar_url
ORDER BY count(*) DESC, u.id
LIMIT $2
`

type SuggestFriendsOfFriendsParams struct {
	ViewerID string
	Lim      int32
}

type SuggestFriendsOfFriendsRow struct {
	ID          string
	DisplayName *string
	AvatarUrl   *string
	Mutuals     int32
}

// 추천 ① 친구의 친구 — 내가 팔로우하는 사람들이 팔로우하는 사람을, 겹치는 수가 많은 순으로.
func (q *Queries) SuggestFriendsOfFriends(ctx context.Context, arg SuggestFriendsOfFriendsParams) ([]SuggestFriendsOfFriendsRow, error) {
	rows, err := q.db.Query(ctx, suggestFriendsOfFriends, arg.ViewerID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SuggestFriendsOfFriendsRow
	for rows.Next() {
		var i SuggestFriendsOfFriendsRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Mutuals,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const suggestPopular = `-- name: SuggestPopular :many
SELECT u.id, u.display_name, u.avatar_url,
       (SELECT count(*) FROM follows f WHERE f.followee_id = u.id)::int AS followers
FROM users u
WHERE u.id <> $1::text
  AND u.id <> ALL ($2::text[])
  AND NOT EXISTS (
    SELECT 1 FROM follows mine
    WHERE mine.follower_id = $1::text AND mine.followee_id = u.id
  )
  AND NOT EXISTS (
    SELECT 1 FROM blocks b
    WHERE (b.blocker_id = $1::text AND b.blocked_id = u.id)
       OR (b.blocker_id = u.id AND b.blocked_id = $1::text)
  )
ORDER BY followers DESC, u.id
LIMIT $3
`

type SuggestPopularParams struct {
	ViewerID string
	Exclude  []string
	Lim      int32
}

type SuggestPopularRow struct {
	ID          string
	DisplayName *string
	AvatarUrl   *string
	Followers   int32
}

// 추천 ② 모자란 만큼 — 팔로워가 많은 사람으로 채운다.
func (q *Queries) SuggestPopular(ctx context.Context, arg SuggestPopularParams) ([]SuggestPopularRow, error) {
	rows, err := q.db.Query(ctx, suggestPopular, arg.ViewerID, arg.Exclude, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SuggestPopularRow
	for rows.Next() {
		var i SuggestPopularRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Followers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const trendingHashtags = `-- name: TrendingHashtags :many
SELECT h.tag, count(*)::int AS uses
FROM post_hashtags h
JOIN posts p ON p.id = h.post_id
WHERE p.moderation_status = 'approved'
  AND p.visibility = 'public'
  AND NOT EXISTS (
    SELECT 1 FROM blocks b
    WHERE (b.blocker_id = $1::text AND b.blocked_id = p.author_id)
       OR (b.blocker_id = p.author_id AND b.blocked_id = $1::text)
  )
GROUP BY h.tag
ORDER BY count(*) DESC, h.tag
LIMIT $2
`

type TrendingHashtagsParams struct {
	ViewerID string
	Lim      int32
}

type TrendingHashtagsRow struct {
	Tag  string
	Uses int32
}

// 많이 쓰인 태그. 공개 글만 세고, 차단 관계는 뺀다.
func (q *Queries) TrendingHashtags(ctx context.Context, arg TrendingHashtagsParams) ([]TrendingHashtagsRow, error) {
	rows, err := q.db.Query(ctx, trendingHashtags, arg.ViewerID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrendingHashtagsRow
	for rows.Next() {
		var i TrendingHashtagsRow
		if err := rows.Scan(&i.Tag, &i.Uses); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unblockUser = `-- name: UnblockUser :exec
DELETE FROM blocks WHERE blocker_id = $1 AND blocked_id = $2
`

type UnblockUserParams struct {
	BlockerID string
	BlockedID string
}

func (q *Queries) UnblockUser(ctx context.Context, arg UnblockUserParams) error {
	_, err := q.db.Exec(ctx, unblockUser, arg.BlockerID, arg.BlockedID)
	return err
}

const unbookmarkPost = `-- name: UnbookmarkPost :execrows
DELETE FROM post_bookmarks WHERE post_id = $1 AND user_id = $2
`

type UnbookmarkPostParams struct {
	PostID string
	UserID string
}

func (q *Queries) UnbookmarkPost(ctx context.Context, arg UnbookmarkPostParams) (int64, error) {
	result, err := q.db.Exec(ctx, unbookmarkPost, arg.PostID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const unfollow = `-- name: Unfollow :execrows
DELETE FROM follows WHERE follower_id = $1 AND followee_id = $2
`

type UnfollowParams struct {
	FollowerID string
	FolloweeID string
}

func (q *Queries) Unfollow(ctx context.Context, arg UnfollowParams) (int64, error) {
	result, err := q.db.Exec(ctx, unfollow, arg.FollowerID, arg.FolloweeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const unlikeComment = `-- name: UnlikeComment :execrows
DELETE FROM comment_likes WHERE comment_id = $1 AND user_id = $2
`

type UnlikeCommentParams struct {
	CommentID string
	UserID    string
}

func (q *Queries) UnlikeComment(ctx context.Context, arg UnlikeCommentParams) (int64, error) {
	result, err := q.db.Exec(ctx, unlikeComment, arg.CommentID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const unlikePost = `-- name: UnlikePost :execrows
DELETE FROM post_likes WHERE post_id = $1 AND user_id = $2
`

type UnlikePostParams struct {
	PostID string
	UserID string
}

func (q *Queries) UnlikePost(ctx context.Context, arg UnlikePostParams) (int64, error) {
	result, err := q.db.Exec(ctx, unlikePost, arg.PostID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updatePost = `-- name: UpdatePost :execrows
UPDATE posts
SET caption = $1,
    visibility = CASE WHEN $2::boolean THEN $3::text ELSE visibility END,
    updated_at = now()
WHERE id = $4::text AND author_id = $5::text
`

type UpdatePostParams struct {
	Caption       *string
	SetVisibility bool
	Visibility    string
	ID            string
	AuthorID      string
}

// 올린 뒤 고칠 수 있는 것은 캡션과 공개범위뿐이다. 운동 기록은 그때의 사실이라 손대지 않는다.
func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePost,
		arg.Caption,
		arg.SetVisibility,
		arg.Visibility,
		arg.ID,
		arg.AuthorID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
