// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: gear.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGearClick = `-- name: CreateGearClick :exec
INSERT INTO gear_clicks (id, user_id, post_id, category, source, kind)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateGearClickParams struct {
	ID       string
	UserID   string
	PostID   string
	Category string
	Source   string
	Kind     string
}

func (q *Queries) CreateGearClick(ctx context.Context, arg CreateGearClickParams) error {
	_, err := q.db.Exec(ctx, createGearClick,
		arg.ID,
		arg.UserID,
		arg.PostID,
		arg.Category,
		arg.Source,
		arg.Kind,
	)
	return err
}

const recentGearClickExists = `-- name: RecentGearClickExists :one

SELECT EXISTS (
  SELECT 1 FROM gear_clicks
  WHERE user_id = $1::text
    AND post_id = $2::text
    AND category = $3::text
    AND created_at >= $4::timestamptz
)::boolean
`

type RecentGearClickExistsParams struct {
	UserID   string
	PostID   string
	Category string
	Since    pgtype.Timestamptz
}

// @plm SRS-039  착용장비 클릭
// 같은 사람이 같은 글의 같은 장비를 짧은 시간에 다시 눌렀는가.
// 반복 클릭은 집계를 부풀릴 뿐 아니라 제재 사유이기도 하다 — 서버에서 눌러 둔다.
func (q *Queries) RecentGearClickExists(ctx context.Context, arg RecentGearClickExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, recentGearClickExists,
		arg.UserID,
		arg.PostID,
		arg.Category,
		arg.Since,
	)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}
