// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: media.sql

package sqlcgen

import (
	"context"
)

const createMediaAsset = `-- name: CreateMediaAsset :one

INSERT INTO media_assets (id, owner_id, key, url, content_type, kind, bytes, flagged, flag_reason)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, owner_id, key, url, content_type, kind, bytes, flagged, flag_reason, created_at
`

type CreateMediaAssetParams struct {
	ID          string
	OwnerID     string
	Key         string
	Url         string
	ContentType string
	Kind        string
	Bytes       int64
	Flagged     bool
	FlagReason  *string
}

// @plm SRS-019  미디어 쿼리 — 메타를 넣고, 키로 찾는다
//
// 바이트는 여기 없다(저장소에 있다). 이 파일이 아는 것은 "누가 올렸고 서브해도 되는가"뿐이다.
func (q *Queries) CreateMediaAsset(ctx context.Context, arg CreateMediaAssetParams) (MediaAsset, error) {
	row := q.db.QueryRow(ctx, createMediaAsset,
		arg.ID,
		arg.OwnerID,
		arg.Key,
		arg.Url,
		arg.ContentType,
		arg.Kind,
		arg.Bytes,
		arg.Flagged,
		arg.FlagReason,
	)
	var i MediaAsset
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Key,
		&i.Url,
		&i.ContentType,
		&i.Kind,
		&i.Bytes,
		&i.Flagged,
		&i.FlagReason,
		&i.CreatedAt,
	)
	return i, err
}

const getMediaAssetByKey = `-- name: GetMediaAssetByKey :one
SELECT id, owner_id, key, url, content_type, kind, bytes, flagged, flag_reason, created_at FROM media_assets WHERE key = $1
`

// 파일 서브가 매 요청 부른다 — 키에 유일 인덱스가 걸려 있다.
func (q *Queries) GetMediaAssetByKey(ctx context.Context, key string) (MediaAsset, error) {
	row := q.db.QueryRow(ctx, getMediaAssetByKey, key)
	var i MediaAsset
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Key,
		&i.Url,
		&i.ContentType,
		&i.Kind,
		&i.Bytes,
		&i.Flagged,
		&i.FlagReason,
		&i.CreatedAt,
	)
	return i, err
}
