// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Block struct {
	BlockerID string
	BlockedID string
	CreatedAt pgtype.Timestamptz
}

type CoachingAudit struct {
	ID        string
	GrantID   string
	ActorID   string
	Action    string
	Detail    []byte
	CreatedAt pgtype.Timestamptz
}

type CoachingGrant struct {
	ID          string
	TrainerID   string
	MemberID    string
	Status      string
	Scope       []byte
	RequestedBy string
	ConsentAt   pgtype.Timestamptz
	RevokedAt   pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Comment struct {
	ID               string
	PostID           string
	AuthorID         string
	Body             string
	ModerationStatus string
	CreatedAt        pgtype.Timestamptz
	ParentID         *string
	LikeCount        int32
	ReplyCount       int32
	RemovedAt        pgtype.Timestamptz
}

type CommentLike struct {
	CommentID string
	UserID    string
	CreatedAt pgtype.Timestamptz
}

type Conversation struct {
	ID        string
	IsGroup   bool
	DirectKey *string
	Title     *string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type ConversationParticipant struct {
	ConversationID string
	UserID         string
	LastReadAt     pgtype.Timestamptz
	JoinedAt       pgtype.Timestamptz
}

type Exercise struct {
	ID               string
	NameKo           string
	NameEn           *string
	PrimaryMuscles   []string
	SecondaryMuscles []string
	Equipment        string
	Kind             *string
	LoadMode         *string
	SubstituteIds    []string
	ImageUrl         *string
	IsCustom         bool
	IsArchived       bool
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type Follow struct {
	FollowerID string
	FolloweeID string
	CreatedAt  pgtype.Timestamptz
}

type GearClick struct {
	ID        string
	UserID    string
	PostID    string
	Category  string
	Source    string
	Kind      string
	CreatedAt pgtype.Timestamptz
}

type MediaAsset struct {
	ID          string
	OwnerID     string
	Key         string
	Url         string
	ContentType string
	Kind        string
	Bytes       int64
	Flagged     bool
	FlagReason  *string
	CreatedAt   pgtype.Timestamptz
}

type Message struct {
	ID             string
	ConversationID string
	SenderID       string
	Kind           string
	Body           *string
	MediaUrl       *string
	CreatedAt      pgtype.Timestamptz
}

type Notification struct {
	ID        string
	UserID    string
	Kind      string
	ActorID   string
	PostID    *string
	ReadAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type Post struct {
	ID               string
	AuthorID         string
	Kind             string
	Caption          *string
	Visibility       string
	ModerationStatus string
	WorkoutID        *string
	WorkoutName      *string
	TotalVolumeKg    *float64
	WorkingSets      *int32
	DurationSeconds  *int32
	PrCount          *int32
	MediaUrls        []string
	IdempotencyKey   *string
	LikeCount        int32
	CommentCount     int32
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	StreakDays       *int32
	WeeklyReached    *bool
	Exercises        []byte
	RemovedAt        pgtype.Timestamptz
	RemovedReason    *string
	Gear             []byte
}

type PostBookmark struct {
	PostID    string
	UserID    string
	CreatedAt pgtype.Timestamptz
}

type PostHashtag struct {
	PostID string
	Tag    string
}

type PostLike struct {
	PostID    string
	UserID    string
	CreatedAt pgtype.Timestamptz
}

type RefreshToken struct {
	TokenHash string
	UserID    string
	ExpiresAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type Report struct {
	ID          string
	TargetType  string
	TargetID    string
	ReporterID  string
	Reason      string
	Details     *string
	Status      string
	ReviewedBy  *string
	ReviewedAt  pgtype.Timestamptz
	ActionTaken *string
	CreatedAt   pgtype.Timestamptz
}

type Story struct {
	ID               string
	AuthorID         string
	MediaUrl         string
	Caption          *string
	ModerationStatus string
	CreatedAt        pgtype.Timestamptz
	ExpiresAt        pgtype.Timestamptz
	RemovedAt        pgtype.Timestamptz
	RemovedReason    *string
}

type SyncRecord struct {
	ID         string
	UserID     string
	Collection string
	RecordID   string
	Payload    []byte
	Deleted    bool
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type User struct {
	ID              string
	Email           *string
	DisplayName     *string
	AvatarUrl       *string
	PasswordHash    *string
	AuthProvider    string
	Role            string
	ExperienceLevel *string
	TrainerIntent   bool
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}
