// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: moderation.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReport = `-- name: CreateReport :exec

INSERT INTO reports (id, target_type, target_id, reporter_id, reason, details)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (reporter_id, target_type, target_id) DO NOTHING
`

type CreateReportParams struct {
	ID         string
	TargetType string
	TargetID   string
	ReporterID string
	Reason     string
	Details    *string
}

// @plm SRS-020  신고·모더레이션 쿼리
// 같은 신고자·대상은 한 건이다(유일 제약) — 다시 눌러도 조용히 넘어간다.
func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) error {
	_, err := q.db.Exec(ctx, createReport,
		arg.ID,
		arg.TargetType,
		arg.TargetID,
		arg.ReporterID,
		arg.Reason,
		arg.Details,
	)
	return err
}

const getCommentForModeration = `-- name: GetCommentForModeration :one
SELECT c.id, c.author_id, c.post_id, c.moderation_status, c.body, c.created_at,
       u.display_name AS author_name
FROM comments c JOIN users u ON u.id = c.author_id
WHERE c.id = $1
`

type GetCommentForModerationRow struct {
	ID               string
	AuthorID         string
	PostID           string
	ModerationStatus string
	Body             string
	CreatedAt        pgtype.Timestamptz
	AuthorName       *string
}

func (q *Queries) GetCommentForModeration(ctx context.Context, id string) (GetCommentForModerationRow, error) {
	row := q.db.QueryRow(ctx, getCommentForModeration, id)
	var i GetCommentForModerationRow
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.PostID,
		&i.ModerationStatus,
		&i.Body,
		&i.CreatedAt,
		&i.AuthorName,
	)
	return i, err
}

const getPostForModeration = `-- name: GetPostForModeration :one
SELECT p.id, p.author_id, p.moderation_status, p.kind, p.caption, p.media_urls, p.created_at,
       u.display_name AS author_name
FROM posts p JOIN users u ON u.id = p.author_id
WHERE p.id = $1
`

type GetPostForModerationRow struct {
	ID               string
	AuthorID         string
	ModerationStatus string
	Kind             string
	Caption          *string
	MediaUrls        []string
	CreatedAt        pgtype.Timestamptz
	AuthorName       *string
}

// ── 대상 조회(미리보기) ─────────────────────────────────────────────────────
func (q *Queries) GetPostForModeration(ctx context.Context, id string) (GetPostForModerationRow, error) {
	row := q.db.QueryRow(ctx, getPostForModeration, id)
	var i GetPostForModerationRow
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.ModerationStatus,
		&i.Kind,
		&i.Caption,
		&i.MediaUrls,
		&i.CreatedAt,
		&i.AuthorName,
	)
	return i, err
}

const getPostVisibility = `-- name: GetPostVisibility :one
SELECT author_id, visibility, moderation_status FROM posts WHERE id = $1
`

type GetPostVisibilityRow struct {
	AuthorID         string
	Visibility       string
	ModerationStatus string
}

// 가시성 판정에 쓰는 최소 조회.
func (q *Queries) GetPostVisibility(ctx context.Context, id string) (GetPostVisibilityRow, error) {
	row := q.db.QueryRow(ctx, getPostVisibility, id)
	var i GetPostVisibilityRow
	err := row.Scan(&i.AuthorID, &i.Visibility, &i.ModerationStatus)
	return i, err
}

const getStoryForModeration = `-- name: GetStoryForModeration :one
SELECT s.id, s.author_id, s.moderation_status, s.media_url, s.caption, s.created_at, s.expires_at,
       u.display_name AS author_name
FROM stories s JOIN users u ON u.id = s.author_id
WHERE s.id = $1
`

type GetStoryForModerationRow struct {
	ID               string
	AuthorID         string
	ModerationStatus string
	MediaUrl         string
	Caption          *string
	CreatedAt        pgtype.Timestamptz
	ExpiresAt        pgtype.Timestamptz
	AuthorName       *string
}

func (q *Queries) GetStoryForModeration(ctx context.Context, id string) (GetStoryForModerationRow, error) {
	row := q.db.QueryRow(ctx, getStoryForModeration, id)
	var i GetStoryForModerationRow
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.ModerationStatus,
		&i.MediaUrl,
		&i.Caption,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.AuthorName,
	)
	return i, err
}

const isFollowingSimple = `-- name: IsFollowingSimple :one
SELECT EXISTS (SELECT 1 FROM follows WHERE follower_id = $1 AND followee_id = $2)::boolean
`

type IsFollowingSimpleParams struct {
	FollowerID string
	FolloweeID string
}

func (q *Queries) IsFollowingSimple(ctx context.Context, arg IsFollowingSimpleParams) (bool, error) {
	row := q.db.QueryRow(ctx, isFollowingSimple, arg.FollowerID, arg.FolloweeID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const listPendingPosts = `-- name: ListPendingPosts :many
SELECT p.id, p.author_id, p.kind, p.caption, p.media_urls, p.created_at, u.display_name AS author_name
FROM posts p JOIN users u ON u.id = p.author_id
WHERE p.moderation_status = 'pending'
ORDER BY p.created_at DESC
LIMIT $1
`

type ListPendingPostsRow struct {
	ID         string
	AuthorID   string
	Kind       string
	Caption    *string
	MediaUrls  []string
	CreatedAt  pgtype.Timestamptz
	AuthorName *string
}

// ── 자동 보류된 것(신고가 없어도 검토 대상) ─────────────────────────────────
func (q *Queries) ListPendingPosts(ctx context.Context, lim int32) ([]ListPendingPostsRow, error) {
	rows, err := q.db.Query(ctx, listPendingPosts, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingPostsRow
	for rows.Next() {
		var i ListPendingPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Kind,
			&i.Caption,
			&i.MediaUrls,
			&i.CreatedAt,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingReports = `-- name: ListPendingReports :many
SELECT target_type, target_id, reason, created_at
FROM reports
WHERE status = 'pending'
ORDER BY created_at DESC
LIMIT $1
`

type ListPendingReportsRow struct {
	TargetType string
	TargetID   string
	Reason     string
	CreatedAt  pgtype.Timestamptz
}

// 아직 안 본 신고들. 대상별 묶음은 Go가 만든다(사유 집합·건수·가장 최근 시각).
func (q *Queries) ListPendingReports(ctx context.Context, lim int32) ([]ListPendingReportsRow, error) {
	rows, err := q.db.Query(ctx, listPendingReports, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingReportsRow
	for rows.Next() {
		var i ListPendingReportsRow
		if err := rows.Scan(
			&i.TargetType,
			&i.TargetID,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingStories = `-- name: ListPendingStories :many
SELECT s.id, s.author_id, s.media_url, s.caption, s.created_at, u.display_name AS author_name
FROM stories s JOIN users u ON u.id = s.author_id
WHERE s.moderation_status = 'pending'
ORDER BY s.created_at DESC
LIMIT $1
`

type ListPendingStoriesRow struct {
	ID         string
	AuthorID   string
	MediaUrl   string
	Caption    *string
	CreatedAt  pgtype.Timestamptz
	AuthorName *string
}

func (q *Queries) ListPendingStories(ctx context.Context, lim int32) ([]ListPendingStoriesRow, error) {
	rows, err := q.db.Query(ctx, listPendingStories, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingStoriesRow
	for rows.Next() {
		var i ListPendingStoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.MediaUrl,
			&i.Caption,
			&i.CreatedAt,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveReportsForTarget = `-- name: ResolveReportsForTarget :exec
UPDATE reports
SET status = $1::text,
    reviewed_by = $2::text,
    reviewed_at = now(),
    action_taken = $3::text
WHERE target_type = $4::text AND target_id = $5::text AND status = 'pending'
`

type ResolveReportsForTargetParams struct {
	Status      string
	ReviewedBy  string
	ActionTaken string
	TargetType  string
	TargetID    string
}

// 대상 하나에 달린 신고를 한꺼번에 종결한다.
func (q *Queries) ResolveReportsForTarget(ctx context.Context, arg ResolveReportsForTargetParams) error {
	_, err := q.db.Exec(ctx, resolveReportsForTarget,
		arg.Status,
		arg.ReviewedBy,
		arg.ActionTaken,
		arg.TargetType,
		arg.TargetID,
	)
	return err
}

const setCommentModeration = `-- name: SetCommentModeration :exec
UPDATE comments SET moderation_status = $1::text,
                    removed_at = CASE WHEN $2::boolean THEN now() ELSE NULL END
WHERE id = $3::text
`

type SetCommentModerationParams struct {
	Status  string
	Removed bool
	ID      string
}

func (q *Queries) SetCommentModeration(ctx context.Context, arg SetCommentModerationParams) error {
	_, err := q.db.Exec(ctx, setCommentModeration, arg.Status, arg.Removed, arg.ID)
	return err
}

const setMediaFlagged = `-- name: SetMediaFlagged :exec
UPDATE media_assets SET flagged = $1::boolean WHERE key = $2::text
`

type SetMediaFlaggedParams struct {
	Flagged bool
	Key     string
}

// 제거하면 사진의 바이트도 막는다(승인하면 다시 푼다) — "내려갔다"가 참이려면 파일도 안 보여야 한다.
func (q *Queries) SetMediaFlagged(ctx context.Context, arg SetMediaFlaggedParams) error {
	_, err := q.db.Exec(ctx, setMediaFlagged, arg.Flagged, arg.Key)
	return err
}

const setPostModeration = `-- name: SetPostModeration :exec
UPDATE posts SET moderation_status = $1::text,
                 removed_at = CASE WHEN $2::boolean THEN now() ELSE NULL END,
                 removed_reason = CASE WHEN $2::boolean THEN $3::text ELSE NULL END
WHERE id = $4::text
`

type SetPostModerationParams struct {
	Status  string
	Removed bool
	Reason  string
	ID      string
}

// ── 처리 ────────────────────────────────────────────────────────────────────
func (q *Queries) SetPostModeration(ctx context.Context, arg SetPostModerationParams) error {
	_, err := q.db.Exec(ctx, setPostModeration,
		arg.Status,
		arg.Removed,
		arg.Reason,
		arg.ID,
	)
	return err
}

const setStoryModeration = `-- name: SetStoryModeration :exec
UPDATE stories SET moderation_status = $1::text,
                   removed_at = CASE WHEN $2::boolean THEN now() ELSE NULL END,
                   removed_reason = CASE WHEN $2::boolean THEN $3::text ELSE NULL END
WHERE id = $4::text
`

type SetStoryModerationParams struct {
	Status  string
	Removed bool
	Reason  string
	ID      string
}

func (q *Queries) SetStoryModeration(ctx context.Context, arg SetStoryModerationParams) error {
	_, err := q.db.Exec(ctx, setStoryModeration,
		arg.Status,
		arg.Removed,
		arg.Reason,
		arg.ID,
	)
	return err
}
