// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notification.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT count(*)::int
FROM notifications n
WHERE n.user_id = $1::text
  AND n.read_at IS NULL
  AND NOT EXISTS (
    SELECT 1 FROM blocks b
    WHERE (b.blocker_id = $1::text AND b.blocked_id = n.actor_id)
       OR (b.blocker_id = n.actor_id AND b.blocked_id = $1::text)
  )
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, viewerID string) (int32, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, viewerID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createNotification = `-- name: CreateNotification :exec

INSERT INTO notifications (id, user_id, kind, actor_id, post_id)
VALUES ($1, $2, $3, $4, $5)
`

type CreateNotificationParams struct {
	ID      string
	UserID  string
	Kind    string
	ActorID string
	PostID  *string
}

// @plm SRS-020  알림 쿼리
//
// 차단한 사람이 일으킨 알림은 보이지 않는다 — 차단은 **양방향**이라 어느 쪽이 걸었든 가린다.
func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) error {
	_, err := q.db.Exec(ctx, createNotification,
		arg.ID,
		arg.UserID,
		arg.Kind,
		arg.ActorID,
		arg.PostID,
	)
	return err
}

const listNotifications = `-- name: ListNotifications :many
SELECT n.id, n.user_id, n.kind, n.actor_id, n.post_id, n.read_at, n.created_at, u.display_name AS actor_name, u.avatar_url AS actor_avatar
FROM notifications n
JOIN users u ON u.id = n.actor_id
WHERE n.user_id = $1::text
  AND NOT EXISTS (
    SELECT 1 FROM blocks b
    WHERE (b.blocker_id = $1::text AND b.blocked_id = n.actor_id)
       OR (b.blocker_id = n.actor_id AND b.blocked_id = $1::text)
  )
ORDER BY n.created_at DESC, n.id DESC
LIMIT $2
`

type ListNotificationsParams struct {
	ViewerID string
	Lim      int32
}

type ListNotificationsRow struct {
	ID          string
	UserID      string
	Kind        string
	ActorID     string
	PostID      *string
	ReadAt      pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	ActorName   *string
	ActorAvatar *string
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]ListNotificationsRow, error) {
	rows, err := q.db.Query(ctx, listNotifications, arg.ViewerID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNotificationsRow
	for rows.Next() {
		var i ListNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.ActorID,
			&i.PostID,
			&i.ReadAt,
			&i.CreatedAt,
			&i.ActorName,
			&i.ActorAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications SET read_at = now() WHERE user_id = $1 AND read_at IS NULL
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, markAllNotificationsRead, userID)
	return err
}
