// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: story.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStory = `-- name: CreateStory :one

INSERT INTO stories (id, author_id, media_url, caption, moderation_status, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, author_id, media_url, caption, moderation_status, created_at, expires_at, removed_at, removed_reason
`

type CreateStoryParams struct {
	ID               string
	AuthorID         string
	MediaUrl         string
	Caption          *string
	ModerationStatus string
	ExpiresAt        pgtype.Timestamptz
}

// @plm SRS-019  스토리 쿼리
//
// **누구의 스토리를 고를 것인가**는 SQL이 한다(팔로우·차단 목록을 Go로 끌어와 거르면
// 사람이 늘수록 느려진다 — 피드와 같은 판단).
func (q *Queries) CreateStory(ctx context.Context, arg CreateStoryParams) (Story, error) {
	row := q.db.QueryRow(ctx, createStory,
		arg.ID,
		arg.AuthorID,
		arg.MediaUrl,
		arg.Caption,
		arg.ModerationStatus,
		arg.ExpiresAt,
	)
	var i Story
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.MediaUrl,
		&i.Caption,
		&i.ModerationStatus,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RemovedAt,
		&i.RemovedReason,
	)
	return i, err
}

const listActiveStories = `-- name: ListActiveStories :many
SELECT s.id, s.author_id, s.media_url, s.caption, s.moderation_status, s.created_at, s.expires_at, s.removed_at, s.removed_reason, u.display_name AS author_name, u.avatar_url AS author_avatar
FROM stories s
JOIN users u ON u.id = s.author_id
WHERE s.expires_at > now()
  AND s.moderation_status = 'approved'
  AND (
    s.author_id = $1::text
    OR EXISTS (
      SELECT 1 FROM follows f
      WHERE f.follower_id = $1::text AND f.followee_id = s.author_id
    )
  )
  AND NOT EXISTS (
    SELECT 1 FROM blocks b
    WHERE (b.blocker_id = $1::text AND b.blocked_id = s.author_id)
       OR (b.blocker_id = s.author_id AND b.blocked_id = $1::text)
  )
ORDER BY s.author_id, s.created_at ASC, s.id ASC
`

type ListActiveStoriesRow struct {
	ID               string
	AuthorID         string
	MediaUrl         string
	Caption          *string
	ModerationStatus string
	CreatedAt        pgtype.Timestamptz
	ExpiresAt        pgtype.Timestamptz
	RemovedAt        pgtype.Timestamptz
	RemovedReason    *string
	AuthorName       *string
	AuthorAvatar     *string
}

// 살아 있는 스토리 — 나 + 내가 팔로우하는 사람, 만료 전, 승인된 것.
// 차단은 **양방향**으로 가린다. 정렬은 (사람, 오래된 것 먼저) — 넘겨 보는 순서 그대로.
func (q *Queries) ListActiveStories(ctx context.Context, viewerID string) ([]ListActiveStoriesRow, error) {
	rows, err := q.db.Query(ctx, listActiveStories, viewerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveStoriesRow
	for rows.Next() {
		var i ListActiveStoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.MediaUrl,
			&i.Caption,
			&i.ModerationStatus,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.RemovedAt,
			&i.RemovedReason,
			&i.AuthorName,
			&i.AuthorAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
