#!/bin/bash
# setup-env.sh — .env 대화형 생성 (프로젝트 선택 포함)

set -euo pipefail

ENV_FILE="${1:-.ouroboros/env/.env}"
DEFAULT_PROJECT=$(basename "$(pwd)")

if [ -f "$ENV_FILE" ]; then
    # 설치 스크립트가 이미 완전한 .env를 생성한 경우 — 프롬프트 없이 조용히 유지
    if grep -q '^OUROBOROS_URL=.' "$ENV_FILE" && grep -q '^DEVELOPER_USER_ID=.' "$ENV_FILE" && grep -q '^PROJECT_ID=.' "$ENV_FILE"; then
        echo "[OK] .ouroboros/env/.env 이미 구성됨 — 유지합니다. (재설정: rm $ENV_FILE && make env)"
        exit 0
    fi
    # 존재하지만 필수 항목이 비어 있을 때만 재설정 여부 질문
    echo ".ouroboros/env/.env 가 존재하지만 일부 필수 항목이 비어 있습니다."
    printf "다시 설정하시겠습니까? (y/N) "
    read -r yn
    case $yn in [Yy]*) ;; *) echo "유지함."; exit 0;; esac
fi

echo ""
echo "=== Ouroboros 워크플로우 설정 ==="
echo ""

# 1. URL
printf "Ouroboros URL [https://ouro.jungmin.kim]: "
read -r ouro_url
ouro_url=${ouro_url:-https://ouro.jungmin.kim}

# 2. API Key (선택 — Claude 실행 후 MCP에서 인증하면 불필요)
printf "API Key (선택, 비우면 Claude의 MCP에서 인증): "
read -r ouro_key

# 3. 키가 있으면 검증 + 사용자 정보 추출. 없으면 MCP 인증에 위임.
user_id=""; role=""
if [ -n "$ouro_key" ]; then
    echo ""
    echo "키 검증 중..."
    login_result=$(curl -sf -X POST "${ouro_url}/api/auth/login" \
        -H "Content-Type: application/json" \
        -d "{\"license_key\":\"${ouro_key}\"}" 2>/dev/null || echo "{}")
    user_id=$(echo "$login_result" | python3 -c "import json,sys;print(json.load(sys.stdin).get('user_id',''))" 2>/dev/null || echo "")
    role=$(echo "$login_result" | python3 -c "import json,sys;print(json.load(sys.stdin).get('role',''))" 2>/dev/null || echo "")
    token=$(echo "$login_result" | python3 -c "import json,sys;print(json.load(sys.stdin).get('token',''))" 2>/dev/null || echo "")
    if [ -n "$user_id" ] && [ -n "$token" ]; then
        echo "  ✅ 인증 성공: ${user_id} (${role})"
    else
        echo "  ⚠️  키 검증 실패(서버 미연결 또는 키 오류) — 계속 진행."
        printf "DEVELOPER_USER_ID (선택, 비우면 MCP 인증 시 결정): "
        read -r user_id
    fi
else
    echo "  ℹ️  API Key 생략 — Claude 실행 후 MCP에서 인증합니다."
    printf "DEVELOPER_USER_ID (선택, 비우면 MCP 인증 시 결정): "
    read -r user_id
fi

# 4. 프로젝트 선택
echo ""
echo "프로젝트 설정:"

projects=""
if [ -n "$ouro_key" ]; then
    projects=$(curl -sf "${ouro_url}/api/projects" \
        -H "Authorization: Bearer ${ouro_key}" 2>/dev/null | \
        python3 -c "
import json, sys
data = json.load(sys.stdin)
projects = data.get('projects', [])
for i, p in enumerate(projects):
    print(f'{p}')
" 2>/dev/null || echo "")
fi

if [ -n "$projects" ]; then
    echo ""
    echo "  기존 프로젝트:"
    i=1
    echo "$projects" | while read -r p; do
        echo "    ${i}. ${p}"
        i=$((i + 1))
    done
    echo "    0. 새 프로젝트 직접 입력"
    echo ""
    printf "  번호 선택 또는 프로젝트명 입력 [${DEFAULT_PROJECT}]: "
    read -r pid_input

    if [ -z "$pid_input" ]; then
        pid="$DEFAULT_PROJECT"
    elif echo "$pid_input" | grep -qE '^[0-9]+$'; then
        if [ "$pid_input" = "0" ]; then
            printf "  새 프로젝트 ID: "
            read -r pid
        else
            pid=$(echo "$projects" | sed -n "${pid_input}p")
        fi
    else
        pid="$pid_input"
    fi
else
    echo "  (서버에서 프로젝트 목록을 가져올 수 없습니다)"
    printf "  프로젝트 ID [${DEFAULT_PROJECT}]: "
    read -r pid
fi

pid=${pid:-$DEFAULT_PROJECT}

# 5. .env 생성
echo ""
{
    echo "# Auto-generated by: make env"
    echo "# $(date '+%Y-%m-%d %H:%M')"
    echo ""
    echo "# --- 필수 ---"
    echo "OUROBOROS_URL=${ouro_url}"
    [ -z "$ouro_key" ] && echo "# API Key 생략 — Claude의 MCP(OAuth)에서 인증 (.mcp.json 참조)"
    echo "OUROBOROS_API_KEY=${ouro_key}"
    echo "DEVELOPER_USER_ID=${user_id}"
    echo ""
    echo "# --- 선택 ---"
    echo "PROJECT_ID=${pid}"
    echo ""
    echo "# --- 대화 기록 (옵션, 비워두면 비활성화) ---"
    echo "# EVENT_LOG_URL=${ouro_url/ouro./ouro-dash.}"
} > "$ENV_FILE"

echo "=== .ouroboros/env/.env 생성 완료 ==="
echo ""
cat "$ENV_FILE"
echo ""
echo "다음 단계: make init"
