// @plm SRS-007  아이콘 — app과 같은 글리프(Ionicons)를 웹에서 쓴다
//
// app은 `@expo/vector-icons`의 Ionicons를 쓴다. 웹에는 그 패키지가 없으므로 같은 아이콘 세트를
// 담은 `react-icons/io5`로 대체하되, **호출 방식은 app과 같게** 둔다: `<Icon name="barbell" />`.
// 그래야 화면을 옮길 때 아이콘 코드를 고쳐 쓸 일이 없다.
//
// 이름을 하나하나 import하는 이유: 통째로 불러오면 쓰지도 않는 수천 개가 번들에 실린다.
// 목록은 app에서 실제로 쓰는 것만 추린 것이고, 없는 이름을 쓰면 **타입 검사가 잡는다**.
import {
  IoAdd,
  IoAddCircle,
  IoAlertCircleOutline,
  IoAppsOutline,
  IoBarbell,
  IoBarbellOutline,
  IoCalendar,
  IoCalendarOutline,
  IoCamera,
  IoChatboxEllipses,
  IoLockClosedOutline,
  IoSendOutline,
  IoChatboxEllipsesOutline,
  IoChatbubbleEllipsesOutline,
  IoChatbubbleOutline,
  IoChatbubblesOutline,
  IoCheckmark,
  IoCheckmarkCircle,
  IoCheckmarkCircleOutline,
  IoChevronBack,
  IoChevronDown,
  IoChevronForward,
  IoChevronUp,
  IoClipboardOutline,
  IoClose,
  IoCloseCircle,
  IoCloudDoneOutline,
  IoCloudDownloadOutline,
  IoCloudOfflineOutline,
  IoCompassOutline,
  IoCreateOutline,
  IoDownloadOutline,
  IoEllipsisHorizontal,
  IoExitOutline,
  IoFilmOutline,
  IoEllipseOutline,
  IoFitnessOutline,
  IoFlagOutline,
  IoFlame,
  IoFlash,
  IoFolder,
  IoFolderOpen,
  IoFolderOutline,
  IoFunnel,
  IoGitMergeOutline,
  IoHeart,
  IoHeartOutline,
  IoHelpCircleOutline,
  IoHourglassOutline,
  IoImageOutline,
  IoInformationCircleOutline,
  IoListOutline,
  IoLocation,
  IoLocationOutline,
  IoMoon,
  IoNotificationsOutline,
  IoOpenOutline,
  IoOptionsOutline,
  IoPencil,
  IoPause,
  IoPeopleOutline,
  IoPerson,
  IoPersonAddOutline,
  IoPlay,
  IoNavigate,
  IoRefresh,
  IoResize,
  IoRemove,
  IoRemoveCircle,
  IoReorderThree,
  IoSearchOutline,
  IoShieldCheckmarkOutline,
  IoSparkles,
  IoStar,
  IoStatsChart,
  IoSwapHorizontalOutline,
  IoTime,
  IoTimeOutline,
  IoTimerOutline,
  IoTrashOutline,
  IoTrophy,
  IoBookmark,
  IoBookmarkOutline,
  IoNewspaperOutline,
  IoPersonCircleOutline,
  IoPricetagOutline,
  IoSend,
} from "react-icons/io5";

const GLYPHS = {
  add: IoAdd,
  "add-circle": IoAddCircle,
  barbell: IoBarbell,
  "apps-outline": IoAppsOutline,
  "barbell-outline": IoBarbellOutline,
  calendar: IoCalendar,
  "calendar-outline": IoCalendarOutline,
  camera: IoCamera,
  "chatbox-ellipses": IoChatboxEllipses,
  "lock-closed-outline": IoLockClosedOutline,
  "send-outline": IoSendOutline,
  "chatbox-ellipses-outline": IoChatboxEllipsesOutline,
  "chatbubble-ellipses-outline": IoChatbubbleEllipsesOutline,
  "chatbubble-outline": IoChatbubbleOutline,
  "chatbubbles-outline": IoChatbubblesOutline,
  checkmark: IoCheckmark,
  "checkmark-circle": IoCheckmarkCircle,
  "checkmark-circle-outline": IoCheckmarkCircleOutline,
  "chevron-back": IoChevronBack,
  "chevron-down": IoChevronDown,
  "chevron-forward": IoChevronForward,
  "chevron-up": IoChevronUp,
  "clipboard-outline": IoClipboardOutline,
  close: IoClose,
  "close-circle": IoCloseCircle,
  "alert-circle-outline": IoAlertCircleOutline,
  "cloud-done-outline": IoCloudDoneOutline,
  "cloud-download-outline": IoCloudDownloadOutline,
  "cloud-offline-outline": IoCloudOfflineOutline,
  "compass-outline": IoCompassOutline,
  "create-outline": IoCreateOutline,
  "download-outline": IoDownloadOutline,
  "ellipsis-horizontal": IoEllipsisHorizontal,
  "exit-outline": IoExitOutline,
  "film-outline": IoFilmOutline,
  "ellipse-outline": IoEllipseOutline,
  "fitness-outline": IoFitnessOutline,
  "flag-outline": IoFlagOutline,
  flame: IoFlame,
  flash: IoFlash,
  folder: IoFolder,
  "folder-open": IoFolderOpen,
  "folder-outline": IoFolderOutline,
  funnel: IoFunnel,
  "git-merge-outline": IoGitMergeOutline,
  heart: IoHeart,
  "heart-outline": IoHeartOutline,
  "help-circle-outline": IoHelpCircleOutline,
  "hourglass-outline": IoHourglassOutline,
  "image-outline": IoImageOutline,
  "information-circle-outline": IoInformationCircleOutline,
  location: IoLocation,
  "list-outline": IoListOutline,
  "location-outline": IoLocationOutline,
  moon: IoMoon,
  "notifications-outline": IoNotificationsOutline,
  "open-outline": IoOpenOutline,
  "options-outline": IoOptionsOutline,
  pause: IoPause,
  pencil: IoPencil,
  "people-outline": IoPeopleOutline,
  person: IoPerson,
  "person-add-outline": IoPersonAddOutline,
  play: IoPlay,
  navigate: IoNavigate,
  refresh: IoRefresh,
  resize: IoResize,
  remove: IoRemove,
  "remove-circle": IoRemoveCircle,
  "reorder-three": IoReorderThree,
  "search-outline": IoSearchOutline,
  "shield-checkmark-outline": IoShieldCheckmarkOutline,
  sparkles: IoSparkles,
  star: IoStar,
  "stats-chart": IoStatsChart,
  "swap-horizontal-outline": IoSwapHorizontalOutline,
  time: IoTime,
  "time-outline": IoTimeOutline,
  "timer-outline": IoTimerOutline,
  "trash-outline": IoTrashOutline,
  trophy: IoTrophy,
  bookmark: IoBookmark,
  "bookmark-outline": IoBookmarkOutline,
  "newspaper-outline": IoNewspaperOutline,
  "person-circle-outline": IoPersonCircleOutline,
  "pricetag-outline": IoPricetagOutline,
  send: IoSend,
} as const;

export type IconName = keyof typeof GLYPHS;

/** app의 `<Ionicons name size color />`와 같은 자리에 그대로 놓을 수 있다. */
export function Icon({
  name,
  size = 18,
  color = "currentColor",
  className,
}: {
  name: IconName;
  size?: number;
  color?: string;
  className?: string;
}) {
  const G = GLYPHS[name];
  return <G size={size} color={color} className={className} aria-hidden />;
}
