#!/usr/bin/env bash
# Ouroboros Document Template Installer
# Usage: curl -fsSL 'https://ouro.jungmin.kim/install.sh' | bash
#
# 크로스 플랫폼: Linux, macOS, Windows (Git Bash / WSL)
# 의존성: bash, curl, tar, sed (모두 Git Bash에 내장)
# 인증: Keycloak OAuth (API key 불필요)
set -euo pipefail

OURO_URL="${OURO_URL:-__OURO_URL__}"

# ---------------------------------------------------------------------------
# 설치 시작
# ---------------------------------------------------------------------------
echo ""
echo "  Ouroboros Document Template Installer"
echo "  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# 1. 설치 위치 확인
TARGET_DIR="$(pwd)"
echo "  설치 위치: $TARGET_DIR"

if [ -e /dev/tty ]; then
  read -rp "  계속하시겠습니까? (Y/n): " CONFIRM < /dev/tty
else
  CONFIRM="Y"
fi

case "$CONFIRM" in
  [Nn]*) echo "  취소되었습니다."; exit 0 ;;
esac

# 2. Template 다운로드 (public — 인증은 Claude Code MCP 연결 시 OAuth로 수행)
echo "  템플릿 다운로드 중..."
TMPFILE=$(mktemp "${TMPDIR:-/tmp}/ouro-template-XXXXXX")
HTTP_CODE=$(curl -sf -o "$TMPFILE" -w "%{http_code}" \
  "$OURO_URL/api/template-doc/download" 2>/dev/null || echo "000")

if [ "$HTTP_CODE" != "200" ]; then
  echo "  다운로드 실패 (HTTP $HTTP_CODE)"
  rm -f "$TMPFILE"
  exit 1
fi

# 3. 기존 파일 백업
echo "  설치 중..."

BACKUP="$TARGET_DIR/.claude.backup.$(date +%Y%m%d%H%M%S)"
HAS_BACKUP=false
for item in .claude .ouroboros .mcp.json CLAUDE.md; do
  if [ -e "$TARGET_DIR/$item" ]; then
    mkdir -p "$BACKUP"
    mv "$TARGET_DIR/$item" "$BACKUP/$item"
    HAS_BACKUP=true
  fi
done
if [ "$HAS_BACKUP" = true ]; then
  echo "  기존 파일 백업 → $BACKUP"
fi

# 4. 압축 해제
tar -xzf "$TMPFILE" -C "$TARGET_DIR"
rm -f "$TMPFILE"

# 5. 실행 권한
chmod +x "$TARGET_DIR/.ouroboros/hooks/"*.sh 2>/dev/null || true
chmod +x "$TARGET_DIR/.ouroboros/scripts/"*.sh 2>/dev/null || true

# 6. .gitignore 업데이트
GITIGNORE="$TARGET_DIR/.gitignore"
for entry in ".ouroboros/env/" ".claude.backup.*/" ".mcp.json"; do
  if [ -f "$GITIGNORE" ]; then
    grep -qxF "$entry" "$GITIGNORE" 2>/dev/null || echo "$entry" >> "$GITIGNORE"
  else
    echo "$entry" >> "$GITIGNORE"
  fi
done
echo "  .gitignore 업데이트"

# 7. docs 디렉토리 생성
mkdir -p "$TARGET_DIR/.ouroboros/docs/"{spec,qa,knowledge,study,todo}

# 8. 사용자 정보 입력
echo ""
echo "  사용자 설정"
DEFAULT_PROJECT=$(basename "$TARGET_DIR")

if [ -e /dev/tty ]; then
  read -rp "  Keycloak Username: " USER_ID < /dev/tty
  read -rp "  프로젝트 ID [$DEFAULT_PROJECT]: " PROJECT_ID < /dev/tty
else
  USER_ID="${USER:-local}"
  PROJECT_ID=""
fi

USER_ID="${USER_ID:-local}"
PROJECT_ID="${PROJECT_ID:-$DEFAULT_PROJECT}"

# 9. .ouroboros/env/.env 생성
mkdir -p "$TARGET_DIR/.ouroboros/env"
cat > "$TARGET_DIR/.ouroboros/env/.env" << ENVEOF
# Auto-generated by: Ouroboros Installer
# $(date '+%Y-%m-%d %H:%M')

# --- 필수 ---
OUROBOROS_URL=$OURO_URL
DEVELOPER_USER_ID=$USER_ID

# --- 프로젝트 ---
PROJECT_ID=$PROJECT_ID
ENVEOF
echo "  .ouroboros/env/.env 생성"

# 10. .mcp.json 생성 (Keycloak OAuth)
cat > "$TARGET_DIR/.mcp.json" << MCPEOF
{
  "mcpServers": {
    "ouroboros": {
      "type": "http",
      "url": "$OURO_URL/mcp",
      "oauth": {
        "clientId": "claude-code-mcp"
      }
    },
    "sequential-thinking": {
      "command": "npx",
      "args": ["-y", "@modelcontextprotocol/server-sequential-thinking"]
    },
    "context7": {
      "command": "npx",
      "args": ["-y", "@upstash/context7-mcp"]
    },
    "serena": {
      "command": "uvx",
      "args": [
        "--from", "git+https://github.com/oraios/serena",
        "serena-mcp-server",
        "--context", "ide-assistant",
        "--project", "."
      ]
    }
  }
}
MCPEOF
echo "  .mcp.json 생성 (OAuth + 4 MCP servers)"

# 11. Makefile 연결
if [ ! -f "$TARGET_DIR/Makefile" ]; then
  echo "include .ouroboros/Makefile" > "$TARGET_DIR/Makefile"
  echo "  Makefile 생성"
elif ! grep -q ".ouroboros/Makefile" "$TARGET_DIR/Makefile" 2>/dev/null; then
  echo ""
  echo "  기존 Makefile 발견 — Ouroboros 명령어:"
  echo "    make -f .ouroboros/Makefile guide"
fi

# 12. 문서 읽기 도구 설치 확인
echo ""
echo "  문서 읽기 도구 확인..."
MISSING=""
python3 -c "import markitdown" 2>/dev/null || MISSING="markitdown"
python3 -c "import fitz" 2>/dev/null || MISSING="$MISSING pymupdf"
if [ -n "$MISSING" ]; then
  echo "  (선택) 문서 변환 도구 미설치: $MISSING"
  echo "  설치: pip install markitdown pymupdf pdfminer.six mammoth openpyxl pandas python-pptx"
else
  echo "  문서 읽기 도구 OK"
fi

# 13. 완료
echo ""
echo "  Ouroboros 설치 완료!"
echo "  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  설치된 항목:"
echo "    .claude/commands/      13개 스킬"
echo "    .claude/CLAUDE.md      워크플로우 가이드 (SSoT)"
echo "    .ouroboros/hooks/      7개 Hook"
echo "    .ouroboros/Makefile    워크플로우 명령어"
echo "    .ouroboros/env/.env    서버 연결 설정"
echo "    .mcp.json              MCP 서버 연결 (OAuth)"
echo "    CLAUDE.md              핵심 지침 + 문서 읽기 규칙"
echo ""
echo "  인증 방식: Keycloak OAuth (API key 불필요)"
echo "  Claude Code에서 /mcp → ouroboros → Authenticate로 로그인"
echo ""
echo "  다음 단계:"
echo "    make status             설정 확인"
echo "    make guide              시스템 가이드"
echo "    /suggest                다음 작업 추천"
echo ""
