#!/usr/bin/env bash
# plan-db Workflow Template Installer (plan + code + plm-hub)
# Usage: curl -fsSL 'https://ouro.jungmin.kim/install.sh' | bash
#
# 크로스 플랫폼: Linux, macOS, Windows (Git Bash / WSL)
# 의존성: bash, curl, tar, sed. 인증은 Claude Code MCP 연결 시 OAuth(API key 불필요).
set -euo pipefail

OURO_URL="${OURO_URL:-__OURO_URL__}"

echo ""
echo "  plan-db Workflow Template Installer"
echo "  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  plan(기획) + code(코딩) + plm-hub(PLM 거버넌스) 플러그인"
echo ""

# 1. 설치 위치
TARGET_DIR="$(pwd)"
echo "  설치 위치: $TARGET_DIR"
if [ -e /dev/tty ]; then
  read -rp "  계속하시겠습니까? (Y/n): " CONFIRM < /dev/tty
else
  CONFIRM="Y"
fi
case "$CONFIRM" in [Nn]*) echo "  취소되었습니다."; exit 0 ;; esac

# 2. 템플릿 다운로드 (public — 인증은 Claude Code MCP OAuth)
echo "  템플릿 다운로드 중..."
TMPFILE=$(mktemp "${TMPDIR:-/tmp}/plandb-template-XXXXXX")
HTTP_CODE=$(curl -sf -o "$TMPFILE" -w "%{http_code}" "$OURO_URL/api/template/download" 2>/dev/null || echo "000")
if [ "$HTTP_CODE" != "200" ]; then
  echo "  다운로드 실패 (HTTP $HTTP_CODE)"; rm -f "$TMPFILE"; exit 1
fi

# 3. 기존 파일 백업 (템플릿이 제공하는 항목)
echo "  설치 중..."
BACKUP="$TARGET_DIR/.plandb.backup.$(date +%Y%m%d%H%M%S)"
HAS_BACKUP=false
for item in .template .ouroboros .claude-plugin .mcp.json .plmignore CLAUDE.md README.md INSTALL.md Makefile .gitattributes; do
  if [ -e "$TARGET_DIR/$item" ]; then
    mkdir -p "$BACKUP"; mv "$TARGET_DIR/$item" "$BACKUP/$item"; HAS_BACKUP=true
  fi
done
[ "$HAS_BACKUP" = true ] && echo "  기존 파일 백업 → $BACKUP"

# 4. 압축 해제
tar -xzf "$TMPFILE" -C "$TARGET_DIR"
rm -f "$TMPFILE"

# 5. 실행 권한 (.template/ 하위 hooks·scripts)
for d in \
  "$TARGET_DIR/.template/plugins"/*/hooks \
  "$TARGET_DIR/.template/plm-hub/plugin/hooks" \
  "$TARGET_DIR/.template/plm-hub/scripts" \
  "$TARGET_DIR/.template/scripts"; do
  [ -d "$d" ] && chmod +x "$d"/*.sh 2>/dev/null || true
done

# 6. .gitignore 보강
GITIGNORE="$TARGET_DIR/.gitignore"
for entry in ".ouroboros/env/" ".plandb.backup.*/"; do
  if [ -f "$GITIGNORE" ]; then grep -qxF "$entry" "$GITIGNORE" 2>/dev/null || echo "$entry" >> "$GITIGNORE";
  else echo "$entry" >> "$GITIGNORE"; fi
done

# 7. 사용자 설정 → .ouroboros/env/.env
echo ""
echo "  사용자 설정"
DEFAULT_PROJECT=$(basename "$TARGET_DIR")
if [ -e /dev/tty ]; then
  read -rp "  Keycloak Username (Ouroboros): " USER_ID < /dev/tty
  read -rp "  프로젝트 ID [$DEFAULT_PROJECT]: " PROJECT_ID < /dev/tty
else
  USER_ID="${USER:-local}"; PROJECT_ID=""
fi
USER_ID="${USER_ID:-local}"; PROJECT_ID="${PROJECT_ID:-$DEFAULT_PROJECT}"
mkdir -p "$TARGET_DIR/.ouroboros/env"
cat > "$TARGET_DIR/.ouroboros/env/.env" << ENVEOF
# Auto-generated by plan-db Installer · $(date '+%Y-%m-%d %H:%M')
# --- Ouroboros (메모리/KG MCP) ---
OUROBOROS_URL=$OURO_URL
DEVELOPER_USER_ID=$USER_ID
PROJECT_ID=$PROJECT_ID
# --- PLM-Hub (거버넌스) : 쓰기 토큰 — plm-hub:link 실행 시 SSO 인증으로 자동 발급·기입 ---
PLM_API_TOKEN=
ENVEOF

# 8. .mcp.json 의 OURO_URL 반영(템플릿 기본값 → 실제 URL)
if [ -f "$TARGET_DIR/.mcp.json" ]; then
  sed -i.bak "s#https://ouro.jungmin.kim#$OURO_URL#g" "$TARGET_DIR/.mcp.json" 2>/dev/null || true
  rm -f "$TARGET_DIR/.mcp.json.bak"
fi

echo ""
echo "  ✓ 설치 완료 — plan-db 템플릿"
echo "  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  구조: .template/(플러그인·plm-hub·guide·scripts) · .ouroboros/(상태) · .mcp.json"
echo ""
echo "  다음 단계:"
echo "   1) make setup            # plan·code·plm-hub 플러그인 + MCP + 시드 + 가이드 설치"
echo "   2) Claude 재실행 → 프로젝트 신뢰 → ouroboros·plm MCP OAuth 승인"
echo "   3) plm-hub:link <project-id>   # PLM 프로젝트 바인딩(plm.jungmin.kim) + .env의 PLM_API_TOKEN 입력"
echo "   4) 기획 plan:plan→requirement→design→decision→trace · 코딩 code:spec→execute→qa"
echo ""
echo "   가이드: make guide        설계: .template/plm-hub/plugin/HOOKS.md"
echo ""
